// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: badrequest/v1/badrequest.proto
// Protobuf Java Version: 4.34.1

package io.altessa.badrequest.v1;

@com.google.protobuf.Generated
public interface BadRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.altessa.badrequest.v1.BadRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A list of individual field violations that contributed to the bad request.
   * </pre>
   *
   * <code>repeated .io.altessa.badrequest.v1.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
   */
  java.util.List<io.altessa.badrequest.v1.FieldViolation> 
      getFieldViolationsList();
  /**
   * <pre>
   * A list of individual field violations that contributed to the bad request.
   * </pre>
   *
   * <code>repeated .io.altessa.badrequest.v1.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
   */
  io.altessa.badrequest.v1.FieldViolation getFieldViolations(int index);
  /**
   * <pre>
   * A list of individual field violations that contributed to the bad request.
   * </pre>
   *
   * <code>repeated .io.altessa.badrequest.v1.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
   */
  int getFieldViolationsCount();
  /**
   * <pre>
   * A list of individual field violations that contributed to the bad request.
   * </pre>
   *
   * <code>repeated .io.altessa.badrequest.v1.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
   */
  java.util.List<? extends io.altessa.badrequest.v1.FieldViolationOrBuilder> 
      getFieldViolationsOrBuilderList();
  /**
   * <pre>
   * A list of individual field violations that contributed to the bad request.
   * </pre>
   *
   * <code>repeated .io.altessa.badrequest.v1.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
   */
  io.altessa.badrequest.v1.FieldViolationOrBuilder getFieldViolationsOrBuilder(
      int index);
}
