// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: badrequest/v1/badrequest.proto

package io.altessa.badrequest.v1;

/**
 * <pre>
 * Defines a general error structure for requests that are malformed or contain invalid data.
 * It typically includes a list of specific field violations that caused the request to be rejected.
 * This message is often used as a detail payload for `google.rpc.Status` when the error code is `INVALID_ARGUMENT`.
 * </pre>
 *
 * Protobuf type {@code io.altessa.badrequest.v1.BadRequest}
 */
public final class BadRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.altessa.badrequest.v1.BadRequest)
    BadRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BadRequest.newBuilder() to construct.
  private BadRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BadRequest() {
    fieldViolations_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BadRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.altessa.badrequest.v1.Badrequest.internal_static_io_altessa_badrequest_v1_BadRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.altessa.badrequest.v1.Badrequest.internal_static_io_altessa_badrequest_v1_BadRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.altessa.badrequest.v1.BadRequest.class, io.altessa.badrequest.v1.BadRequest.Builder.class);
  }

  public static final int FIELD_VIOLATIONS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<io.altessa.badrequest.v1.FieldViolation> fieldViolations_;
  /**
   * <pre>
   * A list of individual field violations that contributed to the bad request.
   * </pre>
   *
   * <code>repeated .io.altessa.badrequest.v1.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
   */
  @java.lang.Override
  public java.util.List<io.altessa.badrequest.v1.FieldViolation> getFieldViolationsList() {
    return fieldViolations_;
  }
  /**
   * <pre>
   * A list of individual field violations that contributed to the bad request.
   * </pre>
   *
   * <code>repeated .io.altessa.badrequest.v1.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.altessa.badrequest.v1.FieldViolationOrBuilder> 
      getFieldViolationsOrBuilderList() {
    return fieldViolations_;
  }
  /**
   * <pre>
   * A list of individual field violations that contributed to the bad request.
   * </pre>
   *
   * <code>repeated .io.altessa.badrequest.v1.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
   */
  @java.lang.Override
  public int getFieldViolationsCount() {
    return fieldViolations_.size();
  }
  /**
   * <pre>
   * A list of individual field violations that contributed to the bad request.
   * </pre>
   *
   * <code>repeated .io.altessa.badrequest.v1.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
   */
  @java.lang.Override
  public io.altessa.badrequest.v1.FieldViolation getFieldViolations(int index) {
    return fieldViolations_.get(index);
  }
  /**
   * <pre>
   * A list of individual field violations that contributed to the bad request.
   * </pre>
   *
   * <code>repeated .io.altessa.badrequest.v1.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
   */
  @java.lang.Override
  public io.altessa.badrequest.v1.FieldViolationOrBuilder getFieldViolationsOrBuilder(
      int index) {
    return fieldViolations_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < fieldViolations_.size(); i++) {
      output.writeMessage(1, fieldViolations_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < fieldViolations_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, fieldViolations_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.altessa.badrequest.v1.BadRequest)) {
      return super.equals(obj);
    }
    io.altessa.badrequest.v1.BadRequest other = (io.altessa.badrequest.v1.BadRequest) obj;

    if (!getFieldViolationsList()
        .equals(other.getFieldViolationsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getFieldViolationsCount() > 0) {
      hash = (37 * hash) + FIELD_VIOLATIONS_FIELD_NUMBER;
      hash = (53 * hash) + getFieldViolationsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.altessa.badrequest.v1.BadRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.altessa.badrequest.v1.BadRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.altessa.badrequest.v1.BadRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.altessa.badrequest.v1.BadRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.altessa.badrequest.v1.BadRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.altessa.badrequest.v1.BadRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.altessa.badrequest.v1.BadRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.altessa.badrequest.v1.BadRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.altessa.badrequest.v1.BadRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.altessa.badrequest.v1.BadRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.altessa.badrequest.v1.BadRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.altessa.badrequest.v1.BadRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.altessa.badrequest.v1.BadRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Defines a general error structure for requests that are malformed or contain invalid data.
   * It typically includes a list of specific field violations that caused the request to be rejected.
   * This message is often used as a detail payload for `google.rpc.Status` when the error code is `INVALID_ARGUMENT`.
   * </pre>
   *
   * Protobuf type {@code io.altessa.badrequest.v1.BadRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.altessa.badrequest.v1.BadRequest)
      io.altessa.badrequest.v1.BadRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.altessa.badrequest.v1.Badrequest.internal_static_io_altessa_badrequest_v1_BadRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.altessa.badrequest.v1.Badrequest.internal_static_io_altessa_badrequest_v1_BadRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.altessa.badrequest.v1.BadRequest.class, io.altessa.badrequest.v1.BadRequest.Builder.class);
    }

    // Construct using io.altessa.badrequest.v1.BadRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (fieldViolationsBuilder_ == null) {
        fieldViolations_ = java.util.Collections.emptyList();
      } else {
        fieldViolations_ = null;
        fieldViolationsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.altessa.badrequest.v1.Badrequest.internal_static_io_altessa_badrequest_v1_BadRequest_descriptor;
    }

    @java.lang.Override
    public io.altessa.badrequest.v1.BadRequest getDefaultInstanceForType() {
      return io.altessa.badrequest.v1.BadRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.altessa.badrequest.v1.BadRequest build() {
      io.altessa.badrequest.v1.BadRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.altessa.badrequest.v1.BadRequest buildPartial() {
      io.altessa.badrequest.v1.BadRequest result = new io.altessa.badrequest.v1.BadRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.altessa.badrequest.v1.BadRequest result) {
      if (fieldViolationsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          fieldViolations_ = java.util.Collections.unmodifiableList(fieldViolations_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.fieldViolations_ = fieldViolations_;
      } else {
        result.fieldViolations_ = fieldViolationsBuilder_.build();
      }
    }

    private void buildPartial0(io.altessa.badrequest.v1.BadRequest result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.altessa.badrequest.v1.BadRequest) {
        return mergeFrom((io.altessa.badrequest.v1.BadRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.altessa.badrequest.v1.BadRequest other) {
      if (other == io.altessa.badrequest.v1.BadRequest.getDefaultInstance()) return this;
      if (fieldViolationsBuilder_ == null) {
        if (!other.fieldViolations_.isEmpty()) {
          if (fieldViolations_.isEmpty()) {
            fieldViolations_ = other.fieldViolations_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFieldViolationsIsMutable();
            fieldViolations_.addAll(other.fieldViolations_);
          }
          onChanged();
        }
      } else {
        if (!other.fieldViolations_.isEmpty()) {
          if (fieldViolationsBuilder_.isEmpty()) {
            fieldViolationsBuilder_.dispose();
            fieldViolationsBuilder_ = null;
            fieldViolations_ = other.fieldViolations_;
            bitField0_ = (bitField0_ & ~0x00000001);
            fieldViolationsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFieldViolationsFieldBuilder() : null;
          } else {
            fieldViolationsBuilder_.addAllMessages(other.fieldViolations_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              io.altessa.badrequest.v1.FieldViolation m =
                  input.readMessage(
                      io.altessa.badrequest.v1.FieldViolation.PARSER,
                      extensionRegistry);
              if (fieldViolationsBuilder_ == null) {
                ensureFieldViolationsIsMutable();
                fieldViolations_.add(m);
              } else {
                fieldViolationsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<io.altessa.badrequest.v1.FieldViolation> fieldViolations_ =
      java.util.Collections.emptyList();
    private void ensureFieldViolationsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        fieldViolations_ = new java.util.ArrayList<io.altessa.badrequest.v1.FieldViolation>(fieldViolations_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.altessa.badrequest.v1.FieldViolation, io.altessa.badrequest.v1.FieldViolation.Builder, io.altessa.badrequest.v1.FieldViolationOrBuilder> fieldViolationsBuilder_;

    /**
     * <pre>
     * A list of individual field violations that contributed to the bad request.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     */
    public java.util.List<io.altessa.badrequest.v1.FieldViolation> getFieldViolationsList() {
      if (fieldViolationsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(fieldViolations_);
      } else {
        return fieldViolationsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * A list of individual field violations that contributed to the bad request.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     */
    public int getFieldViolationsCount() {
      if (fieldViolationsBuilder_ == null) {
        return fieldViolations_.size();
      } else {
        return fieldViolationsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * A list of individual field violations that contributed to the bad request.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     */
    public io.altessa.badrequest.v1.FieldViolation getFieldViolations(int index) {
      if (fieldViolationsBuilder_ == null) {
        return fieldViolations_.get(index);
      } else {
        return fieldViolationsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * A list of individual field violations that contributed to the bad request.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     */
    public Builder setFieldViolations(
        int index, io.altessa.badrequest.v1.FieldViolation value) {
      if (fieldViolationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFieldViolationsIsMutable();
        fieldViolations_.set(index, value);
        onChanged();
      } else {
        fieldViolationsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of individual field violations that contributed to the bad request.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     */
    public Builder setFieldViolations(
        int index, io.altessa.badrequest.v1.FieldViolation.Builder builderForValue) {
      if (fieldViolationsBuilder_ == null) {
        ensureFieldViolationsIsMutable();
        fieldViolations_.set(index, builderForValue.build());
        onChanged();
      } else {
        fieldViolationsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of individual field violations that contributed to the bad request.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     */
    public Builder addFieldViolations(io.altessa.badrequest.v1.FieldViolation value) {
      if (fieldViolationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFieldViolationsIsMutable();
        fieldViolations_.add(value);
        onChanged();
      } else {
        fieldViolationsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of individual field violations that contributed to the bad request.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     */
    public Builder addFieldViolations(
        int index, io.altessa.badrequest.v1.FieldViolation value) {
      if (fieldViolationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFieldViolationsIsMutable();
        fieldViolations_.add(index, value);
        onChanged();
      } else {
        fieldViolationsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of individual field violations that contributed to the bad request.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     */
    public Builder addFieldViolations(
        io.altessa.badrequest.v1.FieldViolation.Builder builderForValue) {
      if (fieldViolationsBuilder_ == null) {
        ensureFieldViolationsIsMutable();
        fieldViolations_.add(builderForValue.build());
        onChanged();
      } else {
        fieldViolationsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of individual field violations that contributed to the bad request.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     */
    public Builder addFieldViolations(
        int index, io.altessa.badrequest.v1.FieldViolation.Builder builderForValue) {
      if (fieldViolationsBuilder_ == null) {
        ensureFieldViolationsIsMutable();
        fieldViolations_.add(index, builderForValue.build());
        onChanged();
      } else {
        fieldViolationsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of individual field violations that contributed to the bad request.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     */
    public Builder addAllFieldViolations(
        java.lang.Iterable<? extends io.altessa.badrequest.v1.FieldViolation> values) {
      if (fieldViolationsBuilder_ == null) {
        ensureFieldViolationsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fieldViolations_);
        onChanged();
      } else {
        fieldViolationsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * A list of individual field violations that contributed to the bad request.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     */
    public Builder clearFieldViolations() {
      if (fieldViolationsBuilder_ == null) {
        fieldViolations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        fieldViolationsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * A list of individual field violations that contributed to the bad request.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     */
    public Builder removeFieldViolations(int index) {
      if (fieldViolationsBuilder_ == null) {
        ensureFieldViolationsIsMutable();
        fieldViolations_.remove(index);
        onChanged();
      } else {
        fieldViolationsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * A list of individual field violations that contributed to the bad request.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     */
    public io.altessa.badrequest.v1.FieldViolation.Builder getFieldViolationsBuilder(
        int index) {
      return getFieldViolationsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * A list of individual field violations that contributed to the bad request.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     */
    public io.altessa.badrequest.v1.FieldViolationOrBuilder getFieldViolationsOrBuilder(
        int index) {
      if (fieldViolationsBuilder_ == null) {
        return fieldViolations_.get(index);  } else {
        return fieldViolationsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * A list of individual field violations that contributed to the bad request.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     */
    public java.util.List<? extends io.altessa.badrequest.v1.FieldViolationOrBuilder> 
         getFieldViolationsOrBuilderList() {
      if (fieldViolationsBuilder_ != null) {
        return fieldViolationsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(fieldViolations_);
      }
    }
    /**
     * <pre>
     * A list of individual field violations that contributed to the bad request.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     */
    public io.altessa.badrequest.v1.FieldViolation.Builder addFieldViolationsBuilder() {
      return getFieldViolationsFieldBuilder().addBuilder(
          io.altessa.badrequest.v1.FieldViolation.getDefaultInstance());
    }
    /**
     * <pre>
     * A list of individual field violations that contributed to the bad request.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     */
    public io.altessa.badrequest.v1.FieldViolation.Builder addFieldViolationsBuilder(
        int index) {
      return getFieldViolationsFieldBuilder().addBuilder(
          index, io.altessa.badrequest.v1.FieldViolation.getDefaultInstance());
    }
    /**
     * <pre>
     * A list of individual field violations that contributed to the bad request.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     */
    public java.util.List<io.altessa.badrequest.v1.FieldViolation.Builder> 
         getFieldViolationsBuilderList() {
      return getFieldViolationsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.altessa.badrequest.v1.FieldViolation, io.altessa.badrequest.v1.FieldViolation.Builder, io.altessa.badrequest.v1.FieldViolationOrBuilder> 
        getFieldViolationsFieldBuilder() {
      if (fieldViolationsBuilder_ == null) {
        fieldViolationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.altessa.badrequest.v1.FieldViolation, io.altessa.badrequest.v1.FieldViolation.Builder, io.altessa.badrequest.v1.FieldViolationOrBuilder>(
                fieldViolations_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        fieldViolations_ = null;
      }
      return fieldViolationsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.altessa.badrequest.v1.BadRequest)
  }

  // @@protoc_insertion_point(class_scope:io.altessa.badrequest.v1.BadRequest)
  private static final io.altessa.badrequest.v1.BadRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.altessa.badrequest.v1.BadRequest();
  }

  public static io.altessa.badrequest.v1.BadRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<BadRequest>
      PARSER = new com.google.protobuf.AbstractParser<BadRequest>() {
    @java.lang.Override
    public BadRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BadRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BadRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.altessa.badrequest.v1.BadRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

