// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/altessa/badrequest/v1/badrequest.proto

package io.altessa.badrequest.v1;

/**
 * <pre>
 * Defines a single segment in the path to a violated field.
 * It provides details about the field name, number, type, and, if applicable, its index in a repeated field or its key in a map.
 * </pre>
 *
 * Protobuf type {@code io.altessa.badrequest.v1.FieldPathComponent}
 */
public final class FieldPathComponent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.altessa.badrequest.v1.FieldPathComponent)
    FieldPathComponentOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FieldPathComponent.newBuilder() to construct.
  private FieldPathComponent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FieldPathComponent() {
    name_ = "";
    type_ = 0;
    mapKeyType_ = 0;
    mapValueType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FieldPathComponent();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.altessa.badrequest.v1.BadRequestProto.internal_static_io_altessa_badrequest_v1_FieldPathComponent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.altessa.badrequest.v1.BadRequestProto.internal_static_io_altessa_badrequest_v1_FieldPathComponent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.altessa.badrequest.v1.FieldPathComponent.class, io.altessa.badrequest.v1.FieldPathComponent.Builder.class);
  }

  private int bitField0_;
  private int mapKeyCase_ = 0;
  private java.lang.Object mapKey_;
  public enum MapKeyCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    INDEX(8),
    BOOL_KEY(9),
    INT_KEY(10),
    UINT_KEY(11),
    STRING_KEY(12),
    MAPKEY_NOT_SET(0);
    private final int value;
    private MapKeyCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MapKeyCase valueOf(int value) {
      return forNumber(value);
    }

    public static MapKeyCase forNumber(int value) {
      switch (value) {
        case 8: return INDEX;
        case 9: return BOOL_KEY;
        case 10: return INT_KEY;
        case 11: return UINT_KEY;
        case 12: return STRING_KEY;
        case 0: return MAPKEY_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public MapKeyCase
  getMapKeyCase() {
    return MapKeyCase.forNumber(
        mapKeyCase_);
  }

  public static final int NUMBER_FIELD_NUMBER = 1;
  private int number_ = 0;
  /**
   * <pre>
   * Field number as defined in the .proto file.
   * </pre>
   *
   * <code>optional int32 number = 1 [json_name = "number", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return Whether the number field is set.
   */
  @java.lang.Override
  public boolean hasNumber() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Field number as defined in the .proto file.
   * </pre>
   *
   * <code>optional int32 number = 1 [json_name = "number", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return The number.
   */
  @java.lang.Override
  public int getNumber() {
    return number_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <pre>
   * Name of the field as defined in the .proto file.
   * </pre>
   *
   * <code>optional string name = 2 [json_name = "name", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Name of the field as defined in the .proto file.
   * </pre>
   *
   * <code>optional string name = 2 [json_name = "name", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Name of the field as defined in the .proto file.
   * </pre>
   *
   * <code>optional string name = 2 [json_name = "name", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 3;
  private int type_ = 0;
  /**
   * <pre>
   * Data type of the field.
   * </pre>
   *
   * <code>optional .io.altessa.badrequest.v1.FieldType type = 3 [json_name = "type", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return Whether the type field is set.
   */
  @java.lang.Override public boolean hasType() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * Data type of the field.
   * </pre>
   *
   * <code>optional .io.altessa.badrequest.v1.FieldType type = 3 [json_name = "type", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <pre>
   * Data type of the field.
   * </pre>
   *
   * <code>optional .io.altessa.badrequest.v1.FieldType type = 3 [json_name = "type", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return The type.
   */
  @java.lang.Override public io.altessa.badrequest.v1.FieldType getType() {
    io.altessa.badrequest.v1.FieldType result = io.altessa.badrequest.v1.FieldType.forNumber(type_);
    return result == null ? io.altessa.badrequest.v1.FieldType.UNRECOGNIZED : result;
  }

  public static final int MAP_KEY_TYPE_FIELD_NUMBER = 4;
  private int mapKeyType_ = 0;
  /**
   * <pre>
   * For map fields, specifies the data type of the map keys.
   * </pre>
   *
   * <code>optional .io.altessa.badrequest.v1.FieldType map_key_type = 4 [json_name = "mapKeyType", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return Whether the mapKeyType field is set.
   */
  @java.lang.Override public boolean hasMapKeyType() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * For map fields, specifies the data type of the map keys.
   * </pre>
   *
   * <code>optional .io.altessa.badrequest.v1.FieldType map_key_type = 4 [json_name = "mapKeyType", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return The enum numeric value on the wire for mapKeyType.
   */
  @java.lang.Override public int getMapKeyTypeValue() {
    return mapKeyType_;
  }
  /**
   * <pre>
   * For map fields, specifies the data type of the map keys.
   * </pre>
   *
   * <code>optional .io.altessa.badrequest.v1.FieldType map_key_type = 4 [json_name = "mapKeyType", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return The mapKeyType.
   */
  @java.lang.Override public io.altessa.badrequest.v1.FieldType getMapKeyType() {
    io.altessa.badrequest.v1.FieldType result = io.altessa.badrequest.v1.FieldType.forNumber(mapKeyType_);
    return result == null ? io.altessa.badrequest.v1.FieldType.UNRECOGNIZED : result;
  }

  public static final int MAP_VALUE_TYPE_FIELD_NUMBER = 5;
  private int mapValueType_ = 0;
  /**
   * <pre>
   * For map fields, specifies the data type of the map values.
   * </pre>
   *
   * <code>optional .io.altessa.badrequest.v1.FieldType map_value_type = 5 [json_name = "mapValueType", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return Whether the mapValueType field is set.
   */
  @java.lang.Override public boolean hasMapValueType() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <pre>
   * For map fields, specifies the data type of the map values.
   * </pre>
   *
   * <code>optional .io.altessa.badrequest.v1.FieldType map_value_type = 5 [json_name = "mapValueType", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return The enum numeric value on the wire for mapValueType.
   */
  @java.lang.Override public int getMapValueTypeValue() {
    return mapValueType_;
  }
  /**
   * <pre>
   * For map fields, specifies the data type of the map values.
   * </pre>
   *
   * <code>optional .io.altessa.badrequest.v1.FieldType map_value_type = 5 [json_name = "mapValueType", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return The mapValueType.
   */
  @java.lang.Override public io.altessa.badrequest.v1.FieldType getMapValueType() {
    io.altessa.badrequest.v1.FieldType result = io.altessa.badrequest.v1.FieldType.forNumber(mapValueType_);
    return result == null ? io.altessa.badrequest.v1.FieldType.UNRECOGNIZED : result;
  }

  public static final int REPEATED_FIELD_FIELD_NUMBER = 6;
  private boolean repeatedField_ = false;
  /**
   * <pre>
   * Indicates whether the field is a repeated field (i.e., an array or list).
   * AIP-140: boolean fields omit the `is_` prefix; `repeated` is a proto
   * keyword, so this reads as `repeated_field`.
   * </pre>
   *
   * <code>optional bool repeated_field = 6 [json_name = "repeatedField", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return Whether the repeatedField field is set.
   */
  @java.lang.Override
  public boolean hasRepeatedField() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <pre>
   * Indicates whether the field is a repeated field (i.e., an array or list).
   * AIP-140: boolean fields omit the `is_` prefix; `repeated` is a proto
   * keyword, so this reads as `repeated_field`.
   * </pre>
   *
   * <code>optional bool repeated_field = 6 [json_name = "repeatedField", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return The repeatedField.
   */
  @java.lang.Override
  public boolean getRepeatedField() {
    return repeatedField_;
  }

  public static final int REPEATED_INDEX_FIELD_NUMBER = 7;
  private long repeatedIndex_ = 0L;
  /**
   * <pre>
   * For repeated fields, the 0-based index of the element that caused the violation.
   * </pre>
   *
   * <code>optional uint64 repeated_index = 7 [json_name = "repeatedIndex", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return Whether the repeatedIndex field is set.
   */
  @java.lang.Override
  public boolean hasRepeatedIndex() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <pre>
   * For repeated fields, the 0-based index of the element that caused the violation.
   * </pre>
   *
   * <code>optional uint64 repeated_index = 7 [json_name = "repeatedIndex", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return The repeatedIndex.
   */
  @java.lang.Override
  public long getRepeatedIndex() {
    return repeatedIndex_;
  }

  public static final int INDEX_FIELD_NUMBER = 8;
  /**
   * <pre>
   * The index if the map key is treated as an array index (less common for proto maps).
   * </pre>
   *
   * <code>uint64 index = 8 [json_name = "index"];</code>
   * @return Whether the index field is set.
   */
  @java.lang.Override
  public boolean hasIndex() {
    return mapKeyCase_ == 8;
  }
  /**
   * <pre>
   * The index if the map key is treated as an array index (less common for proto maps).
   * </pre>
   *
   * <code>uint64 index = 8 [json_name = "index"];</code>
   * @return The index.
   */
  @java.lang.Override
  public long getIndex() {
    if (mapKeyCase_ == 8) {
      return (java.lang.Long) mapKey_;
    }
    return 0L;
  }

  public static final int BOOL_KEY_FIELD_NUMBER = 9;
  /**
   * <pre>
   * The map key, if its type is `bool`.
   * </pre>
   *
   * <code>bool bool_key = 9 [json_name = "boolKey"];</code>
   * @return Whether the boolKey field is set.
   */
  @java.lang.Override
  public boolean hasBoolKey() {
    return mapKeyCase_ == 9;
  }
  /**
   * <pre>
   * The map key, if its type is `bool`.
   * </pre>
   *
   * <code>bool bool_key = 9 [json_name = "boolKey"];</code>
   * @return The boolKey.
   */
  @java.lang.Override
  public boolean getBoolKey() {
    if (mapKeyCase_ == 9) {
      return (java.lang.Boolean) mapKey_;
    }
    return false;
  }

  public static final int INT_KEY_FIELD_NUMBER = 10;
  /**
   * <pre>
   * The map key, if its type is `int32`, `int64`, `sint32`, `sint64`, `sfixed32`, or `sfixed64`.
   * </pre>
   *
   * <code>int64 int_key = 10 [json_name = "intKey"];</code>
   * @return Whether the intKey field is set.
   */
  @java.lang.Override
  public boolean hasIntKey() {
    return mapKeyCase_ == 10;
  }
  /**
   * <pre>
   * The map key, if its type is `int32`, `int64`, `sint32`, `sint64`, `sfixed32`, or `sfixed64`.
   * </pre>
   *
   * <code>int64 int_key = 10 [json_name = "intKey"];</code>
   * @return The intKey.
   */
  @java.lang.Override
  public long getIntKey() {
    if (mapKeyCase_ == 10) {
      return (java.lang.Long) mapKey_;
    }
    return 0L;
  }

  public static final int UINT_KEY_FIELD_NUMBER = 11;
  /**
   * <pre>
   * The map key, if its type is `uint32`, `uint64`, `fixed32`, or `fixed64`.
   * </pre>
   *
   * <code>uint64 uint_key = 11 [json_name = "uintKey"];</code>
   * @return Whether the uintKey field is set.
   */
  @java.lang.Override
  public boolean hasUintKey() {
    return mapKeyCase_ == 11;
  }
  /**
   * <pre>
   * The map key, if its type is `uint32`, `uint64`, `fixed32`, or `fixed64`.
   * </pre>
   *
   * <code>uint64 uint_key = 11 [json_name = "uintKey"];</code>
   * @return The uintKey.
   */
  @java.lang.Override
  public long getUintKey() {
    if (mapKeyCase_ == 11) {
      return (java.lang.Long) mapKey_;
    }
    return 0L;
  }

  public static final int STRING_KEY_FIELD_NUMBER = 12;
  /**
   * <pre>
   * The map key, if its type is `string`.
   * </pre>
   *
   * <code>string string_key = 12 [json_name = "stringKey"];</code>
   * @return Whether the stringKey field is set.
   */
  public boolean hasStringKey() {
    return mapKeyCase_ == 12;
  }
  /**
   * <pre>
   * The map key, if its type is `string`.
   * </pre>
   *
   * <code>string string_key = 12 [json_name = "stringKey"];</code>
   * @return The stringKey.
   */
  public java.lang.String getStringKey() {
    java.lang.Object ref = "";
    if (mapKeyCase_ == 12) {
      ref = mapKey_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (mapKeyCase_ == 12) {
        mapKey_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * The map key, if its type is `string`.
   * </pre>
   *
   * <code>string string_key = 12 [json_name = "stringKey"];</code>
   * @return The bytes for stringKey.
   */
  public com.google.protobuf.ByteString
      getStringKeyBytes() {
    java.lang.Object ref = "";
    if (mapKeyCase_ == 12) {
      ref = mapKey_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (mapKeyCase_ == 12) {
        mapKey_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(1, number_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeEnum(3, type_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeEnum(4, mapKeyType_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeEnum(5, mapValueType_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeBool(6, repeatedField_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeUInt64(7, repeatedIndex_);
    }
    if (mapKeyCase_ == 8) {
      output.writeUInt64(
          8, (long)((java.lang.Long) mapKey_));
    }
    if (mapKeyCase_ == 9) {
      output.writeBool(
          9, (boolean)((java.lang.Boolean) mapKey_));
    }
    if (mapKeyCase_ == 10) {
      output.writeInt64(
          10, (long)((java.lang.Long) mapKey_));
    }
    if (mapKeyCase_ == 11) {
      output.writeUInt64(
          11, (long)((java.lang.Long) mapKey_));
    }
    if (mapKeyCase_ == 12) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, mapKey_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, number_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, type_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, mapKeyType_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, mapValueType_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, repeatedField_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(7, repeatedIndex_);
    }
    if (mapKeyCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(
            8, (long)((java.lang.Long) mapKey_));
    }
    if (mapKeyCase_ == 9) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(
            9, (boolean)((java.lang.Boolean) mapKey_));
    }
    if (mapKeyCase_ == 10) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(
            10, (long)((java.lang.Long) mapKey_));
    }
    if (mapKeyCase_ == 11) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(
            11, (long)((java.lang.Long) mapKey_));
    }
    if (mapKeyCase_ == 12) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, mapKey_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.altessa.badrequest.v1.FieldPathComponent)) {
      return super.equals(obj);
    }
    io.altessa.badrequest.v1.FieldPathComponent other = (io.altessa.badrequest.v1.FieldPathComponent) obj;

    if (hasNumber() != other.hasNumber()) return false;
    if (hasNumber()) {
      if (getNumber()
          != other.getNumber()) return false;
    }
    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (hasType() != other.hasType()) return false;
    if (hasType()) {
      if (type_ != other.type_) return false;
    }
    if (hasMapKeyType() != other.hasMapKeyType()) return false;
    if (hasMapKeyType()) {
      if (mapKeyType_ != other.mapKeyType_) return false;
    }
    if (hasMapValueType() != other.hasMapValueType()) return false;
    if (hasMapValueType()) {
      if (mapValueType_ != other.mapValueType_) return false;
    }
    if (hasRepeatedField() != other.hasRepeatedField()) return false;
    if (hasRepeatedField()) {
      if (getRepeatedField()
          != other.getRepeatedField()) return false;
    }
    if (hasRepeatedIndex() != other.hasRepeatedIndex()) return false;
    if (hasRepeatedIndex()) {
      if (getRepeatedIndex()
          != other.getRepeatedIndex()) return false;
    }
    if (!getMapKeyCase().equals(other.getMapKeyCase())) return false;
    switch (mapKeyCase_) {
      case 8:
        if (getIndex()
            != other.getIndex()) return false;
        break;
      case 9:
        if (getBoolKey()
            != other.getBoolKey()) return false;
        break;
      case 10:
        if (getIntKey()
            != other.getIntKey()) return false;
        break;
      case 11:
        if (getUintKey()
            != other.getUintKey()) return false;
        break;
      case 12:
        if (!getStringKey()
            .equals(other.getStringKey())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasNumber()) {
      hash = (37 * hash) + NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getNumber();
    }
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasType()) {
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
    }
    if (hasMapKeyType()) {
      hash = (37 * hash) + MAP_KEY_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + mapKeyType_;
    }
    if (hasMapValueType()) {
      hash = (37 * hash) + MAP_VALUE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + mapValueType_;
    }
    if (hasRepeatedField()) {
      hash = (37 * hash) + REPEATED_FIELD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getRepeatedField());
    }
    if (hasRepeatedIndex()) {
      hash = (37 * hash) + REPEATED_INDEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRepeatedIndex());
    }
    switch (mapKeyCase_) {
      case 8:
        hash = (37 * hash) + INDEX_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getIndex());
        break;
      case 9:
        hash = (37 * hash) + BOOL_KEY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getBoolKey());
        break;
      case 10:
        hash = (37 * hash) + INT_KEY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getIntKey());
        break;
      case 11:
        hash = (37 * hash) + UINT_KEY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getUintKey());
        break;
      case 12:
        hash = (37 * hash) + STRING_KEY_FIELD_NUMBER;
        hash = (53 * hash) + getStringKey().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.altessa.badrequest.v1.FieldPathComponent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.altessa.badrequest.v1.FieldPathComponent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.altessa.badrequest.v1.FieldPathComponent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.altessa.badrequest.v1.FieldPathComponent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.altessa.badrequest.v1.FieldPathComponent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.altessa.badrequest.v1.FieldPathComponent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.altessa.badrequest.v1.FieldPathComponent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.altessa.badrequest.v1.FieldPathComponent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.altessa.badrequest.v1.FieldPathComponent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.altessa.badrequest.v1.FieldPathComponent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.altessa.badrequest.v1.FieldPathComponent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.altessa.badrequest.v1.FieldPathComponent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.altessa.badrequest.v1.FieldPathComponent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Defines a single segment in the path to a violated field.
   * It provides details about the field name, number, type, and, if applicable, its index in a repeated field or its key in a map.
   * </pre>
   *
   * Protobuf type {@code io.altessa.badrequest.v1.FieldPathComponent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.altessa.badrequest.v1.FieldPathComponent)
      io.altessa.badrequest.v1.FieldPathComponentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.altessa.badrequest.v1.BadRequestProto.internal_static_io_altessa_badrequest_v1_FieldPathComponent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.altessa.badrequest.v1.BadRequestProto.internal_static_io_altessa_badrequest_v1_FieldPathComponent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.altessa.badrequest.v1.FieldPathComponent.class, io.altessa.badrequest.v1.FieldPathComponent.Builder.class);
    }

    // Construct using io.altessa.badrequest.v1.FieldPathComponent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      number_ = 0;
      name_ = "";
      type_ = 0;
      mapKeyType_ = 0;
      mapValueType_ = 0;
      repeatedField_ = false;
      repeatedIndex_ = 0L;
      mapKeyCase_ = 0;
      mapKey_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.altessa.badrequest.v1.BadRequestProto.internal_static_io_altessa_badrequest_v1_FieldPathComponent_descriptor;
    }

    @java.lang.Override
    public io.altessa.badrequest.v1.FieldPathComponent getDefaultInstanceForType() {
      return io.altessa.badrequest.v1.FieldPathComponent.getDefaultInstance();
    }

    @java.lang.Override
    public io.altessa.badrequest.v1.FieldPathComponent build() {
      io.altessa.badrequest.v1.FieldPathComponent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.altessa.badrequest.v1.FieldPathComponent buildPartial() {
      io.altessa.badrequest.v1.FieldPathComponent result = new io.altessa.badrequest.v1.FieldPathComponent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(io.altessa.badrequest.v1.FieldPathComponent result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.number_ = number_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.type_ = type_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.mapKeyType_ = mapKeyType_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.mapValueType_ = mapValueType_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.repeatedField_ = repeatedField_;
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.repeatedIndex_ = repeatedIndex_;
        to_bitField0_ |= 0x00000040;
      }
      result.bitField0_ |= to_bitField0_;
    }

    private void buildPartialOneofs(io.altessa.badrequest.v1.FieldPathComponent result) {
      result.mapKeyCase_ = mapKeyCase_;
      result.mapKey_ = this.mapKey_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.altessa.badrequest.v1.FieldPathComponent) {
        return mergeFrom((io.altessa.badrequest.v1.FieldPathComponent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.altessa.badrequest.v1.FieldPathComponent other) {
      if (other == io.altessa.badrequest.v1.FieldPathComponent.getDefaultInstance()) return this;
      if (other.hasNumber()) {
        setNumber(other.getNumber());
      }
      if (other.hasName()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasType()) {
        setType(other.getType());
      }
      if (other.hasMapKeyType()) {
        setMapKeyType(other.getMapKeyType());
      }
      if (other.hasMapValueType()) {
        setMapValueType(other.getMapValueType());
      }
      if (other.hasRepeatedField()) {
        setRepeatedField(other.getRepeatedField());
      }
      if (other.hasRepeatedIndex()) {
        setRepeatedIndex(other.getRepeatedIndex());
      }
      switch (other.getMapKeyCase()) {
        case INDEX: {
          setIndex(other.getIndex());
          break;
        }
        case BOOL_KEY: {
          setBoolKey(other.getBoolKey());
          break;
        }
        case INT_KEY: {
          setIntKey(other.getIntKey());
          break;
        }
        case UINT_KEY: {
          setUintKey(other.getUintKey());
          break;
        }
        case STRING_KEY: {
          mapKeyCase_ = 12;
          mapKey_ = other.mapKey_;
          onChanged();
          break;
        }
        case MAPKEY_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              number_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              mapKeyType_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              mapValueType_ = input.readEnum();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              repeatedField_ = input.readBool();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              repeatedIndex_ = input.readUInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              mapKey_ = input.readUInt64();
              mapKeyCase_ = 8;
              break;
            } // case 64
            case 72: {
              mapKey_ = input.readBool();
              mapKeyCase_ = 9;
              break;
            } // case 72
            case 80: {
              mapKey_ = input.readInt64();
              mapKeyCase_ = 10;
              break;
            } // case 80
            case 88: {
              mapKey_ = input.readUInt64();
              mapKeyCase_ = 11;
              break;
            } // case 88
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();
              mapKeyCase_ = 12;
              mapKey_ = s;
              break;
            } // case 98
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int mapKeyCase_ = 0;
    private java.lang.Object mapKey_;
    public MapKeyCase
        getMapKeyCase() {
      return MapKeyCase.forNumber(
          mapKeyCase_);
    }

    public Builder clearMapKey() {
      mapKeyCase_ = 0;
      mapKey_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private int number_ ;
    /**
     * <pre>
     * Field number as defined in the .proto file.
     * </pre>
     *
     * <code>optional int32 number = 1 [json_name = "number", (.google.api.field_behavior) = OPTIONAL];</code>
     * @return Whether the number field is set.
     */
    @java.lang.Override
    public boolean hasNumber() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Field number as defined in the .proto file.
     * </pre>
     *
     * <code>optional int32 number = 1 [json_name = "number", (.google.api.field_behavior) = OPTIONAL];</code>
     * @return The number.
     */
    @java.lang.Override
    public int getNumber() {
      return number_;
    }
    /**
     * <pre>
     * Field number as defined in the .proto file.
     * </pre>
     *
     * <code>optional int32 number = 1 [json_name = "number", (.google.api.field_behavior) = OPTIONAL];</code>
     * @param value The number to set.
     * @return This builder for chaining.
     */
    public Builder setNumber(int value) {
      
      number_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Field number as defined in the .proto file.
     * </pre>
     *
     * <code>optional int32 number = 1 [json_name = "number", (.google.api.field_behavior) = OPTIONAL];</code>
     * @return This builder for chaining.
     */
    public Builder clearNumber() {
      bitField0_ = (bitField0_ & ~0x00000001);
      number_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * Name of the field as defined in the .proto file.
     * </pre>
     *
     * <code>optional string name = 2 [json_name = "name", (.google.api.field_behavior) = OPTIONAL];</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Name of the field as defined in the .proto file.
     * </pre>
     *
     * <code>optional string name = 2 [json_name = "name", (.google.api.field_behavior) = OPTIONAL];</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Name of the field as defined in the .proto file.
     * </pre>
     *
     * <code>optional string name = 2 [json_name = "name", (.google.api.field_behavior) = OPTIONAL];</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Name of the field as defined in the .proto file.
     * </pre>
     *
     * <code>optional string name = 2 [json_name = "name", (.google.api.field_behavior) = OPTIONAL];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the field as defined in the .proto file.
     * </pre>
     *
     * <code>optional string name = 2 [json_name = "name", (.google.api.field_behavior) = OPTIONAL];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the field as defined in the .proto file.
     * </pre>
     *
     * <code>optional string name = 2 [json_name = "name", (.google.api.field_behavior) = OPTIONAL];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <pre>
     * Data type of the field.
     * </pre>
     *
     * <code>optional .io.altessa.badrequest.v1.FieldType type = 3 [json_name = "type", (.google.api.field_behavior) = OPTIONAL];</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override public boolean hasType() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Data type of the field.
     * </pre>
     *
     * <code>optional .io.altessa.badrequest.v1.FieldType type = 3 [json_name = "type", (.google.api.field_behavior) = OPTIONAL];</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * Data type of the field.
     * </pre>
     *
     * <code>optional .io.altessa.badrequest.v1.FieldType type = 3 [json_name = "type", (.google.api.field_behavior) = OPTIONAL];</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Data type of the field.
     * </pre>
     *
     * <code>optional .io.altessa.badrequest.v1.FieldType type = 3 [json_name = "type", (.google.api.field_behavior) = OPTIONAL];</code>
     * @return The type.
     */
    @java.lang.Override
    public io.altessa.badrequest.v1.FieldType getType() {
      io.altessa.badrequest.v1.FieldType result = io.altessa.badrequest.v1.FieldType.forNumber(type_);
      return result == null ? io.altessa.badrequest.v1.FieldType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Data type of the field.
     * </pre>
     *
     * <code>optional .io.altessa.badrequest.v1.FieldType type = 3 [json_name = "type", (.google.api.field_behavior) = OPTIONAL];</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(io.altessa.badrequest.v1.FieldType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Data type of the field.
     * </pre>
     *
     * <code>optional .io.altessa.badrequest.v1.FieldType type = 3 [json_name = "type", (.google.api.field_behavior) = OPTIONAL];</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000004);
      type_ = 0;
      onChanged();
      return this;
    }

    private int mapKeyType_ = 0;
    /**
     * <pre>
     * For map fields, specifies the data type of the map keys.
     * </pre>
     *
     * <code>optional .io.altessa.badrequest.v1.FieldType map_key_type = 4 [json_name = "mapKeyType", (.google.api.field_behavior) = OPTIONAL];</code>
     * @return Whether the mapKeyType field is set.
     */
    @java.lang.Override public boolean hasMapKeyType() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * For map fields, specifies the data type of the map keys.
     * </pre>
     *
     * <code>optional .io.altessa.badrequest.v1.FieldType map_key_type = 4 [json_name = "mapKeyType", (.google.api.field_behavior) = OPTIONAL];</code>
     * @return The enum numeric value on the wire for mapKeyType.
     */
    @java.lang.Override public int getMapKeyTypeValue() {
      return mapKeyType_;
    }
    /**
     * <pre>
     * For map fields, specifies the data type of the map keys.
     * </pre>
     *
     * <code>optional .io.altessa.badrequest.v1.FieldType map_key_type = 4 [json_name = "mapKeyType", (.google.api.field_behavior) = OPTIONAL];</code>
     * @param value The enum numeric value on the wire for mapKeyType to set.
     * @return This builder for chaining.
     */
    public Builder setMapKeyTypeValue(int value) {
      mapKeyType_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * For map fields, specifies the data type of the map keys.
     * </pre>
     *
     * <code>optional .io.altessa.badrequest.v1.FieldType map_key_type = 4 [json_name = "mapKeyType", (.google.api.field_behavior) = OPTIONAL];</code>
     * @return The mapKeyType.
     */
    @java.lang.Override
    public io.altessa.badrequest.v1.FieldType getMapKeyType() {
      io.altessa.badrequest.v1.FieldType result = io.altessa.badrequest.v1.FieldType.forNumber(mapKeyType_);
      return result == null ? io.altessa.badrequest.v1.FieldType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * For map fields, specifies the data type of the map keys.
     * </pre>
     *
     * <code>optional .io.altessa.badrequest.v1.FieldType map_key_type = 4 [json_name = "mapKeyType", (.google.api.field_behavior) = OPTIONAL];</code>
     * @param value The mapKeyType to set.
     * @return This builder for chaining.
     */
    public Builder setMapKeyType(io.altessa.badrequest.v1.FieldType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      mapKeyType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * For map fields, specifies the data type of the map keys.
     * </pre>
     *
     * <code>optional .io.altessa.badrequest.v1.FieldType map_key_type = 4 [json_name = "mapKeyType", (.google.api.field_behavior) = OPTIONAL];</code>
     * @return This builder for chaining.
     */
    public Builder clearMapKeyType() {
      bitField0_ = (bitField0_ & ~0x00000008);
      mapKeyType_ = 0;
      onChanged();
      return this;
    }

    private int mapValueType_ = 0;
    /**
     * <pre>
     * For map fields, specifies the data type of the map values.
     * </pre>
     *
     * <code>optional .io.altessa.badrequest.v1.FieldType map_value_type = 5 [json_name = "mapValueType", (.google.api.field_behavior) = OPTIONAL];</code>
     * @return Whether the mapValueType field is set.
     */
    @java.lang.Override public boolean hasMapValueType() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * For map fields, specifies the data type of the map values.
     * </pre>
     *
     * <code>optional .io.altessa.badrequest.v1.FieldType map_value_type = 5 [json_name = "mapValueType", (.google.api.field_behavior) = OPTIONAL];</code>
     * @return The enum numeric value on the wire for mapValueType.
     */
    @java.lang.Override public int getMapValueTypeValue() {
      return mapValueType_;
    }
    /**
     * <pre>
     * For map fields, specifies the data type of the map values.
     * </pre>
     *
     * <code>optional .io.altessa.badrequest.v1.FieldType map_value_type = 5 [json_name = "mapValueType", (.google.api.field_behavior) = OPTIONAL];</code>
     * @param value The enum numeric value on the wire for mapValueType to set.
     * @return This builder for chaining.
     */
    public Builder setMapValueTypeValue(int value) {
      mapValueType_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * For map fields, specifies the data type of the map values.
     * </pre>
     *
     * <code>optional .io.altessa.badrequest.v1.FieldType map_value_type = 5 [json_name = "mapValueType", (.google.api.field_behavior) = OPTIONAL];</code>
     * @return The mapValueType.
     */
    @java.lang.Override
    public io.altessa.badrequest.v1.FieldType getMapValueType() {
      io.altessa.badrequest.v1.FieldType result = io.altessa.badrequest.v1.FieldType.forNumber(mapValueType_);
      return result == null ? io.altessa.badrequest.v1.FieldType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * For map fields, specifies the data type of the map values.
     * </pre>
     *
     * <code>optional .io.altessa.badrequest.v1.FieldType map_value_type = 5 [json_name = "mapValueType", (.google.api.field_behavior) = OPTIONAL];</code>
     * @param value The mapValueType to set.
     * @return This builder for chaining.
     */
    public Builder setMapValueType(io.altessa.badrequest.v1.FieldType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      mapValueType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * For map fields, specifies the data type of the map values.
     * </pre>
     *
     * <code>optional .io.altessa.badrequest.v1.FieldType map_value_type = 5 [json_name = "mapValueType", (.google.api.field_behavior) = OPTIONAL];</code>
     * @return This builder for chaining.
     */
    public Builder clearMapValueType() {
      bitField0_ = (bitField0_ & ~0x00000010);
      mapValueType_ = 0;
      onChanged();
      return this;
    }

    private boolean repeatedField_ ;
    /**
     * <pre>
     * Indicates whether the field is a repeated field (i.e., an array or list).
     * AIP-140: boolean fields omit the `is_` prefix; `repeated` is a proto
     * keyword, so this reads as `repeated_field`.
     * </pre>
     *
     * <code>optional bool repeated_field = 6 [json_name = "repeatedField", (.google.api.field_behavior) = OPTIONAL];</code>
     * @return Whether the repeatedField field is set.
     */
    @java.lang.Override
    public boolean hasRepeatedField() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * Indicates whether the field is a repeated field (i.e., an array or list).
     * AIP-140: boolean fields omit the `is_` prefix; `repeated` is a proto
     * keyword, so this reads as `repeated_field`.
     * </pre>
     *
     * <code>optional bool repeated_field = 6 [json_name = "repeatedField", (.google.api.field_behavior) = OPTIONAL];</code>
     * @return The repeatedField.
     */
    @java.lang.Override
    public boolean getRepeatedField() {
      return repeatedField_;
    }
    /**
     * <pre>
     * Indicates whether the field is a repeated field (i.e., an array or list).
     * AIP-140: boolean fields omit the `is_` prefix; `repeated` is a proto
     * keyword, so this reads as `repeated_field`.
     * </pre>
     *
     * <code>optional bool repeated_field = 6 [json_name = "repeatedField", (.google.api.field_behavior) = OPTIONAL];</code>
     * @param value The repeatedField to set.
     * @return This builder for chaining.
     */
    public Builder setRepeatedField(boolean value) {
      
      repeatedField_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Indicates whether the field is a repeated field (i.e., an array or list).
     * AIP-140: boolean fields omit the `is_` prefix; `repeated` is a proto
     * keyword, so this reads as `repeated_field`.
     * </pre>
     *
     * <code>optional bool repeated_field = 6 [json_name = "repeatedField", (.google.api.field_behavior) = OPTIONAL];</code>
     * @return This builder for chaining.
     */
    public Builder clearRepeatedField() {
      bitField0_ = (bitField0_ & ~0x00000020);
      repeatedField_ = false;
      onChanged();
      return this;
    }

    private long repeatedIndex_ ;
    /**
     * <pre>
     * For repeated fields, the 0-based index of the element that caused the violation.
     * </pre>
     *
     * <code>optional uint64 repeated_index = 7 [json_name = "repeatedIndex", (.google.api.field_behavior) = OPTIONAL];</code>
     * @return Whether the repeatedIndex field is set.
     */
    @java.lang.Override
    public boolean hasRepeatedIndex() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * For repeated fields, the 0-based index of the element that caused the violation.
     * </pre>
     *
     * <code>optional uint64 repeated_index = 7 [json_name = "repeatedIndex", (.google.api.field_behavior) = OPTIONAL];</code>
     * @return The repeatedIndex.
     */
    @java.lang.Override
    public long getRepeatedIndex() {
      return repeatedIndex_;
    }
    /**
     * <pre>
     * For repeated fields, the 0-based index of the element that caused the violation.
     * </pre>
     *
     * <code>optional uint64 repeated_index = 7 [json_name = "repeatedIndex", (.google.api.field_behavior) = OPTIONAL];</code>
     * @param value The repeatedIndex to set.
     * @return This builder for chaining.
     */
    public Builder setRepeatedIndex(long value) {
      
      repeatedIndex_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * For repeated fields, the 0-based index of the element that caused the violation.
     * </pre>
     *
     * <code>optional uint64 repeated_index = 7 [json_name = "repeatedIndex", (.google.api.field_behavior) = OPTIONAL];</code>
     * @return This builder for chaining.
     */
    public Builder clearRepeatedIndex() {
      bitField0_ = (bitField0_ & ~0x00000040);
      repeatedIndex_ = 0L;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * The index if the map key is treated as an array index (less common for proto maps).
     * </pre>
     *
     * <code>uint64 index = 8 [json_name = "index"];</code>
     * @return Whether the index field is set.
     */
    public boolean hasIndex() {
      return mapKeyCase_ == 8;
    }
    /**
     * <pre>
     * The index if the map key is treated as an array index (less common for proto maps).
     * </pre>
     *
     * <code>uint64 index = 8 [json_name = "index"];</code>
     * @return The index.
     */
    public long getIndex() {
      if (mapKeyCase_ == 8) {
        return (java.lang.Long) mapKey_;
      }
      return 0L;
    }
    /**
     * <pre>
     * The index if the map key is treated as an array index (less common for proto maps).
     * </pre>
     *
     * <code>uint64 index = 8 [json_name = "index"];</code>
     * @param value The index to set.
     * @return This builder for chaining.
     */
    public Builder setIndex(long value) {
      
      mapKeyCase_ = 8;
      mapKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The index if the map key is treated as an array index (less common for proto maps).
     * </pre>
     *
     * <code>uint64 index = 8 [json_name = "index"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIndex() {
      if (mapKeyCase_ == 8) {
        mapKeyCase_ = 0;
        mapKey_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <pre>
     * The map key, if its type is `bool`.
     * </pre>
     *
     * <code>bool bool_key = 9 [json_name = "boolKey"];</code>
     * @return Whether the boolKey field is set.
     */
    public boolean hasBoolKey() {
      return mapKeyCase_ == 9;
    }
    /**
     * <pre>
     * The map key, if its type is `bool`.
     * </pre>
     *
     * <code>bool bool_key = 9 [json_name = "boolKey"];</code>
     * @return The boolKey.
     */
    public boolean getBoolKey() {
      if (mapKeyCase_ == 9) {
        return (java.lang.Boolean) mapKey_;
      }
      return false;
    }
    /**
     * <pre>
     * The map key, if its type is `bool`.
     * </pre>
     *
     * <code>bool bool_key = 9 [json_name = "boolKey"];</code>
     * @param value The boolKey to set.
     * @return This builder for chaining.
     */
    public Builder setBoolKey(boolean value) {
      
      mapKeyCase_ = 9;
      mapKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The map key, if its type is `bool`.
     * </pre>
     *
     * <code>bool bool_key = 9 [json_name = "boolKey"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBoolKey() {
      if (mapKeyCase_ == 9) {
        mapKeyCase_ = 0;
        mapKey_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <pre>
     * The map key, if its type is `int32`, `int64`, `sint32`, `sint64`, `sfixed32`, or `sfixed64`.
     * </pre>
     *
     * <code>int64 int_key = 10 [json_name = "intKey"];</code>
     * @return Whether the intKey field is set.
     */
    public boolean hasIntKey() {
      return mapKeyCase_ == 10;
    }
    /**
     * <pre>
     * The map key, if its type is `int32`, `int64`, `sint32`, `sint64`, `sfixed32`, or `sfixed64`.
     * </pre>
     *
     * <code>int64 int_key = 10 [json_name = "intKey"];</code>
     * @return The intKey.
     */
    public long getIntKey() {
      if (mapKeyCase_ == 10) {
        return (java.lang.Long) mapKey_;
      }
      return 0L;
    }
    /**
     * <pre>
     * The map key, if its type is `int32`, `int64`, `sint32`, `sint64`, `sfixed32`, or `sfixed64`.
     * </pre>
     *
     * <code>int64 int_key = 10 [json_name = "intKey"];</code>
     * @param value The intKey to set.
     * @return This builder for chaining.
     */
    public Builder setIntKey(long value) {
      
      mapKeyCase_ = 10;
      mapKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The map key, if its type is `int32`, `int64`, `sint32`, `sint64`, `sfixed32`, or `sfixed64`.
     * </pre>
     *
     * <code>int64 int_key = 10 [json_name = "intKey"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIntKey() {
      if (mapKeyCase_ == 10) {
        mapKeyCase_ = 0;
        mapKey_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <pre>
     * The map key, if its type is `uint32`, `uint64`, `fixed32`, or `fixed64`.
     * </pre>
     *
     * <code>uint64 uint_key = 11 [json_name = "uintKey"];</code>
     * @return Whether the uintKey field is set.
     */
    public boolean hasUintKey() {
      return mapKeyCase_ == 11;
    }
    /**
     * <pre>
     * The map key, if its type is `uint32`, `uint64`, `fixed32`, or `fixed64`.
     * </pre>
     *
     * <code>uint64 uint_key = 11 [json_name = "uintKey"];</code>
     * @return The uintKey.
     */
    public long getUintKey() {
      if (mapKeyCase_ == 11) {
        return (java.lang.Long) mapKey_;
      }
      return 0L;
    }
    /**
     * <pre>
     * The map key, if its type is `uint32`, `uint64`, `fixed32`, or `fixed64`.
     * </pre>
     *
     * <code>uint64 uint_key = 11 [json_name = "uintKey"];</code>
     * @param value The uintKey to set.
     * @return This builder for chaining.
     */
    public Builder setUintKey(long value) {
      
      mapKeyCase_ = 11;
      mapKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The map key, if its type is `uint32`, `uint64`, `fixed32`, or `fixed64`.
     * </pre>
     *
     * <code>uint64 uint_key = 11 [json_name = "uintKey"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUintKey() {
      if (mapKeyCase_ == 11) {
        mapKeyCase_ = 0;
        mapKey_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <pre>
     * The map key, if its type is `string`.
     * </pre>
     *
     * <code>string string_key = 12 [json_name = "stringKey"];</code>
     * @return Whether the stringKey field is set.
     */
    @java.lang.Override
    public boolean hasStringKey() {
      return mapKeyCase_ == 12;
    }
    /**
     * <pre>
     * The map key, if its type is `string`.
     * </pre>
     *
     * <code>string string_key = 12 [json_name = "stringKey"];</code>
     * @return The stringKey.
     */
    @java.lang.Override
    public java.lang.String getStringKey() {
      java.lang.Object ref = "";
      if (mapKeyCase_ == 12) {
        ref = mapKey_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (mapKeyCase_ == 12) {
          mapKey_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The map key, if its type is `string`.
     * </pre>
     *
     * <code>string string_key = 12 [json_name = "stringKey"];</code>
     * @return The bytes for stringKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStringKeyBytes() {
      java.lang.Object ref = "";
      if (mapKeyCase_ == 12) {
        ref = mapKey_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (mapKeyCase_ == 12) {
          mapKey_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The map key, if its type is `string`.
     * </pre>
     *
     * <code>string string_key = 12 [json_name = "stringKey"];</code>
     * @param value The stringKey to set.
     * @return This builder for chaining.
     */
    public Builder setStringKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      mapKeyCase_ = 12;
      mapKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The map key, if its type is `string`.
     * </pre>
     *
     * <code>string string_key = 12 [json_name = "stringKey"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStringKey() {
      if (mapKeyCase_ == 12) {
        mapKeyCase_ = 0;
        mapKey_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * The map key, if its type is `string`.
     * </pre>
     *
     * <code>string string_key = 12 [json_name = "stringKey"];</code>
     * @param value The bytes for stringKey to set.
     * @return This builder for chaining.
     */
    public Builder setStringKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      mapKeyCase_ = 12;
      mapKey_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.altessa.badrequest.v1.FieldPathComponent)
  }

  // @@protoc_insertion_point(class_scope:io.altessa.badrequest.v1.FieldPathComponent)
  private static final io.altessa.badrequest.v1.FieldPathComponent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.altessa.badrequest.v1.FieldPathComponent();
  }

  public static io.altessa.badrequest.v1.FieldPathComponent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FieldPathComponent>
      PARSER = new com.google.protobuf.AbstractParser<FieldPathComponent>() {
    @java.lang.Override
    public FieldPathComponent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FieldPathComponent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FieldPathComponent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.altessa.badrequest.v1.FieldPathComponent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

