// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/altessa/badrequest/v1/badrequest.proto

package io.altessa.badrequest.v1;

/**
 * <pre>
 * FieldType mirrors google.protobuf.FieldDescriptorProto.Type as an open
 * proto3 enum so this schema is usable from PHP and other generators
 * that disallow proto2 closed-enum dependencies in proto3 files. Numeric
 * values intentionally match the upstream FieldDescriptorProto.Type so
 * tools can cast or round-trip without a lookup table.
 * Stability (AIP-180): grows ONLY in lockstep with upstream
 * FieldDescriptorProto.Type — values are not added independently. New
 * proto wire types are exceedingly rare (the last addition was
 * `sint32` / `sint64` in 2008), so consumers can treat this enum as
 * effectively closed.
 * </pre>
 *
 * Protobuf enum {@code io.altessa.badrequest.v1.FieldType}
 */
public enum FieldType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>FIELD_TYPE_UNSPECIFIED = 0;</code>
   */
  FIELD_TYPE_UNSPECIFIED(0),
  /**
   * <code>FIELD_TYPE_DOUBLE = 1;</code>
   */
  FIELD_TYPE_DOUBLE(1),
  /**
   * <code>FIELD_TYPE_FLOAT = 2;</code>
   */
  FIELD_TYPE_FLOAT(2),
  /**
   * <code>FIELD_TYPE_INT64 = 3;</code>
   */
  FIELD_TYPE_INT64(3),
  /**
   * <code>FIELD_TYPE_UINT64 = 4;</code>
   */
  FIELD_TYPE_UINT64(4),
  /**
   * <code>FIELD_TYPE_INT32 = 5;</code>
   */
  FIELD_TYPE_INT32(5),
  /**
   * <code>FIELD_TYPE_FIXED64 = 6;</code>
   */
  FIELD_TYPE_FIXED64(6),
  /**
   * <code>FIELD_TYPE_FIXED32 = 7;</code>
   */
  FIELD_TYPE_FIXED32(7),
  /**
   * <code>FIELD_TYPE_BOOL = 8;</code>
   */
  FIELD_TYPE_BOOL(8),
  /**
   * <code>FIELD_TYPE_STRING = 9;</code>
   */
  FIELD_TYPE_STRING(9),
  /**
   * <code>FIELD_TYPE_GROUP = 10;</code>
   */
  FIELD_TYPE_GROUP(10),
  /**
   * <code>FIELD_TYPE_MESSAGE = 11;</code>
   */
  FIELD_TYPE_MESSAGE(11),
  /**
   * <code>FIELD_TYPE_BYTES = 12;</code>
   */
  FIELD_TYPE_BYTES(12),
  /**
   * <code>FIELD_TYPE_UINT32 = 13;</code>
   */
  FIELD_TYPE_UINT32(13),
  /**
   * <code>FIELD_TYPE_ENUM = 14;</code>
   */
  FIELD_TYPE_ENUM(14),
  /**
   * <code>FIELD_TYPE_SFIXED32 = 15;</code>
   */
  FIELD_TYPE_SFIXED32(15),
  /**
   * <code>FIELD_TYPE_SFIXED64 = 16;</code>
   */
  FIELD_TYPE_SFIXED64(16),
  /**
   * <code>FIELD_TYPE_SINT32 = 17;</code>
   */
  FIELD_TYPE_SINT32(17),
  /**
   * <code>FIELD_TYPE_SINT64 = 18;</code>
   */
  FIELD_TYPE_SINT64(18),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>FIELD_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int FIELD_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>FIELD_TYPE_DOUBLE = 1;</code>
   */
  public static final int FIELD_TYPE_DOUBLE_VALUE = 1;
  /**
   * <code>FIELD_TYPE_FLOAT = 2;</code>
   */
  public static final int FIELD_TYPE_FLOAT_VALUE = 2;
  /**
   * <code>FIELD_TYPE_INT64 = 3;</code>
   */
  public static final int FIELD_TYPE_INT64_VALUE = 3;
  /**
   * <code>FIELD_TYPE_UINT64 = 4;</code>
   */
  public static final int FIELD_TYPE_UINT64_VALUE = 4;
  /**
   * <code>FIELD_TYPE_INT32 = 5;</code>
   */
  public static final int FIELD_TYPE_INT32_VALUE = 5;
  /**
   * <code>FIELD_TYPE_FIXED64 = 6;</code>
   */
  public static final int FIELD_TYPE_FIXED64_VALUE = 6;
  /**
   * <code>FIELD_TYPE_FIXED32 = 7;</code>
   */
  public static final int FIELD_TYPE_FIXED32_VALUE = 7;
  /**
   * <code>FIELD_TYPE_BOOL = 8;</code>
   */
  public static final int FIELD_TYPE_BOOL_VALUE = 8;
  /**
   * <code>FIELD_TYPE_STRING = 9;</code>
   */
  public static final int FIELD_TYPE_STRING_VALUE = 9;
  /**
   * <code>FIELD_TYPE_GROUP = 10;</code>
   */
  public static final int FIELD_TYPE_GROUP_VALUE = 10;
  /**
   * <code>FIELD_TYPE_MESSAGE = 11;</code>
   */
  public static final int FIELD_TYPE_MESSAGE_VALUE = 11;
  /**
   * <code>FIELD_TYPE_BYTES = 12;</code>
   */
  public static final int FIELD_TYPE_BYTES_VALUE = 12;
  /**
   * <code>FIELD_TYPE_UINT32 = 13;</code>
   */
  public static final int FIELD_TYPE_UINT32_VALUE = 13;
  /**
   * <code>FIELD_TYPE_ENUM = 14;</code>
   */
  public static final int FIELD_TYPE_ENUM_VALUE = 14;
  /**
   * <code>FIELD_TYPE_SFIXED32 = 15;</code>
   */
  public static final int FIELD_TYPE_SFIXED32_VALUE = 15;
  /**
   * <code>FIELD_TYPE_SFIXED64 = 16;</code>
   */
  public static final int FIELD_TYPE_SFIXED64_VALUE = 16;
  /**
   * <code>FIELD_TYPE_SINT32 = 17;</code>
   */
  public static final int FIELD_TYPE_SINT32_VALUE = 17;
  /**
   * <code>FIELD_TYPE_SINT64 = 18;</code>
   */
  public static final int FIELD_TYPE_SINT64_VALUE = 18;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static FieldType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static FieldType forNumber(int value) {
    switch (value) {
      case 0: return FIELD_TYPE_UNSPECIFIED;
      case 1: return FIELD_TYPE_DOUBLE;
      case 2: return FIELD_TYPE_FLOAT;
      case 3: return FIELD_TYPE_INT64;
      case 4: return FIELD_TYPE_UINT64;
      case 5: return FIELD_TYPE_INT32;
      case 6: return FIELD_TYPE_FIXED64;
      case 7: return FIELD_TYPE_FIXED32;
      case 8: return FIELD_TYPE_BOOL;
      case 9: return FIELD_TYPE_STRING;
      case 10: return FIELD_TYPE_GROUP;
      case 11: return FIELD_TYPE_MESSAGE;
      case 12: return FIELD_TYPE_BYTES;
      case 13: return FIELD_TYPE_UINT32;
      case 14: return FIELD_TYPE_ENUM;
      case 15: return FIELD_TYPE_SFIXED32;
      case 16: return FIELD_TYPE_SFIXED64;
      case 17: return FIELD_TYPE_SINT32;
      case 18: return FIELD_TYPE_SINT64;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<FieldType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      FieldType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<FieldType>() {
          public FieldType findValueByNumber(int number) {
            return FieldType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return io.altessa.badrequest.v1.BadRequestProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final FieldType[] VALUES = values();

  public static FieldType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private FieldType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:io.altessa.badrequest.v1.FieldType)
}

