// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: badrequest/v1/badrequest.proto

package io.altessa.badrequest.v1;

/**
 * <pre>
 * Defines a specific issue with a single field in the request message.
 * It provides details about which field was problematic and why.
 * </pre>
 *
 * Protobuf type {@code io.altessa.badrequest.v1.FieldViolation}
 */
public final class FieldViolation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.altessa.badrequest.v1.FieldViolation)
    FieldViolationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FieldViolation.newBuilder() to construct.
  private FieldViolation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FieldViolation() {
    fieldPath_ = "";
    message_ = "";
    code_ = "";
    fieldPathComponents_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FieldViolation();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.altessa.badrequest.v1.Badrequest.internal_static_io_altessa_badrequest_v1_FieldViolation_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.altessa.badrequest.v1.Badrequest.internal_static_io_altessa_badrequest_v1_FieldViolation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.altessa.badrequest.v1.FieldViolation.class, io.altessa.badrequest.v1.FieldViolation.Builder.class);
  }

  private int bitField0_;
  public static final int FIELD_PATH_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object fieldPath_ = "";
  /**
   * <pre>
   * The dot-separated path to the field that caused the violation.
   * For example, "user.address.street" or "items[2].name".
   * </pre>
   *
   * <code>optional string field_path = 1 [json_name = "fieldPath"];</code>
   * @return Whether the fieldPath field is set.
   */
  @java.lang.Override
  public boolean hasFieldPath() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * The dot-separated path to the field that caused the violation.
   * For example, "user.address.street" or "items[2].name".
   * </pre>
   *
   * <code>optional string field_path = 1 [json_name = "fieldPath"];</code>
   * @return The fieldPath.
   */
  @java.lang.Override
  public java.lang.String getFieldPath() {
    java.lang.Object ref = fieldPath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        fieldPath_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * The dot-separated path to the field that caused the violation.
   * For example, "user.address.street" or "items[2].name".
   * </pre>
   *
   * <code>optional string field_path = 1 [json_name = "fieldPath"];</code>
   * @return The bytes for fieldPath.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFieldPathBytes() {
    java.lang.Object ref = fieldPath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fieldPath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object message_ = "";
  /**
   * <pre>
   * Human-readable message describing the violation.
   * This should be specific to the field and the error condition.
   * </pre>
   *
   * <code>optional string message = 2 [json_name = "message"];</code>
   * @return Whether the message field is set.
   */
  @java.lang.Override
  public boolean hasMessage() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Human-readable message describing the violation.
   * This should be specific to the field and the error condition.
   * </pre>
   *
   * <code>optional string message = 2 [json_name = "message"];</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        message_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * Human-readable message describing the violation.
   * This should be specific to the field and the error condition.
   * </pre>
   *
   * <code>optional string message = 2 [json_name = "message"];</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CODE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object code_ = "";
  /**
   * <pre>
   * Application-specific error code or identifier for this type of violation.
   * This can be used by clients for programmatic error handling.
   * </pre>
   *
   * <code>optional string code = 3 [json_name = "code"];</code>
   * @return Whether the code field is set.
   */
  @java.lang.Override
  public boolean hasCode() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * Application-specific error code or identifier for this type of violation.
   * This can be used by clients for programmatic error handling.
   * </pre>
   *
   * <code>optional string code = 3 [json_name = "code"];</code>
   * @return The code.
   */
  @java.lang.Override
  public java.lang.String getCode() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        code_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * Application-specific error code or identifier for this type of violation.
   * This can be used by clients for programmatic error handling.
   * </pre>
   *
   * <code>optional string code = 3 [json_name = "code"];</code>
   * @return The bytes for code.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCodeBytes() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      code_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIELD_PATH_COMPONENTS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<io.altessa.badrequest.v1.FieldPathComponent> fieldPathComponents_;
  /**
   * <pre>
   * Structured representation of the path to the field that caused the violation.
   * This provides more detailed information than `field_path` and can be used for
   * more precise error handling or display.
   * </pre>
   *
   * <code>repeated .io.altessa.badrequest.v1.FieldPathComponent field_path_components = 4 [json_name = "fieldPathComponents"];</code>
   */
  @java.lang.Override
  public java.util.List<io.altessa.badrequest.v1.FieldPathComponent> getFieldPathComponentsList() {
    return fieldPathComponents_;
  }
  /**
   * <pre>
   * Structured representation of the path to the field that caused the violation.
   * This provides more detailed information than `field_path` and can be used for
   * more precise error handling or display.
   * </pre>
   *
   * <code>repeated .io.altessa.badrequest.v1.FieldPathComponent field_path_components = 4 [json_name = "fieldPathComponents"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.altessa.badrequest.v1.FieldPathComponentOrBuilder> 
      getFieldPathComponentsOrBuilderList() {
    return fieldPathComponents_;
  }
  /**
   * <pre>
   * Structured representation of the path to the field that caused the violation.
   * This provides more detailed information than `field_path` and can be used for
   * more precise error handling or display.
   * </pre>
   *
   * <code>repeated .io.altessa.badrequest.v1.FieldPathComponent field_path_components = 4 [json_name = "fieldPathComponents"];</code>
   */
  @java.lang.Override
  public int getFieldPathComponentsCount() {
    return fieldPathComponents_.size();
  }
  /**
   * <pre>
   * Structured representation of the path to the field that caused the violation.
   * This provides more detailed information than `field_path` and can be used for
   * more precise error handling or display.
   * </pre>
   *
   * <code>repeated .io.altessa.badrequest.v1.FieldPathComponent field_path_components = 4 [json_name = "fieldPathComponents"];</code>
   */
  @java.lang.Override
  public io.altessa.badrequest.v1.FieldPathComponent getFieldPathComponents(int index) {
    return fieldPathComponents_.get(index);
  }
  /**
   * <pre>
   * Structured representation of the path to the field that caused the violation.
   * This provides more detailed information than `field_path` and can be used for
   * more precise error handling or display.
   * </pre>
   *
   * <code>repeated .io.altessa.badrequest.v1.FieldPathComponent field_path_components = 4 [json_name = "fieldPathComponents"];</code>
   */
  @java.lang.Override
  public io.altessa.badrequest.v1.FieldPathComponentOrBuilder getFieldPathComponentsOrBuilder(
      int index) {
    return fieldPathComponents_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fieldPath_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, code_);
    }
    for (int i = 0; i < fieldPathComponents_.size(); i++) {
      output.writeMessage(4, fieldPathComponents_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fieldPath_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, code_);
    }
    for (int i = 0; i < fieldPathComponents_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, fieldPathComponents_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.altessa.badrequest.v1.FieldViolation)) {
      return super.equals(obj);
    }
    io.altessa.badrequest.v1.FieldViolation other = (io.altessa.badrequest.v1.FieldViolation) obj;

    if (hasFieldPath() != other.hasFieldPath()) return false;
    if (hasFieldPath()) {
      if (!getFieldPath()
          .equals(other.getFieldPath())) return false;
    }
    if (hasMessage() != other.hasMessage()) return false;
    if (hasMessage()) {
      if (!getMessage()
          .equals(other.getMessage())) return false;
    }
    if (hasCode() != other.hasCode()) return false;
    if (hasCode()) {
      if (!getCode()
          .equals(other.getCode())) return false;
    }
    if (!getFieldPathComponentsList()
        .equals(other.getFieldPathComponentsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasFieldPath()) {
      hash = (37 * hash) + FIELD_PATH_FIELD_NUMBER;
      hash = (53 * hash) + getFieldPath().hashCode();
    }
    if (hasMessage()) {
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
    }
    if (hasCode()) {
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode().hashCode();
    }
    if (getFieldPathComponentsCount() > 0) {
      hash = (37 * hash) + FIELD_PATH_COMPONENTS_FIELD_NUMBER;
      hash = (53 * hash) + getFieldPathComponentsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.altessa.badrequest.v1.FieldViolation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.altessa.badrequest.v1.FieldViolation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.altessa.badrequest.v1.FieldViolation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.altessa.badrequest.v1.FieldViolation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.altessa.badrequest.v1.FieldViolation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.altessa.badrequest.v1.FieldViolation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.altessa.badrequest.v1.FieldViolation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.altessa.badrequest.v1.FieldViolation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.altessa.badrequest.v1.FieldViolation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.altessa.badrequest.v1.FieldViolation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.altessa.badrequest.v1.FieldViolation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.altessa.badrequest.v1.FieldViolation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.altessa.badrequest.v1.FieldViolation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Defines a specific issue with a single field in the request message.
   * It provides details about which field was problematic and why.
   * </pre>
   *
   * Protobuf type {@code io.altessa.badrequest.v1.FieldViolation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.altessa.badrequest.v1.FieldViolation)
      io.altessa.badrequest.v1.FieldViolationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.altessa.badrequest.v1.Badrequest.internal_static_io_altessa_badrequest_v1_FieldViolation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.altessa.badrequest.v1.Badrequest.internal_static_io_altessa_badrequest_v1_FieldViolation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.altessa.badrequest.v1.FieldViolation.class, io.altessa.badrequest.v1.FieldViolation.Builder.class);
    }

    // Construct using io.altessa.badrequest.v1.FieldViolation.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      fieldPath_ = "";
      message_ = "";
      code_ = "";
      if (fieldPathComponentsBuilder_ == null) {
        fieldPathComponents_ = java.util.Collections.emptyList();
      } else {
        fieldPathComponents_ = null;
        fieldPathComponentsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.altessa.badrequest.v1.Badrequest.internal_static_io_altessa_badrequest_v1_FieldViolation_descriptor;
    }

    @java.lang.Override
    public io.altessa.badrequest.v1.FieldViolation getDefaultInstanceForType() {
      return io.altessa.badrequest.v1.FieldViolation.getDefaultInstance();
    }

    @java.lang.Override
    public io.altessa.badrequest.v1.FieldViolation build() {
      io.altessa.badrequest.v1.FieldViolation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.altessa.badrequest.v1.FieldViolation buildPartial() {
      io.altessa.badrequest.v1.FieldViolation result = new io.altessa.badrequest.v1.FieldViolation(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.altessa.badrequest.v1.FieldViolation result) {
      if (fieldPathComponentsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          fieldPathComponents_ = java.util.Collections.unmodifiableList(fieldPathComponents_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.fieldPathComponents_ = fieldPathComponents_;
      } else {
        result.fieldPathComponents_ = fieldPathComponentsBuilder_.build();
      }
    }

    private void buildPartial0(io.altessa.badrequest.v1.FieldViolation result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.fieldPath_ = fieldPath_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.message_ = message_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.code_ = code_;
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.altessa.badrequest.v1.FieldViolation) {
        return mergeFrom((io.altessa.badrequest.v1.FieldViolation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.altessa.badrequest.v1.FieldViolation other) {
      if (other == io.altessa.badrequest.v1.FieldViolation.getDefaultInstance()) return this;
      if (other.hasFieldPath()) {
        fieldPath_ = other.fieldPath_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasMessage()) {
        message_ = other.message_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasCode()) {
        code_ = other.code_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (fieldPathComponentsBuilder_ == null) {
        if (!other.fieldPathComponents_.isEmpty()) {
          if (fieldPathComponents_.isEmpty()) {
            fieldPathComponents_ = other.fieldPathComponents_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureFieldPathComponentsIsMutable();
            fieldPathComponents_.addAll(other.fieldPathComponents_);
          }
          onChanged();
        }
      } else {
        if (!other.fieldPathComponents_.isEmpty()) {
          if (fieldPathComponentsBuilder_.isEmpty()) {
            fieldPathComponentsBuilder_.dispose();
            fieldPathComponentsBuilder_ = null;
            fieldPathComponents_ = other.fieldPathComponents_;
            bitField0_ = (bitField0_ & ~0x00000008);
            fieldPathComponentsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFieldPathComponentsFieldBuilder() : null;
          } else {
            fieldPathComponentsBuilder_.addAllMessages(other.fieldPathComponents_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              fieldPath_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              message_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              code_ = input.readBytes();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              io.altessa.badrequest.v1.FieldPathComponent m =
                  input.readMessage(
                      io.altessa.badrequest.v1.FieldPathComponent.PARSER,
                      extensionRegistry);
              if (fieldPathComponentsBuilder_ == null) {
                ensureFieldPathComponentsIsMutable();
                fieldPathComponents_.add(m);
              } else {
                fieldPathComponentsBuilder_.addMessage(m);
              }
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object fieldPath_ = "";
    /**
     * <pre>
     * The dot-separated path to the field that caused the violation.
     * For example, "user.address.street" or "items[2].name".
     * </pre>
     *
     * <code>optional string field_path = 1 [json_name = "fieldPath"];</code>
     * @return Whether the fieldPath field is set.
     */
    public boolean hasFieldPath() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The dot-separated path to the field that caused the violation.
     * For example, "user.address.street" or "items[2].name".
     * </pre>
     *
     * <code>optional string field_path = 1 [json_name = "fieldPath"];</code>
     * @return The fieldPath.
     */
    public java.lang.String getFieldPath() {
      java.lang.Object ref = fieldPath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fieldPath_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The dot-separated path to the field that caused the violation.
     * For example, "user.address.street" or "items[2].name".
     * </pre>
     *
     * <code>optional string field_path = 1 [json_name = "fieldPath"];</code>
     * @return The bytes for fieldPath.
     */
    public com.google.protobuf.ByteString
        getFieldPathBytes() {
      java.lang.Object ref = fieldPath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fieldPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The dot-separated path to the field that caused the violation.
     * For example, "user.address.street" or "items[2].name".
     * </pre>
     *
     * <code>optional string field_path = 1 [json_name = "fieldPath"];</code>
     * @param value The fieldPath to set.
     * @return This builder for chaining.
     */
    public Builder setFieldPath(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      fieldPath_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The dot-separated path to the field that caused the violation.
     * For example, "user.address.street" or "items[2].name".
     * </pre>
     *
     * <code>optional string field_path = 1 [json_name = "fieldPath"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFieldPath() {
      fieldPath_ = getDefaultInstance().getFieldPath();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The dot-separated path to the field that caused the violation.
     * For example, "user.address.street" or "items[2].name".
     * </pre>
     *
     * <code>optional string field_path = 1 [json_name = "fieldPath"];</code>
     * @param value The bytes for fieldPath to set.
     * @return This builder for chaining.
     */
    public Builder setFieldPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      fieldPath_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <pre>
     * Human-readable message describing the violation.
     * This should be specific to the field and the error condition.
     * </pre>
     *
     * <code>optional string message = 2 [json_name = "message"];</code>
     * @return Whether the message field is set.
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Human-readable message describing the violation.
     * This should be specific to the field and the error condition.
     * </pre>
     *
     * <code>optional string message = 2 [json_name = "message"];</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Human-readable message describing the violation.
     * This should be specific to the field and the error condition.
     * </pre>
     *
     * <code>optional string message = 2 [json_name = "message"];</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Human-readable message describing the violation.
     * This should be specific to the field and the error condition.
     * </pre>
     *
     * <code>optional string message = 2 [json_name = "message"];</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      message_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Human-readable message describing the violation.
     * This should be specific to the field and the error condition.
     * </pre>
     *
     * <code>optional string message = 2 [json_name = "message"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      message_ = getDefaultInstance().getMessage();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Human-readable message describing the violation.
     * This should be specific to the field and the error condition.
     * </pre>
     *
     * <code>optional string message = 2 [json_name = "message"];</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      message_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object code_ = "";
    /**
     * <pre>
     * Application-specific error code or identifier for this type of violation.
     * This can be used by clients for programmatic error handling.
     * </pre>
     *
     * <code>optional string code = 3 [json_name = "code"];</code>
     * @return Whether the code field is set.
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Application-specific error code or identifier for this type of violation.
     * This can be used by clients for programmatic error handling.
     * </pre>
     *
     * <code>optional string code = 3 [json_name = "code"];</code>
     * @return The code.
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          code_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Application-specific error code or identifier for this type of violation.
     * This can be used by clients for programmatic error handling.
     * </pre>
     *
     * <code>optional string code = 3 [json_name = "code"];</code>
     * @return The bytes for code.
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Application-specific error code or identifier for this type of violation.
     * This can be used by clients for programmatic error handling.
     * </pre>
     *
     * <code>optional string code = 3 [json_name = "code"];</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      code_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Application-specific error code or identifier for this type of violation.
     * This can be used by clients for programmatic error handling.
     * </pre>
     *
     * <code>optional string code = 3 [json_name = "code"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      code_ = getDefaultInstance().getCode();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Application-specific error code or identifier for this type of violation.
     * This can be used by clients for programmatic error handling.
     * </pre>
     *
     * <code>optional string code = 3 [json_name = "code"];</code>
     * @param value The bytes for code to set.
     * @return This builder for chaining.
     */
    public Builder setCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      code_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.util.List<io.altessa.badrequest.v1.FieldPathComponent> fieldPathComponents_ =
      java.util.Collections.emptyList();
    private void ensureFieldPathComponentsIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        fieldPathComponents_ = new java.util.ArrayList<io.altessa.badrequest.v1.FieldPathComponent>(fieldPathComponents_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.altessa.badrequest.v1.FieldPathComponent, io.altessa.badrequest.v1.FieldPathComponent.Builder, io.altessa.badrequest.v1.FieldPathComponentOrBuilder> fieldPathComponentsBuilder_;

    /**
     * <pre>
     * Structured representation of the path to the field that caused the violation.
     * This provides more detailed information than `field_path` and can be used for
     * more precise error handling or display.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldPathComponent field_path_components = 4 [json_name = "fieldPathComponents"];</code>
     */
    public java.util.List<io.altessa.badrequest.v1.FieldPathComponent> getFieldPathComponentsList() {
      if (fieldPathComponentsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(fieldPathComponents_);
      } else {
        return fieldPathComponentsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Structured representation of the path to the field that caused the violation.
     * This provides more detailed information than `field_path` and can be used for
     * more precise error handling or display.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldPathComponent field_path_components = 4 [json_name = "fieldPathComponents"];</code>
     */
    public int getFieldPathComponentsCount() {
      if (fieldPathComponentsBuilder_ == null) {
        return fieldPathComponents_.size();
      } else {
        return fieldPathComponentsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Structured representation of the path to the field that caused the violation.
     * This provides more detailed information than `field_path` and can be used for
     * more precise error handling or display.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldPathComponent field_path_components = 4 [json_name = "fieldPathComponents"];</code>
     */
    public io.altessa.badrequest.v1.FieldPathComponent getFieldPathComponents(int index) {
      if (fieldPathComponentsBuilder_ == null) {
        return fieldPathComponents_.get(index);
      } else {
        return fieldPathComponentsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Structured representation of the path to the field that caused the violation.
     * This provides more detailed information than `field_path` and can be used for
     * more precise error handling or display.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldPathComponent field_path_components = 4 [json_name = "fieldPathComponents"];</code>
     */
    public Builder setFieldPathComponents(
        int index, io.altessa.badrequest.v1.FieldPathComponent value) {
      if (fieldPathComponentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFieldPathComponentsIsMutable();
        fieldPathComponents_.set(index, value);
        onChanged();
      } else {
        fieldPathComponentsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Structured representation of the path to the field that caused the violation.
     * This provides more detailed information than `field_path` and can be used for
     * more precise error handling or display.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldPathComponent field_path_components = 4 [json_name = "fieldPathComponents"];</code>
     */
    public Builder setFieldPathComponents(
        int index, io.altessa.badrequest.v1.FieldPathComponent.Builder builderForValue) {
      if (fieldPathComponentsBuilder_ == null) {
        ensureFieldPathComponentsIsMutable();
        fieldPathComponents_.set(index, builderForValue.build());
        onChanged();
      } else {
        fieldPathComponentsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Structured representation of the path to the field that caused the violation.
     * This provides more detailed information than `field_path` and can be used for
     * more precise error handling or display.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldPathComponent field_path_components = 4 [json_name = "fieldPathComponents"];</code>
     */
    public Builder addFieldPathComponents(io.altessa.badrequest.v1.FieldPathComponent value) {
      if (fieldPathComponentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFieldPathComponentsIsMutable();
        fieldPathComponents_.add(value);
        onChanged();
      } else {
        fieldPathComponentsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Structured representation of the path to the field that caused the violation.
     * This provides more detailed information than `field_path` and can be used for
     * more precise error handling or display.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldPathComponent field_path_components = 4 [json_name = "fieldPathComponents"];</code>
     */
    public Builder addFieldPathComponents(
        int index, io.altessa.badrequest.v1.FieldPathComponent value) {
      if (fieldPathComponentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFieldPathComponentsIsMutable();
        fieldPathComponents_.add(index, value);
        onChanged();
      } else {
        fieldPathComponentsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Structured representation of the path to the field that caused the violation.
     * This provides more detailed information than `field_path` and can be used for
     * more precise error handling or display.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldPathComponent field_path_components = 4 [json_name = "fieldPathComponents"];</code>
     */
    public Builder addFieldPathComponents(
        io.altessa.badrequest.v1.FieldPathComponent.Builder builderForValue) {
      if (fieldPathComponentsBuilder_ == null) {
        ensureFieldPathComponentsIsMutable();
        fieldPathComponents_.add(builderForValue.build());
        onChanged();
      } else {
        fieldPathComponentsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Structured representation of the path to the field that caused the violation.
     * This provides more detailed information than `field_path` and can be used for
     * more precise error handling or display.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldPathComponent field_path_components = 4 [json_name = "fieldPathComponents"];</code>
     */
    public Builder addFieldPathComponents(
        int index, io.altessa.badrequest.v1.FieldPathComponent.Builder builderForValue) {
      if (fieldPathComponentsBuilder_ == null) {
        ensureFieldPathComponentsIsMutable();
        fieldPathComponents_.add(index, builderForValue.build());
        onChanged();
      } else {
        fieldPathComponentsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Structured representation of the path to the field that caused the violation.
     * This provides more detailed information than `field_path` and can be used for
     * more precise error handling or display.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldPathComponent field_path_components = 4 [json_name = "fieldPathComponents"];</code>
     */
    public Builder addAllFieldPathComponents(
        java.lang.Iterable<? extends io.altessa.badrequest.v1.FieldPathComponent> values) {
      if (fieldPathComponentsBuilder_ == null) {
        ensureFieldPathComponentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fieldPathComponents_);
        onChanged();
      } else {
        fieldPathComponentsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Structured representation of the path to the field that caused the violation.
     * This provides more detailed information than `field_path` and can be used for
     * more precise error handling or display.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldPathComponent field_path_components = 4 [json_name = "fieldPathComponents"];</code>
     */
    public Builder clearFieldPathComponents() {
      if (fieldPathComponentsBuilder_ == null) {
        fieldPathComponents_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        fieldPathComponentsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Structured representation of the path to the field that caused the violation.
     * This provides more detailed information than `field_path` and can be used for
     * more precise error handling or display.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldPathComponent field_path_components = 4 [json_name = "fieldPathComponents"];</code>
     */
    public Builder removeFieldPathComponents(int index) {
      if (fieldPathComponentsBuilder_ == null) {
        ensureFieldPathComponentsIsMutable();
        fieldPathComponents_.remove(index);
        onChanged();
      } else {
        fieldPathComponentsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Structured representation of the path to the field that caused the violation.
     * This provides more detailed information than `field_path` and can be used for
     * more precise error handling or display.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldPathComponent field_path_components = 4 [json_name = "fieldPathComponents"];</code>
     */
    public io.altessa.badrequest.v1.FieldPathComponent.Builder getFieldPathComponentsBuilder(
        int index) {
      return getFieldPathComponentsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Structured representation of the path to the field that caused the violation.
     * This provides more detailed information than `field_path` and can be used for
     * more precise error handling or display.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldPathComponent field_path_components = 4 [json_name = "fieldPathComponents"];</code>
     */
    public io.altessa.badrequest.v1.FieldPathComponentOrBuilder getFieldPathComponentsOrBuilder(
        int index) {
      if (fieldPathComponentsBuilder_ == null) {
        return fieldPathComponents_.get(index);  } else {
        return fieldPathComponentsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Structured representation of the path to the field that caused the violation.
     * This provides more detailed information than `field_path` and can be used for
     * more precise error handling or display.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldPathComponent field_path_components = 4 [json_name = "fieldPathComponents"];</code>
     */
    public java.util.List<? extends io.altessa.badrequest.v1.FieldPathComponentOrBuilder> 
         getFieldPathComponentsOrBuilderList() {
      if (fieldPathComponentsBuilder_ != null) {
        return fieldPathComponentsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(fieldPathComponents_);
      }
    }
    /**
     * <pre>
     * Structured representation of the path to the field that caused the violation.
     * This provides more detailed information than `field_path` and can be used for
     * more precise error handling or display.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldPathComponent field_path_components = 4 [json_name = "fieldPathComponents"];</code>
     */
    public io.altessa.badrequest.v1.FieldPathComponent.Builder addFieldPathComponentsBuilder() {
      return getFieldPathComponentsFieldBuilder().addBuilder(
          io.altessa.badrequest.v1.FieldPathComponent.getDefaultInstance());
    }
    /**
     * <pre>
     * Structured representation of the path to the field that caused the violation.
     * This provides more detailed information than `field_path` and can be used for
     * more precise error handling or display.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldPathComponent field_path_components = 4 [json_name = "fieldPathComponents"];</code>
     */
    public io.altessa.badrequest.v1.FieldPathComponent.Builder addFieldPathComponentsBuilder(
        int index) {
      return getFieldPathComponentsFieldBuilder().addBuilder(
          index, io.altessa.badrequest.v1.FieldPathComponent.getDefaultInstance());
    }
    /**
     * <pre>
     * Structured representation of the path to the field that caused the violation.
     * This provides more detailed information than `field_path` and can be used for
     * more precise error handling or display.
     * </pre>
     *
     * <code>repeated .io.altessa.badrequest.v1.FieldPathComponent field_path_components = 4 [json_name = "fieldPathComponents"];</code>
     */
    public java.util.List<io.altessa.badrequest.v1.FieldPathComponent.Builder> 
         getFieldPathComponentsBuilderList() {
      return getFieldPathComponentsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.altessa.badrequest.v1.FieldPathComponent, io.altessa.badrequest.v1.FieldPathComponent.Builder, io.altessa.badrequest.v1.FieldPathComponentOrBuilder> 
        getFieldPathComponentsFieldBuilder() {
      if (fieldPathComponentsBuilder_ == null) {
        fieldPathComponentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.altessa.badrequest.v1.FieldPathComponent, io.altessa.badrequest.v1.FieldPathComponent.Builder, io.altessa.badrequest.v1.FieldPathComponentOrBuilder>(
                fieldPathComponents_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        fieldPathComponents_ = null;
      }
      return fieldPathComponentsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.altessa.badrequest.v1.FieldViolation)
  }

  // @@protoc_insertion_point(class_scope:io.altessa.badrequest.v1.FieldViolation)
  private static final io.altessa.badrequest.v1.FieldViolation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.altessa.badrequest.v1.FieldViolation();
  }

  public static io.altessa.badrequest.v1.FieldViolation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<FieldViolation>
      PARSER = new com.google.protobuf.AbstractParser<FieldViolation>() {
    @java.lang.Override
    public FieldViolation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FieldViolation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FieldViolation> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.altessa.badrequest.v1.FieldViolation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

