// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/altessa/badrequest/v1/badrequest.proto

package io.altessa.badrequest.v1;

public interface FieldPathComponentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.altessa.badrequest.v1.FieldPathComponent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Field number as defined in the .proto file.
   * </pre>
   *
   * <code>optional int32 number = 1 [json_name = "number", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return Whether the number field is set.
   */
  boolean hasNumber();
  /**
   * <pre>
   * Field number as defined in the .proto file.
   * </pre>
   *
   * <code>optional int32 number = 1 [json_name = "number", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return The number.
   */
  int getNumber();

  /**
   * <pre>
   * Name of the field as defined in the .proto file.
   * </pre>
   *
   * <code>optional string name = 2 [json_name = "name", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <pre>
   * Name of the field as defined in the .proto file.
   * </pre>
   *
   * <code>optional string name = 2 [json_name = "name", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Name of the field as defined in the .proto file.
   * </pre>
   *
   * <code>optional string name = 2 [json_name = "name", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Data type of the field.
   * </pre>
   *
   * <code>optional .io.altessa.badrequest.v1.FieldType type = 3 [json_name = "type", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return Whether the type field is set.
   */
  boolean hasType();
  /**
   * <pre>
   * Data type of the field.
   * </pre>
   *
   * <code>optional .io.altessa.badrequest.v1.FieldType type = 3 [json_name = "type", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <pre>
   * Data type of the field.
   * </pre>
   *
   * <code>optional .io.altessa.badrequest.v1.FieldType type = 3 [json_name = "type", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return The type.
   */
  io.altessa.badrequest.v1.FieldType getType();

  /**
   * <pre>
   * For map fields, specifies the data type of the map keys.
   * </pre>
   *
   * <code>optional .io.altessa.badrequest.v1.FieldType map_key_type = 4 [json_name = "mapKeyType", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return Whether the mapKeyType field is set.
   */
  boolean hasMapKeyType();
  /**
   * <pre>
   * For map fields, specifies the data type of the map keys.
   * </pre>
   *
   * <code>optional .io.altessa.badrequest.v1.FieldType map_key_type = 4 [json_name = "mapKeyType", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return The enum numeric value on the wire for mapKeyType.
   */
  int getMapKeyTypeValue();
  /**
   * <pre>
   * For map fields, specifies the data type of the map keys.
   * </pre>
   *
   * <code>optional .io.altessa.badrequest.v1.FieldType map_key_type = 4 [json_name = "mapKeyType", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return The mapKeyType.
   */
  io.altessa.badrequest.v1.FieldType getMapKeyType();

  /**
   * <pre>
   * For map fields, specifies the data type of the map values.
   * </pre>
   *
   * <code>optional .io.altessa.badrequest.v1.FieldType map_value_type = 5 [json_name = "mapValueType", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return Whether the mapValueType field is set.
   */
  boolean hasMapValueType();
  /**
   * <pre>
   * For map fields, specifies the data type of the map values.
   * </pre>
   *
   * <code>optional .io.altessa.badrequest.v1.FieldType map_value_type = 5 [json_name = "mapValueType", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return The enum numeric value on the wire for mapValueType.
   */
  int getMapValueTypeValue();
  /**
   * <pre>
   * For map fields, specifies the data type of the map values.
   * </pre>
   *
   * <code>optional .io.altessa.badrequest.v1.FieldType map_value_type = 5 [json_name = "mapValueType", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return The mapValueType.
   */
  io.altessa.badrequest.v1.FieldType getMapValueType();

  /**
   * <pre>
   * Indicates whether the field is a repeated field (i.e., an array or list).
   * AIP-140: boolean fields omit the `is_` prefix; `repeated` is a proto
   * keyword, so this reads as `repeated_field`.
   * </pre>
   *
   * <code>optional bool repeated_field = 6 [json_name = "repeatedField", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return Whether the repeatedField field is set.
   */
  boolean hasRepeatedField();
  /**
   * <pre>
   * Indicates whether the field is a repeated field (i.e., an array or list).
   * AIP-140: boolean fields omit the `is_` prefix; `repeated` is a proto
   * keyword, so this reads as `repeated_field`.
   * </pre>
   *
   * <code>optional bool repeated_field = 6 [json_name = "repeatedField", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return The repeatedField.
   */
  boolean getRepeatedField();

  /**
   * <pre>
   * For repeated fields, the 0-based index of the element that caused the violation.
   * </pre>
   *
   * <code>optional uint64 repeated_index = 7 [json_name = "repeatedIndex", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return Whether the repeatedIndex field is set.
   */
  boolean hasRepeatedIndex();
  /**
   * <pre>
   * For repeated fields, the 0-based index of the element that caused the violation.
   * </pre>
   *
   * <code>optional uint64 repeated_index = 7 [json_name = "repeatedIndex", (.google.api.field_behavior) = OPTIONAL];</code>
   * @return The repeatedIndex.
   */
  long getRepeatedIndex();

  /**
   * <pre>
   * The index if the map key is treated as an array index (less common for proto maps).
   * </pre>
   *
   * <code>uint64 index = 8 [json_name = "index"];</code>
   * @return Whether the index field is set.
   */
  boolean hasIndex();
  /**
   * <pre>
   * The index if the map key is treated as an array index (less common for proto maps).
   * </pre>
   *
   * <code>uint64 index = 8 [json_name = "index"];</code>
   * @return The index.
   */
  long getIndex();

  /**
   * <pre>
   * The map key, if its type is `bool`.
   * </pre>
   *
   * <code>bool bool_key = 9 [json_name = "boolKey"];</code>
   * @return Whether the boolKey field is set.
   */
  boolean hasBoolKey();
  /**
   * <pre>
   * The map key, if its type is `bool`.
   * </pre>
   *
   * <code>bool bool_key = 9 [json_name = "boolKey"];</code>
   * @return The boolKey.
   */
  boolean getBoolKey();

  /**
   * <pre>
   * The map key, if its type is `int32`, `int64`, `sint32`, `sint64`, `sfixed32`, or `sfixed64`.
   * </pre>
   *
   * <code>int64 int_key = 10 [json_name = "intKey"];</code>
   * @return Whether the intKey field is set.
   */
  boolean hasIntKey();
  /**
   * <pre>
   * The map key, if its type is `int32`, `int64`, `sint32`, `sint64`, `sfixed32`, or `sfixed64`.
   * </pre>
   *
   * <code>int64 int_key = 10 [json_name = "intKey"];</code>
   * @return The intKey.
   */
  long getIntKey();

  /**
   * <pre>
   * The map key, if its type is `uint32`, `uint64`, `fixed32`, or `fixed64`.
   * </pre>
   *
   * <code>uint64 uint_key = 11 [json_name = "uintKey"];</code>
   * @return Whether the uintKey field is set.
   */
  boolean hasUintKey();
  /**
   * <pre>
   * The map key, if its type is `uint32`, `uint64`, `fixed32`, or `fixed64`.
   * </pre>
   *
   * <code>uint64 uint_key = 11 [json_name = "uintKey"];</code>
   * @return The uintKey.
   */
  long getUintKey();

  /**
   * <pre>
   * The map key, if its type is `string`.
   * </pre>
   *
   * <code>string string_key = 12 [json_name = "stringKey"];</code>
   * @return Whether the stringKey field is set.
   */
  boolean hasStringKey();
  /**
   * <pre>
   * The map key, if its type is `string`.
   * </pre>
   *
   * <code>string string_key = 12 [json_name = "stringKey"];</code>
   * @return The stringKey.
   */
  java.lang.String getStringKey();
  /**
   * <pre>
   * The map key, if its type is `string`.
   * </pre>
   *
   * <code>string string_key = 12 [json_name = "stringKey"];</code>
   * @return The bytes for stringKey.
   */
  com.google.protobuf.ByteString
      getStringKeyBytes();

  public io.altessa.badrequest.v1.FieldPathComponent.MapKeyCase getMapKeyCase();
}
