// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/altessa/type/v1/date_period.proto

package io.altessa.type.v1;

public interface DatePeriodOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.altessa.type.v1.DatePeriod)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Start date, inclusive.
   * </pre>
   *
   * <code>.google.type.Date start_date = 1 [json_name = "startDate", (.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the startDate field is set.
   */
  boolean hasStartDate();
  /**
   * <pre>
   * Start date, inclusive.
   * </pre>
   *
   * <code>.google.type.Date start_date = 1 [json_name = "startDate", (.google.api.field_behavior) = REQUIRED];</code>
   * @return The startDate.
   */
  com.google.type.Date getStartDate();
  /**
   * <pre>
   * Start date, inclusive.
   * </pre>
   *
   * <code>.google.type.Date start_date = 1 [json_name = "startDate", (.google.api.field_behavior) = REQUIRED];</code>
   */
  com.google.type.DateOrBuilder getStartDateOrBuilder();

  /**
   * <pre>
   * End date, inclusive. MUST be on or after start_date.
   * </pre>
   *
   * <code>.google.type.Date end_date = 2 [json_name = "endDate", (.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the endDate field is set.
   */
  boolean hasEndDate();
  /**
   * <pre>
   * End date, inclusive. MUST be on or after start_date.
   * </pre>
   *
   * <code>.google.type.Date end_date = 2 [json_name = "endDate", (.google.api.field_behavior) = REQUIRED];</code>
   * @return The endDate.
   */
  com.google.type.Date getEndDate();
  /**
   * <pre>
   * End date, inclusive. MUST be on or after start_date.
   * </pre>
   *
   * <code>.google.type.Date end_date = 2 [json_name = "endDate", (.google.api.field_behavior) = REQUIRED];</code>
   */
  com.google.type.DateOrBuilder getEndDateOrBuilder();
}
