// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/altessa/type/v1/date_period.proto

package io.altessa.type.v1;

/**
 * <pre>
 * A calendar-date range, inclusive on both ends. Use this for ranges that
 * have no wall-clock component (billing periods, leave windows, …);
 * use google.type.Interval for ranges defined by absolute timestamps.
 * Producers MUST ensure `end_date &gt;= start_date`. A zero-length period
 * (start == end) is a valid one-day range. Consumers SHOULD reject
 * requests that violate the ordering invariant with INVALID_ARGUMENT.
 * `google.type.Date` permits partially-specified values (year-only,
 * year + month, …). `DatePeriod` requires BOTH bounds to be fully
 * specified — non-zero `year`, `month`, and `day` — so consumers can
 * do calendar arithmetic without ambiguity. Producers SHOULD reject
 * partial dates before constructing a `DatePeriod`.
 * Timezone: `google.type.Date` is timezone-naive by design. The
 * surrounding domain decides how to interpret it (e.g. "the billing
 * month in the merchant's local tz"). Do not attach timezone state to
 * a `DatePeriod` via a side-channel — if you need timezone-aware
 * ranges, use `google.type.Interval` instead.
 * </pre>
 *
 * Protobuf type {@code io.altessa.type.v1.DatePeriod}
 */
public final class DatePeriod extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.altessa.type.v1.DatePeriod)
    DatePeriodOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DatePeriod.newBuilder() to construct.
  private DatePeriod(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DatePeriod() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DatePeriod();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.altessa.type.v1.DatePeriodProto.internal_static_io_altessa_type_v1_DatePeriod_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.altessa.type.v1.DatePeriodProto.internal_static_io_altessa_type_v1_DatePeriod_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.altessa.type.v1.DatePeriod.class, io.altessa.type.v1.DatePeriod.Builder.class);
  }

  public static final int START_DATE_FIELD_NUMBER = 1;
  private com.google.type.Date startDate_;
  /**
   * <pre>
   * Start date, inclusive.
   * </pre>
   *
   * <code>.google.type.Date start_date = 1 [json_name = "startDate", (.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the startDate field is set.
   */
  @java.lang.Override
  public boolean hasStartDate() {
    return startDate_ != null;
  }
  /**
   * <pre>
   * Start date, inclusive.
   * </pre>
   *
   * <code>.google.type.Date start_date = 1 [json_name = "startDate", (.google.api.field_behavior) = REQUIRED];</code>
   * @return The startDate.
   */
  @java.lang.Override
  public com.google.type.Date getStartDate() {
    return startDate_ == null ? com.google.type.Date.getDefaultInstance() : startDate_;
  }
  /**
   * <pre>
   * Start date, inclusive.
   * </pre>
   *
   * <code>.google.type.Date start_date = 1 [json_name = "startDate", (.google.api.field_behavior) = REQUIRED];</code>
   */
  @java.lang.Override
  public com.google.type.DateOrBuilder getStartDateOrBuilder() {
    return startDate_ == null ? com.google.type.Date.getDefaultInstance() : startDate_;
  }

  public static final int END_DATE_FIELD_NUMBER = 2;
  private com.google.type.Date endDate_;
  /**
   * <pre>
   * End date, inclusive. MUST be on or after start_date.
   * </pre>
   *
   * <code>.google.type.Date end_date = 2 [json_name = "endDate", (.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the endDate field is set.
   */
  @java.lang.Override
  public boolean hasEndDate() {
    return endDate_ != null;
  }
  /**
   * <pre>
   * End date, inclusive. MUST be on or after start_date.
   * </pre>
   *
   * <code>.google.type.Date end_date = 2 [json_name = "endDate", (.google.api.field_behavior) = REQUIRED];</code>
   * @return The endDate.
   */
  @java.lang.Override
  public com.google.type.Date getEndDate() {
    return endDate_ == null ? com.google.type.Date.getDefaultInstance() : endDate_;
  }
  /**
   * <pre>
   * End date, inclusive. MUST be on or after start_date.
   * </pre>
   *
   * <code>.google.type.Date end_date = 2 [json_name = "endDate", (.google.api.field_behavior) = REQUIRED];</code>
   */
  @java.lang.Override
  public com.google.type.DateOrBuilder getEndDateOrBuilder() {
    return endDate_ == null ? com.google.type.Date.getDefaultInstance() : endDate_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (startDate_ != null) {
      output.writeMessage(1, getStartDate());
    }
    if (endDate_ != null) {
      output.writeMessage(2, getEndDate());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (startDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getStartDate());
    }
    if (endDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getEndDate());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.altessa.type.v1.DatePeriod)) {
      return super.equals(obj);
    }
    io.altessa.type.v1.DatePeriod other = (io.altessa.type.v1.DatePeriod) obj;

    if (hasStartDate() != other.hasStartDate()) return false;
    if (hasStartDate()) {
      if (!getStartDate()
          .equals(other.getStartDate())) return false;
    }
    if (hasEndDate() != other.hasEndDate()) return false;
    if (hasEndDate()) {
      if (!getEndDate()
          .equals(other.getEndDate())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStartDate()) {
      hash = (37 * hash) + START_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getStartDate().hashCode();
    }
    if (hasEndDate()) {
      hash = (37 * hash) + END_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getEndDate().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.altessa.type.v1.DatePeriod parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.altessa.type.v1.DatePeriod parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.altessa.type.v1.DatePeriod parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.altessa.type.v1.DatePeriod parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.altessa.type.v1.DatePeriod parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.altessa.type.v1.DatePeriod parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.altessa.type.v1.DatePeriod parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.altessa.type.v1.DatePeriod parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.altessa.type.v1.DatePeriod parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.altessa.type.v1.DatePeriod parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.altessa.type.v1.DatePeriod parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.altessa.type.v1.DatePeriod parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.altessa.type.v1.DatePeriod prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A calendar-date range, inclusive on both ends. Use this for ranges that
   * have no wall-clock component (billing periods, leave windows, …);
   * use google.type.Interval for ranges defined by absolute timestamps.
   * Producers MUST ensure `end_date &gt;= start_date`. A zero-length period
   * (start == end) is a valid one-day range. Consumers SHOULD reject
   * requests that violate the ordering invariant with INVALID_ARGUMENT.
   * `google.type.Date` permits partially-specified values (year-only,
   * year + month, …). `DatePeriod` requires BOTH bounds to be fully
   * specified — non-zero `year`, `month`, and `day` — so consumers can
   * do calendar arithmetic without ambiguity. Producers SHOULD reject
   * partial dates before constructing a `DatePeriod`.
   * Timezone: `google.type.Date` is timezone-naive by design. The
   * surrounding domain decides how to interpret it (e.g. "the billing
   * month in the merchant's local tz"). Do not attach timezone state to
   * a `DatePeriod` via a side-channel — if you need timezone-aware
   * ranges, use `google.type.Interval` instead.
   * </pre>
   *
   * Protobuf type {@code io.altessa.type.v1.DatePeriod}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.altessa.type.v1.DatePeriod)
      io.altessa.type.v1.DatePeriodOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.altessa.type.v1.DatePeriodProto.internal_static_io_altessa_type_v1_DatePeriod_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.altessa.type.v1.DatePeriodProto.internal_static_io_altessa_type_v1_DatePeriod_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.altessa.type.v1.DatePeriod.class, io.altessa.type.v1.DatePeriod.Builder.class);
    }

    // Construct using io.altessa.type.v1.DatePeriod.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      startDate_ = null;
      if (startDateBuilder_ != null) {
        startDateBuilder_.dispose();
        startDateBuilder_ = null;
      }
      endDate_ = null;
      if (endDateBuilder_ != null) {
        endDateBuilder_.dispose();
        endDateBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.altessa.type.v1.DatePeriodProto.internal_static_io_altessa_type_v1_DatePeriod_descriptor;
    }

    @java.lang.Override
    public io.altessa.type.v1.DatePeriod getDefaultInstanceForType() {
      return io.altessa.type.v1.DatePeriod.getDefaultInstance();
    }

    @java.lang.Override
    public io.altessa.type.v1.DatePeriod build() {
      io.altessa.type.v1.DatePeriod result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.altessa.type.v1.DatePeriod buildPartial() {
      io.altessa.type.v1.DatePeriod result = new io.altessa.type.v1.DatePeriod(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.altessa.type.v1.DatePeriod result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.startDate_ = startDateBuilder_ == null
            ? startDate_
            : startDateBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.endDate_ = endDateBuilder_ == null
            ? endDate_
            : endDateBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.altessa.type.v1.DatePeriod) {
        return mergeFrom((io.altessa.type.v1.DatePeriod)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.altessa.type.v1.DatePeriod other) {
      if (other == io.altessa.type.v1.DatePeriod.getDefaultInstance()) return this;
      if (other.hasStartDate()) {
        mergeStartDate(other.getStartDate());
      }
      if (other.hasEndDate()) {
        mergeEndDate(other.getEndDate());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getStartDateFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getEndDateFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.type.Date startDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Date, com.google.type.Date.Builder, com.google.type.DateOrBuilder> startDateBuilder_;
    /**
     * <pre>
     * Start date, inclusive.
     * </pre>
     *
     * <code>.google.type.Date start_date = 1 [json_name = "startDate", (.google.api.field_behavior) = REQUIRED];</code>
     * @return Whether the startDate field is set.
     */
    public boolean hasStartDate() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Start date, inclusive.
     * </pre>
     *
     * <code>.google.type.Date start_date = 1 [json_name = "startDate", (.google.api.field_behavior) = REQUIRED];</code>
     * @return The startDate.
     */
    public com.google.type.Date getStartDate() {
      if (startDateBuilder_ == null) {
        return startDate_ == null ? com.google.type.Date.getDefaultInstance() : startDate_;
      } else {
        return startDateBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Start date, inclusive.
     * </pre>
     *
     * <code>.google.type.Date start_date = 1 [json_name = "startDate", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setStartDate(com.google.type.Date value) {
      if (startDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        startDate_ = value;
      } else {
        startDateBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Start date, inclusive.
     * </pre>
     *
     * <code>.google.type.Date start_date = 1 [json_name = "startDate", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setStartDate(
        com.google.type.Date.Builder builderForValue) {
      if (startDateBuilder_ == null) {
        startDate_ = builderForValue.build();
      } else {
        startDateBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Start date, inclusive.
     * </pre>
     *
     * <code>.google.type.Date start_date = 1 [json_name = "startDate", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder mergeStartDate(com.google.type.Date value) {
      if (startDateBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          startDate_ != null &&
          startDate_ != com.google.type.Date.getDefaultInstance()) {
          getStartDateBuilder().mergeFrom(value);
        } else {
          startDate_ = value;
        }
      } else {
        startDateBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Start date, inclusive.
     * </pre>
     *
     * <code>.google.type.Date start_date = 1 [json_name = "startDate", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder clearStartDate() {
      bitField0_ = (bitField0_ & ~0x00000001);
      startDate_ = null;
      if (startDateBuilder_ != null) {
        startDateBuilder_.dispose();
        startDateBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Start date, inclusive.
     * </pre>
     *
     * <code>.google.type.Date start_date = 1 [json_name = "startDate", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public com.google.type.Date.Builder getStartDateBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getStartDateFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Start date, inclusive.
     * </pre>
     *
     * <code>.google.type.Date start_date = 1 [json_name = "startDate", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public com.google.type.DateOrBuilder getStartDateOrBuilder() {
      if (startDateBuilder_ != null) {
        return startDateBuilder_.getMessageOrBuilder();
      } else {
        return startDate_ == null ?
            com.google.type.Date.getDefaultInstance() : startDate_;
      }
    }
    /**
     * <pre>
     * Start date, inclusive.
     * </pre>
     *
     * <code>.google.type.Date start_date = 1 [json_name = "startDate", (.google.api.field_behavior) = REQUIRED];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Date, com.google.type.Date.Builder, com.google.type.DateOrBuilder> 
        getStartDateFieldBuilder() {
      if (startDateBuilder_ == null) {
        startDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.type.Date, com.google.type.Date.Builder, com.google.type.DateOrBuilder>(
                getStartDate(),
                getParentForChildren(),
                isClean());
        startDate_ = null;
      }
      return startDateBuilder_;
    }

    private com.google.type.Date endDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Date, com.google.type.Date.Builder, com.google.type.DateOrBuilder> endDateBuilder_;
    /**
     * <pre>
     * End date, inclusive. MUST be on or after start_date.
     * </pre>
     *
     * <code>.google.type.Date end_date = 2 [json_name = "endDate", (.google.api.field_behavior) = REQUIRED];</code>
     * @return Whether the endDate field is set.
     */
    public boolean hasEndDate() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * End date, inclusive. MUST be on or after start_date.
     * </pre>
     *
     * <code>.google.type.Date end_date = 2 [json_name = "endDate", (.google.api.field_behavior) = REQUIRED];</code>
     * @return The endDate.
     */
    public com.google.type.Date getEndDate() {
      if (endDateBuilder_ == null) {
        return endDate_ == null ? com.google.type.Date.getDefaultInstance() : endDate_;
      } else {
        return endDateBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * End date, inclusive. MUST be on or after start_date.
     * </pre>
     *
     * <code>.google.type.Date end_date = 2 [json_name = "endDate", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setEndDate(com.google.type.Date value) {
      if (endDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        endDate_ = value;
      } else {
        endDateBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * End date, inclusive. MUST be on or after start_date.
     * </pre>
     *
     * <code>.google.type.Date end_date = 2 [json_name = "endDate", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setEndDate(
        com.google.type.Date.Builder builderForValue) {
      if (endDateBuilder_ == null) {
        endDate_ = builderForValue.build();
      } else {
        endDateBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * End date, inclusive. MUST be on or after start_date.
     * </pre>
     *
     * <code>.google.type.Date end_date = 2 [json_name = "endDate", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder mergeEndDate(com.google.type.Date value) {
      if (endDateBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          endDate_ != null &&
          endDate_ != com.google.type.Date.getDefaultInstance()) {
          getEndDateBuilder().mergeFrom(value);
        } else {
          endDate_ = value;
        }
      } else {
        endDateBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * End date, inclusive. MUST be on or after start_date.
     * </pre>
     *
     * <code>.google.type.Date end_date = 2 [json_name = "endDate", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder clearEndDate() {
      bitField0_ = (bitField0_ & ~0x00000002);
      endDate_ = null;
      if (endDateBuilder_ != null) {
        endDateBuilder_.dispose();
        endDateBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * End date, inclusive. MUST be on or after start_date.
     * </pre>
     *
     * <code>.google.type.Date end_date = 2 [json_name = "endDate", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public com.google.type.Date.Builder getEndDateBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getEndDateFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * End date, inclusive. MUST be on or after start_date.
     * </pre>
     *
     * <code>.google.type.Date end_date = 2 [json_name = "endDate", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public com.google.type.DateOrBuilder getEndDateOrBuilder() {
      if (endDateBuilder_ != null) {
        return endDateBuilder_.getMessageOrBuilder();
      } else {
        return endDate_ == null ?
            com.google.type.Date.getDefaultInstance() : endDate_;
      }
    }
    /**
     * <pre>
     * End date, inclusive. MUST be on or after start_date.
     * </pre>
     *
     * <code>.google.type.Date end_date = 2 [json_name = "endDate", (.google.api.field_behavior) = REQUIRED];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Date, com.google.type.Date.Builder, com.google.type.DateOrBuilder> 
        getEndDateFieldBuilder() {
      if (endDateBuilder_ == null) {
        endDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.type.Date, com.google.type.Date.Builder, com.google.type.DateOrBuilder>(
                getEndDate(),
                getParentForChildren(),
                isClean());
        endDate_ = null;
      }
      return endDateBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.altessa.type.v1.DatePeriod)
  }

  // @@protoc_insertion_point(class_scope:io.altessa.type.v1.DatePeriod)
  private static final io.altessa.type.v1.DatePeriod DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.altessa.type.v1.DatePeriod();
  }

  public static io.altessa.type.v1.DatePeriod getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DatePeriod>
      PARSER = new com.google.protobuf.AbstractParser<DatePeriod>() {
    @java.lang.Override
    public DatePeriod parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DatePeriod> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DatePeriod> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.altessa.type.v1.DatePeriod getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

