// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: type/v1/document_ref.proto

package io.altessa.type.v1;

/**
 * <pre>
 * A user-facing document: a FileRef plus presentation metadata. Use this
 * when displaying attached documents in UIs ("Contract.pdf — signed copy");
 * use FileRef directly when only the underlying file is needed.
 * </pre>
 *
 * Protobuf type {@code io.altessa.type.v1.DocumentRef}
 */
public final class DocumentRef extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.altessa.type.v1.DocumentRef)
    DocumentRefOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DocumentRef.newBuilder() to construct.
  private DocumentRef(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DocumentRef() {
    title_ = "";
    description_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DocumentRef();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.altessa.type.v1.DocumentRefOuterClass.internal_static_io_altessa_type_v1_DocumentRef_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.altessa.type.v1.DocumentRefOuterClass.internal_static_io_altessa_type_v1_DocumentRef_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.altessa.type.v1.DocumentRef.class, io.altessa.type.v1.DocumentRef.Builder.class);
  }

  private int bitField0_;
  public static final int FILE_FIELD_NUMBER = 1;
  private io.altessa.type.v1.FileRef file_;
  /**
   * <pre>
   * Underlying file.
   * </pre>
   *
   * <code>.io.altessa.type.v1.FileRef file = 1 [json_name = "file", (.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the file field is set.
   */
  @java.lang.Override
  public boolean hasFile() {
    return file_ != null;
  }
  /**
   * <pre>
   * Underlying file.
   * </pre>
   *
   * <code>.io.altessa.type.v1.FileRef file = 1 [json_name = "file", (.google.api.field_behavior) = REQUIRED];</code>
   * @return The file.
   */
  @java.lang.Override
  public io.altessa.type.v1.FileRef getFile() {
    return file_ == null ? io.altessa.type.v1.FileRef.getDefaultInstance() : file_;
  }
  /**
   * <pre>
   * Underlying file.
   * </pre>
   *
   * <code>.io.altessa.type.v1.FileRef file = 1 [json_name = "file", (.google.api.field_behavior) = REQUIRED];</code>
   */
  @java.lang.Override
  public io.altessa.type.v1.FileRefOrBuilder getFileOrBuilder() {
    return file_ == null ? io.altessa.type.v1.FileRef.getDefaultInstance() : file_;
  }

  public static final int TITLE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object title_ = "";
  /**
   * <pre>
   * Display title, e.g. "Service agreement — 2026 edition". Not required
   * to match `file.metadata.filename`.
   * </pre>
   *
   * <code>string title = 2 [json_name = "title", (.google.api.field_behavior) = REQUIRED];</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Display title, e.g. "Service agreement — 2026 edition". Not required
   * to match `file.metadata.filename`.
   * </pre>
   *
   * <code>string title = 2 [json_name = "title", (.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   * <pre>
   * Longer-form description shown alongside the title (purpose, version
   * notes, …).
   * </pre>
   *
   * <code>optional string description = 3 [json_name = "description"];</code>
   * @return Whether the description field is set.
   */
  @java.lang.Override
  public boolean hasDescription() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Longer-form description shown alongside the title (purpose, version
   * notes, …).
   * </pre>
   *
   * <code>optional string description = 3 [json_name = "description"];</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Longer-form description shown alongside the title (purpose, version
   * notes, …).
   * </pre>
   *
   * <code>optional string description = 3 [json_name = "description"];</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (file_ != null) {
      output.writeMessage(1, getFile());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, description_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (file_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getFile());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, description_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.altessa.type.v1.DocumentRef)) {
      return super.equals(obj);
    }
    io.altessa.type.v1.DocumentRef other = (io.altessa.type.v1.DocumentRef) obj;

    if (hasFile() != other.hasFile()) return false;
    if (hasFile()) {
      if (!getFile()
          .equals(other.getFile())) return false;
    }
    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (hasDescription() != other.hasDescription()) return false;
    if (hasDescription()) {
      if (!getDescription()
          .equals(other.getDescription())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasFile()) {
      hash = (37 * hash) + FILE_FIELD_NUMBER;
      hash = (53 * hash) + getFile().hashCode();
    }
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    if (hasDescription()) {
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.altessa.type.v1.DocumentRef parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.altessa.type.v1.DocumentRef parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.altessa.type.v1.DocumentRef parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.altessa.type.v1.DocumentRef parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.altessa.type.v1.DocumentRef parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.altessa.type.v1.DocumentRef parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.altessa.type.v1.DocumentRef parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.altessa.type.v1.DocumentRef parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.altessa.type.v1.DocumentRef parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.altessa.type.v1.DocumentRef parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.altessa.type.v1.DocumentRef parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.altessa.type.v1.DocumentRef parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.altessa.type.v1.DocumentRef prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A user-facing document: a FileRef plus presentation metadata. Use this
   * when displaying attached documents in UIs ("Contract.pdf — signed copy");
   * use FileRef directly when only the underlying file is needed.
   * </pre>
   *
   * Protobuf type {@code io.altessa.type.v1.DocumentRef}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.altessa.type.v1.DocumentRef)
      io.altessa.type.v1.DocumentRefOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.altessa.type.v1.DocumentRefOuterClass.internal_static_io_altessa_type_v1_DocumentRef_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.altessa.type.v1.DocumentRefOuterClass.internal_static_io_altessa_type_v1_DocumentRef_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.altessa.type.v1.DocumentRef.class, io.altessa.type.v1.DocumentRef.Builder.class);
    }

    // Construct using io.altessa.type.v1.DocumentRef.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      file_ = null;
      if (fileBuilder_ != null) {
        fileBuilder_.dispose();
        fileBuilder_ = null;
      }
      title_ = "";
      description_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.altessa.type.v1.DocumentRefOuterClass.internal_static_io_altessa_type_v1_DocumentRef_descriptor;
    }

    @java.lang.Override
    public io.altessa.type.v1.DocumentRef getDefaultInstanceForType() {
      return io.altessa.type.v1.DocumentRef.getDefaultInstance();
    }

    @java.lang.Override
    public io.altessa.type.v1.DocumentRef build() {
      io.altessa.type.v1.DocumentRef result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.altessa.type.v1.DocumentRef buildPartial() {
      io.altessa.type.v1.DocumentRef result = new io.altessa.type.v1.DocumentRef(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.altessa.type.v1.DocumentRef result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.file_ = fileBuilder_ == null
            ? file_
            : fileBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.title_ = title_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.description_ = description_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.altessa.type.v1.DocumentRef) {
        return mergeFrom((io.altessa.type.v1.DocumentRef)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.altessa.type.v1.DocumentRef other) {
      if (other == io.altessa.type.v1.DocumentRef.getDefaultInstance()) return this;
      if (other.hasFile()) {
        mergeFile(other.getFile());
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasDescription()) {
        description_ = other.description_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getFileFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              title_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private io.altessa.type.v1.FileRef file_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.altessa.type.v1.FileRef, io.altessa.type.v1.FileRef.Builder, io.altessa.type.v1.FileRefOrBuilder> fileBuilder_;
    /**
     * <pre>
     * Underlying file.
     * </pre>
     *
     * <code>.io.altessa.type.v1.FileRef file = 1 [json_name = "file", (.google.api.field_behavior) = REQUIRED];</code>
     * @return Whether the file field is set.
     */
    public boolean hasFile() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Underlying file.
     * </pre>
     *
     * <code>.io.altessa.type.v1.FileRef file = 1 [json_name = "file", (.google.api.field_behavior) = REQUIRED];</code>
     * @return The file.
     */
    public io.altessa.type.v1.FileRef getFile() {
      if (fileBuilder_ == null) {
        return file_ == null ? io.altessa.type.v1.FileRef.getDefaultInstance() : file_;
      } else {
        return fileBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Underlying file.
     * </pre>
     *
     * <code>.io.altessa.type.v1.FileRef file = 1 [json_name = "file", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setFile(io.altessa.type.v1.FileRef value) {
      if (fileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        file_ = value;
      } else {
        fileBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Underlying file.
     * </pre>
     *
     * <code>.io.altessa.type.v1.FileRef file = 1 [json_name = "file", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setFile(
        io.altessa.type.v1.FileRef.Builder builderForValue) {
      if (fileBuilder_ == null) {
        file_ = builderForValue.build();
      } else {
        fileBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Underlying file.
     * </pre>
     *
     * <code>.io.altessa.type.v1.FileRef file = 1 [json_name = "file", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder mergeFile(io.altessa.type.v1.FileRef value) {
      if (fileBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          file_ != null &&
          file_ != io.altessa.type.v1.FileRef.getDefaultInstance()) {
          getFileBuilder().mergeFrom(value);
        } else {
          file_ = value;
        }
      } else {
        fileBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Underlying file.
     * </pre>
     *
     * <code>.io.altessa.type.v1.FileRef file = 1 [json_name = "file", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder clearFile() {
      bitField0_ = (bitField0_ & ~0x00000001);
      file_ = null;
      if (fileBuilder_ != null) {
        fileBuilder_.dispose();
        fileBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Underlying file.
     * </pre>
     *
     * <code>.io.altessa.type.v1.FileRef file = 1 [json_name = "file", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public io.altessa.type.v1.FileRef.Builder getFileBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getFileFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Underlying file.
     * </pre>
     *
     * <code>.io.altessa.type.v1.FileRef file = 1 [json_name = "file", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public io.altessa.type.v1.FileRefOrBuilder getFileOrBuilder() {
      if (fileBuilder_ != null) {
        return fileBuilder_.getMessageOrBuilder();
      } else {
        return file_ == null ?
            io.altessa.type.v1.FileRef.getDefaultInstance() : file_;
      }
    }
    /**
     * <pre>
     * Underlying file.
     * </pre>
     *
     * <code>.io.altessa.type.v1.FileRef file = 1 [json_name = "file", (.google.api.field_behavior) = REQUIRED];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.altessa.type.v1.FileRef, io.altessa.type.v1.FileRef.Builder, io.altessa.type.v1.FileRefOrBuilder> 
        getFileFieldBuilder() {
      if (fileBuilder_ == null) {
        fileBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.altessa.type.v1.FileRef, io.altessa.type.v1.FileRef.Builder, io.altessa.type.v1.FileRefOrBuilder>(
                getFile(),
                getParentForChildren(),
                isClean());
        file_ = null;
      }
      return fileBuilder_;
    }

    private java.lang.Object title_ = "";
    /**
     * <pre>
     * Display title, e.g. "Service agreement — 2026 edition". Not required
     * to match `file.metadata.filename`.
     * </pre>
     *
     * <code>string title = 2 [json_name = "title", (.google.api.field_behavior) = REQUIRED];</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Display title, e.g. "Service agreement — 2026 edition". Not required
     * to match `file.metadata.filename`.
     * </pre>
     *
     * <code>string title = 2 [json_name = "title", (.google.api.field_behavior) = REQUIRED];</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Display title, e.g. "Service agreement — 2026 edition". Not required
     * to match `file.metadata.filename`.
     * </pre>
     *
     * <code>string title = 2 [json_name = "title", (.google.api.field_behavior) = REQUIRED];</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      title_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Display title, e.g. "Service agreement — 2026 edition". Not required
     * to match `file.metadata.filename`.
     * </pre>
     *
     * <code>string title = 2 [json_name = "title", (.google.api.field_behavior) = REQUIRED];</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      title_ = getDefaultInstance().getTitle();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Display title, e.g. "Service agreement — 2026 edition". Not required
     * to match `file.metadata.filename`.
     * </pre>
     *
     * <code>string title = 2 [json_name = "title", (.google.api.field_behavior) = REQUIRED];</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      title_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <pre>
     * Longer-form description shown alongside the title (purpose, version
     * notes, …).
     * </pre>
     *
     * <code>optional string description = 3 [json_name = "description"];</code>
     * @return Whether the description field is set.
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Longer-form description shown alongside the title (purpose, version
     * notes, …).
     * </pre>
     *
     * <code>optional string description = 3 [json_name = "description"];</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Longer-form description shown alongside the title (purpose, version
     * notes, …).
     * </pre>
     *
     * <code>optional string description = 3 [json_name = "description"];</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Longer-form description shown alongside the title (purpose, version
     * notes, …).
     * </pre>
     *
     * <code>optional string description = 3 [json_name = "description"];</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      description_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Longer-form description shown alongside the title (purpose, version
     * notes, …).
     * </pre>
     *
     * <code>optional string description = 3 [json_name = "description"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Longer-form description shown alongside the title (purpose, version
     * notes, …).
     * </pre>
     *
     * <code>optional string description = 3 [json_name = "description"];</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.altessa.type.v1.DocumentRef)
  }

  // @@protoc_insertion_point(class_scope:io.altessa.type.v1.DocumentRef)
  private static final io.altessa.type.v1.DocumentRef DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.altessa.type.v1.DocumentRef();
  }

  public static io.altessa.type.v1.DocumentRef getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DocumentRef>
      PARSER = new com.google.protobuf.AbstractParser<DocumentRef>() {
    @java.lang.Override
    public DocumentRef parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DocumentRef> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DocumentRef> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.altessa.type.v1.DocumentRef getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

