// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/altessa/type/v1/document_ref.proto

package io.altessa.type.v1;

public interface DocumentRefOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.altessa.type.v1.DocumentRef)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Underlying file.
   * </pre>
   *
   * <code>.io.altessa.type.v1.FileRef file = 1 [json_name = "file", (.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the file field is set.
   */
  boolean hasFile();
  /**
   * <pre>
   * Underlying file.
   * </pre>
   *
   * <code>.io.altessa.type.v1.FileRef file = 1 [json_name = "file", (.google.api.field_behavior) = REQUIRED];</code>
   * @return The file.
   */
  io.altessa.type.v1.FileRef getFile();
  /**
   * <pre>
   * Underlying file.
   * </pre>
   *
   * <code>.io.altessa.type.v1.FileRef file = 1 [json_name = "file", (.google.api.field_behavior) = REQUIRED];</code>
   */
  io.altessa.type.v1.FileRefOrBuilder getFileOrBuilder();

  /**
   * <pre>
   * Display title, e.g. "Service agreement — 2026 edition". Not required
   * to match `file.metadata.filename`.
   * </pre>
   *
   * <code>string title = 2 [json_name = "title", (.google.api.field_behavior) = REQUIRED];</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <pre>
   * Display title, e.g. "Service agreement — 2026 edition". Not required
   * to match `file.metadata.filename`.
   * </pre>
   *
   * <code>string title = 2 [json_name = "title", (.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <pre>
   * Longer-form description shown alongside the title (purpose, version
   * notes, …).
   * </pre>
   *
   * <code>optional string description = 3 [json_name = "description"];</code>
   * @return Whether the description field is set.
   */
  boolean hasDescription();
  /**
   * <pre>
   * Longer-form description shown alongside the title (purpose, version
   * notes, …).
   * </pre>
   *
   * <code>optional string description = 3 [json_name = "description"];</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * Longer-form description shown alongside the title (purpose, version
   * notes, …).
   * </pre>
   *
   * <code>optional string description = 3 [json_name = "description"];</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
