// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: type/v1/document_ref.proto

package io.altessa.type.v1;

public final class DocumentRefOuterClass {
  private DocumentRefOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_altessa_type_v1_DocumentRef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_altessa_type_v1_DocumentRef_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032type/v1/document_ref.proto\022\022io.altessa" +
      ".type.v1\032\037google/api/field_behavior.prot" +
      "o\032\026type/v1/file_ref.proto\"\225\001\n\013DocumentRe" +
      "f\0224\n\004file\030\001 \001(\0132\033.io.altessa.type.v1.Fil" +
      "eRefB\003\340A\002R\004file\022\031\n\005title\030\002 \001(\tB\003\340A\002R\005tit" +
      "le\022%\n\013description\030\003 \001(\tH\000R\013description\210\001" +
      "\001B\016\n\014_descriptionBH\n\022io.altessa.type.v1P" +
      "\001Z0github.com/altessa-s/proto-gen-go/typ" +
      "e/v1;typev1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.FieldBehaviorProto.getDescriptor(),
          io.altessa.type.v1.FileRefOuterClass.getDescriptor(),
        });
    internal_static_io_altessa_type_v1_DocumentRef_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_altessa_type_v1_DocumentRef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_altessa_type_v1_DocumentRef_descriptor,
        new java.lang.String[] { "File", "Title", "Description", "Description", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.FieldBehaviorProto.getDescriptor();
    io.altessa.type.v1.FileRefOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
