// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: type/v1/file_ref.proto

package io.altessa.type.v1;

public interface FileRefOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.altessa.type.v1.FileRef)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * URL for accessing the file. MAY be permanent or a time-limited signed
   * URL — readers must not cache it beyond the lifetime granted by the
   * issuer.
   * </pre>
   *
   * <code>string url = 1 [json_name = "url", (.google.api.field_behavior) = REQUIRED];</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <pre>
   * URL for accessing the file. MAY be permanent or a time-limited signed
   * URL — readers must not cache it beyond the lifetime granted by the
   * issuer.
   * </pre>
   *
   * <code>string url = 1 [json_name = "url", (.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <pre>
   * Stable identifier of the file in the issuing system. Opaque to
   * consumers; suitable for re-requesting a fresh URL. Assigned at
   * upload time and never changes afterwards.
   * </pre>
   *
   * <code>string id = 2 [json_name = "id", (.google.api.field_behavior) = REQUIRED, (.google.api.field_behavior) = IMMUTABLE];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * Stable identifier of the file in the issuing system. Opaque to
   * consumers; suitable for re-requesting a fresh URL. Assigned at
   * upload time and never changes afterwards.
   * </pre>
   *
   * <code>string id = 2 [json_name = "id", (.google.api.field_behavior) = REQUIRED, (.google.api.field_behavior) = IMMUTABLE];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * File metadata, when known.
   * </pre>
   *
   * <code>.io.altessa.type.v1.FileRef.Metadata metadata = 3 [json_name = "metadata"];</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <pre>
   * File metadata, when known.
   * </pre>
   *
   * <code>.io.altessa.type.v1.FileRef.Metadata metadata = 3 [json_name = "metadata"];</code>
   * @return The metadata.
   */
  io.altessa.type.v1.FileRef.Metadata getMetadata();
  /**
   * <pre>
   * File metadata, when known.
   * </pre>
   *
   * <code>.io.altessa.type.v1.FileRef.Metadata metadata = 3 [json_name = "metadata"];</code>
   */
  io.altessa.type.v1.FileRef.MetadataOrBuilder getMetadataOrBuilder();
}
