// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/altessa/type/v1/file_ref.proto

package io.altessa.type.v1;

/**
 * <pre>
 * Reference to a file held in an external system (object storage, CDN, …).
 * Carries enough information to retrieve the file and describe it for
 * display. The schema is intentionally storage-agnostic — neither bucket
 * nor backend is encoded here.
 * </pre>
 *
 * Protobuf type {@code io.altessa.type.v1.FileRef}
 */
public final class FileRef extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.altessa.type.v1.FileRef)
    FileRefOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FileRef.newBuilder() to construct.
  private FileRef(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FileRef() {
    url_ = "";
    id_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FileRef();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.altessa.type.v1.FileRefProto.internal_static_io_altessa_type_v1_FileRef_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.altessa.type.v1.FileRefProto.internal_static_io_altessa_type_v1_FileRef_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.altessa.type.v1.FileRef.class, io.altessa.type.v1.FileRef.Builder.class);
  }

  public interface MetadataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.altessa.type.v1.FileRef.Metadata)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * IANA media type of the file content (RFC 6838), e.g. "image/png",
     * "application/pdf", "text/plain".
     * </pre>
     *
     * <code>string mime_type = 1 [json_name = "mimeType"];</code>
     * @return The mimeType.
     */
    java.lang.String getMimeType();
    /**
     * <pre>
     * IANA media type of the file content (RFC 6838), e.g. "image/png",
     * "application/pdf", "text/plain".
     * </pre>
     *
     * <code>string mime_type = 1 [json_name = "mimeType"];</code>
     * @return The bytes for mimeType.
     */
    com.google.protobuf.ByteString
        getMimeTypeBytes();

    /**
     * <pre>
     * Size of the file in bytes. Negative values are not meaningful.
     * </pre>
     *
     * <code>int64 size_bytes = 2 [json_name = "sizeBytes"];</code>
     * @return The sizeBytes.
     */
    long getSizeBytes();

    /**
     * <pre>
     * Original filename including extension, e.g. "report.pdf",
     * "photo.jpg". Not guaranteed to be unique within the storage backend.
     * </pre>
     *
     * <code>string filename = 3 [json_name = "filename"];</code>
     * @return The filename.
     */
    java.lang.String getFilename();
    /**
     * <pre>
     * Original filename including extension, e.g. "report.pdf",
     * "photo.jpg". Not guaranteed to be unique within the storage backend.
     * </pre>
     *
     * <code>string filename = 3 [json_name = "filename"];</code>
     * @return The bytes for filename.
     */
    com.google.protobuf.ByteString
        getFilenameBytes();

    /**
     * <pre>
     * Free-form key/value pairs for caller-defined attributes (checksums,
     * alt text, source system, …).
     * </pre>
     *
     * <code>map&lt;string, string&gt; custom = 4 [json_name = "custom"];</code>
     */
    int getCustomCount();
    /**
     * <pre>
     * Free-form key/value pairs for caller-defined attributes (checksums,
     * alt text, source system, …).
     * </pre>
     *
     * <code>map&lt;string, string&gt; custom = 4 [json_name = "custom"];</code>
     */
    boolean containsCustom(
        java.lang.String key);
    /**
     * Use {@link #getCustomMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getCustom();
    /**
     * <pre>
     * Free-form key/value pairs for caller-defined attributes (checksums,
     * alt text, source system, …).
     * </pre>
     *
     * <code>map&lt;string, string&gt; custom = 4 [json_name = "custom"];</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getCustomMap();
    /**
     * <pre>
     * Free-form key/value pairs for caller-defined attributes (checksums,
     * alt text, source system, …).
     * </pre>
     *
     * <code>map&lt;string, string&gt; custom = 4 [json_name = "custom"];</code>
     */
    /* nullable */
java.lang.String getCustomOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue);
    /**
     * <pre>
     * Free-form key/value pairs for caller-defined attributes (checksums,
     * alt text, source system, …).
     * </pre>
     *
     * <code>map&lt;string, string&gt; custom = 4 [json_name = "custom"];</code>
     */
    java.lang.String getCustomOrThrow(
        java.lang.String key);
  }
  /**
   * <pre>
   * Technical descriptors of the referenced file. Producers SHOULD populate
   * every field they know; consumers MUST tolerate missing values
   * (e.g. legacy records, third-party uploads without inspection).
   * </pre>
   *
   * Protobuf type {@code io.altessa.type.v1.FileRef.Metadata}
   */
  public static final class Metadata extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.altessa.type.v1.FileRef.Metadata)
      MetadataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Metadata.newBuilder() to construct.
    private Metadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Metadata() {
      mimeType_ = "";
      filename_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Metadata();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.altessa.type.v1.FileRefProto.internal_static_io_altessa_type_v1_FileRef_Metadata_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetCustom();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.altessa.type.v1.FileRefProto.internal_static_io_altessa_type_v1_FileRef_Metadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.altessa.type.v1.FileRef.Metadata.class, io.altessa.type.v1.FileRef.Metadata.Builder.class);
    }

    public static final int MIME_TYPE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object mimeType_ = "";
    /**
     * <pre>
     * IANA media type of the file content (RFC 6838), e.g. "image/png",
     * "application/pdf", "text/plain".
     * </pre>
     *
     * <code>string mime_type = 1 [json_name = "mimeType"];</code>
     * @return The mimeType.
     */
    @java.lang.Override
    public java.lang.String getMimeType() {
      java.lang.Object ref = mimeType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mimeType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * IANA media type of the file content (RFC 6838), e.g. "image/png",
     * "application/pdf", "text/plain".
     * </pre>
     *
     * <code>string mime_type = 1 [json_name = "mimeType"];</code>
     * @return The bytes for mimeType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMimeTypeBytes() {
      java.lang.Object ref = mimeType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mimeType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIZE_BYTES_FIELD_NUMBER = 2;
    private long sizeBytes_ = 0L;
    /**
     * <pre>
     * Size of the file in bytes. Negative values are not meaningful.
     * </pre>
     *
     * <code>int64 size_bytes = 2 [json_name = "sizeBytes"];</code>
     * @return The sizeBytes.
     */
    @java.lang.Override
    public long getSizeBytes() {
      return sizeBytes_;
    }

    public static final int FILENAME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object filename_ = "";
    /**
     * <pre>
     * Original filename including extension, e.g. "report.pdf",
     * "photo.jpg". Not guaranteed to be unique within the storage backend.
     * </pre>
     *
     * <code>string filename = 3 [json_name = "filename"];</code>
     * @return The filename.
     */
    @java.lang.Override
    public java.lang.String getFilename() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filename_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Original filename including extension, e.g. "report.pdf",
     * "photo.jpg". Not guaranteed to be unique within the storage backend.
     * </pre>
     *
     * <code>string filename = 3 [json_name = "filename"];</code>
     * @return The bytes for filename.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFilenameBytes() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CUSTOM_FIELD_NUMBER = 4;
    private static final class CustomDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  io.altessa.type.v1.FileRefProto.internal_static_io_altessa_type_v1_FileRef_Metadata_CustomEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> custom_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetCustom() {
      if (custom_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            CustomDefaultEntryHolder.defaultEntry);
      }
      return custom_;
    }
    public int getCustomCount() {
      return internalGetCustom().getMap().size();
    }
    /**
     * <pre>
     * Free-form key/value pairs for caller-defined attributes (checksums,
     * alt text, source system, …).
     * </pre>
     *
     * <code>map&lt;string, string&gt; custom = 4 [json_name = "custom"];</code>
     */
    @java.lang.Override
    public boolean containsCustom(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetCustom().getMap().containsKey(key);
    }
    /**
     * Use {@link #getCustomMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getCustom() {
      return getCustomMap();
    }
    /**
     * <pre>
     * Free-form key/value pairs for caller-defined attributes (checksums,
     * alt text, source system, …).
     * </pre>
     *
     * <code>map&lt;string, string&gt; custom = 4 [json_name = "custom"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getCustomMap() {
      return internalGetCustom().getMap();
    }
    /**
     * <pre>
     * Free-form key/value pairs for caller-defined attributes (checksums,
     * alt text, source system, …).
     * </pre>
     *
     * <code>map&lt;string, string&gt; custom = 4 [json_name = "custom"];</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getCustomOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetCustom().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Free-form key/value pairs for caller-defined attributes (checksums,
     * alt text, source system, …).
     * </pre>
     *
     * <code>map&lt;string, string&gt; custom = 4 [json_name = "custom"];</code>
     */
    @java.lang.Override
    public java.lang.String getCustomOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetCustom().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mimeType_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mimeType_);
      }
      if (sizeBytes_ != 0L) {
        output.writeInt64(2, sizeBytes_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(filename_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, filename_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetCustom(),
          CustomDefaultEntryHolder.defaultEntry,
          4);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mimeType_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mimeType_);
      }
      if (sizeBytes_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, sizeBytes_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(filename_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, filename_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetCustom().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        custom__ = CustomDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, custom__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.altessa.type.v1.FileRef.Metadata)) {
        return super.equals(obj);
      }
      io.altessa.type.v1.FileRef.Metadata other = (io.altessa.type.v1.FileRef.Metadata) obj;

      if (!getMimeType()
          .equals(other.getMimeType())) return false;
      if (getSizeBytes()
          != other.getSizeBytes()) return false;
      if (!getFilename()
          .equals(other.getFilename())) return false;
      if (!internalGetCustom().equals(
          other.internalGetCustom())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MIME_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMimeType().hashCode();
      hash = (37 * hash) + SIZE_BYTES_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSizeBytes());
      hash = (37 * hash) + FILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getFilename().hashCode();
      if (!internalGetCustom().getMap().isEmpty()) {
        hash = (37 * hash) + CUSTOM_FIELD_NUMBER;
        hash = (53 * hash) + internalGetCustom().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.altessa.type.v1.FileRef.Metadata parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.altessa.type.v1.FileRef.Metadata parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.altessa.type.v1.FileRef.Metadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.altessa.type.v1.FileRef.Metadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.altessa.type.v1.FileRef.Metadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.altessa.type.v1.FileRef.Metadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.altessa.type.v1.FileRef.Metadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.altessa.type.v1.FileRef.Metadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.altessa.type.v1.FileRef.Metadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.altessa.type.v1.FileRef.Metadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.altessa.type.v1.FileRef.Metadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.altessa.type.v1.FileRef.Metadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.altessa.type.v1.FileRef.Metadata prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Technical descriptors of the referenced file. Producers SHOULD populate
     * every field they know; consumers MUST tolerate missing values
     * (e.g. legacy records, third-party uploads without inspection).
     * </pre>
     *
     * Protobuf type {@code io.altessa.type.v1.FileRef.Metadata}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.altessa.type.v1.FileRef.Metadata)
        io.altessa.type.v1.FileRef.MetadataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.altessa.type.v1.FileRefProto.internal_static_io_altessa_type_v1_FileRef_Metadata_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetCustom();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetMutableCustom();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.altessa.type.v1.FileRefProto.internal_static_io_altessa_type_v1_FileRef_Metadata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.altessa.type.v1.FileRef.Metadata.class, io.altessa.type.v1.FileRef.Metadata.Builder.class);
      }

      // Construct using io.altessa.type.v1.FileRef.Metadata.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        mimeType_ = "";
        sizeBytes_ = 0L;
        filename_ = "";
        internalGetMutableCustom().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.altessa.type.v1.FileRefProto.internal_static_io_altessa_type_v1_FileRef_Metadata_descriptor;
      }

      @java.lang.Override
      public io.altessa.type.v1.FileRef.Metadata getDefaultInstanceForType() {
        return io.altessa.type.v1.FileRef.Metadata.getDefaultInstance();
      }

      @java.lang.Override
      public io.altessa.type.v1.FileRef.Metadata build() {
        io.altessa.type.v1.FileRef.Metadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.altessa.type.v1.FileRef.Metadata buildPartial() {
        io.altessa.type.v1.FileRef.Metadata result = new io.altessa.type.v1.FileRef.Metadata(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(io.altessa.type.v1.FileRef.Metadata result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.mimeType_ = mimeType_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.sizeBytes_ = sizeBytes_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.filename_ = filename_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.custom_ = internalGetCustom();
          result.custom_.makeImmutable();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.altessa.type.v1.FileRef.Metadata) {
          return mergeFrom((io.altessa.type.v1.FileRef.Metadata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.altessa.type.v1.FileRef.Metadata other) {
        if (other == io.altessa.type.v1.FileRef.Metadata.getDefaultInstance()) return this;
        if (!other.getMimeType().isEmpty()) {
          mimeType_ = other.mimeType_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getSizeBytes() != 0L) {
          setSizeBytes(other.getSizeBytes());
        }
        if (!other.getFilename().isEmpty()) {
          filename_ = other.filename_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        internalGetMutableCustom().mergeFrom(
            other.internalGetCustom());
        bitField0_ |= 0x00000008;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                mimeType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                sizeBytes_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                filename_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                custom__ = input.readMessage(
                    CustomDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableCustom().getMutableMap().put(
                    custom__.getKey(), custom__.getValue());
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object mimeType_ = "";
      /**
       * <pre>
       * IANA media type of the file content (RFC 6838), e.g. "image/png",
       * "application/pdf", "text/plain".
       * </pre>
       *
       * <code>string mime_type = 1 [json_name = "mimeType"];</code>
       * @return The mimeType.
       */
      public java.lang.String getMimeType() {
        java.lang.Object ref = mimeType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mimeType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * IANA media type of the file content (RFC 6838), e.g. "image/png",
       * "application/pdf", "text/plain".
       * </pre>
       *
       * <code>string mime_type = 1 [json_name = "mimeType"];</code>
       * @return The bytes for mimeType.
       */
      public com.google.protobuf.ByteString
          getMimeTypeBytes() {
        java.lang.Object ref = mimeType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mimeType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * IANA media type of the file content (RFC 6838), e.g. "image/png",
       * "application/pdf", "text/plain".
       * </pre>
       *
       * <code>string mime_type = 1 [json_name = "mimeType"];</code>
       * @param value The mimeType to set.
       * @return This builder for chaining.
       */
      public Builder setMimeType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        mimeType_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * IANA media type of the file content (RFC 6838), e.g. "image/png",
       * "application/pdf", "text/plain".
       * </pre>
       *
       * <code>string mime_type = 1 [json_name = "mimeType"];</code>
       * @return This builder for chaining.
       */
      public Builder clearMimeType() {
        mimeType_ = getDefaultInstance().getMimeType();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * IANA media type of the file content (RFC 6838), e.g. "image/png",
       * "application/pdf", "text/plain".
       * </pre>
       *
       * <code>string mime_type = 1 [json_name = "mimeType"];</code>
       * @param value The bytes for mimeType to set.
       * @return This builder for chaining.
       */
      public Builder setMimeTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        mimeType_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private long sizeBytes_ ;
      /**
       * <pre>
       * Size of the file in bytes. Negative values are not meaningful.
       * </pre>
       *
       * <code>int64 size_bytes = 2 [json_name = "sizeBytes"];</code>
       * @return The sizeBytes.
       */
      @java.lang.Override
      public long getSizeBytes() {
        return sizeBytes_;
      }
      /**
       * <pre>
       * Size of the file in bytes. Negative values are not meaningful.
       * </pre>
       *
       * <code>int64 size_bytes = 2 [json_name = "sizeBytes"];</code>
       * @param value The sizeBytes to set.
       * @return This builder for chaining.
       */
      public Builder setSizeBytes(long value) {
        
        sizeBytes_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Size of the file in bytes. Negative values are not meaningful.
       * </pre>
       *
       * <code>int64 size_bytes = 2 [json_name = "sizeBytes"];</code>
       * @return This builder for chaining.
       */
      public Builder clearSizeBytes() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sizeBytes_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object filename_ = "";
      /**
       * <pre>
       * Original filename including extension, e.g. "report.pdf",
       * "photo.jpg". Not guaranteed to be unique within the storage backend.
       * </pre>
       *
       * <code>string filename = 3 [json_name = "filename"];</code>
       * @return The filename.
       */
      public java.lang.String getFilename() {
        java.lang.Object ref = filename_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          filename_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Original filename including extension, e.g. "report.pdf",
       * "photo.jpg". Not guaranteed to be unique within the storage backend.
       * </pre>
       *
       * <code>string filename = 3 [json_name = "filename"];</code>
       * @return The bytes for filename.
       */
      public com.google.protobuf.ByteString
          getFilenameBytes() {
        java.lang.Object ref = filename_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filename_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Original filename including extension, e.g. "report.pdf",
       * "photo.jpg". Not guaranteed to be unique within the storage backend.
       * </pre>
       *
       * <code>string filename = 3 [json_name = "filename"];</code>
       * @param value The filename to set.
       * @return This builder for chaining.
       */
      public Builder setFilename(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        filename_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Original filename including extension, e.g. "report.pdf",
       * "photo.jpg". Not guaranteed to be unique within the storage backend.
       * </pre>
       *
       * <code>string filename = 3 [json_name = "filename"];</code>
       * @return This builder for chaining.
       */
      public Builder clearFilename() {
        filename_ = getDefaultInstance().getFilename();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Original filename including extension, e.g. "report.pdf",
       * "photo.jpg". Not guaranteed to be unique within the storage backend.
       * </pre>
       *
       * <code>string filename = 3 [json_name = "filename"];</code>
       * @param value The bytes for filename to set.
       * @return This builder for chaining.
       */
      public Builder setFilenameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        filename_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> custom_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetCustom() {
        if (custom_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              CustomDefaultEntryHolder.defaultEntry);
        }
        return custom_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetMutableCustom() {
        if (custom_ == null) {
          custom_ = com.google.protobuf.MapField.newMapField(
              CustomDefaultEntryHolder.defaultEntry);
        }
        if (!custom_.isMutable()) {
          custom_ = custom_.copy();
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return custom_;
      }
      public int getCustomCount() {
        return internalGetCustom().getMap().size();
      }
      /**
       * <pre>
       * Free-form key/value pairs for caller-defined attributes (checksums,
       * alt text, source system, …).
       * </pre>
       *
       * <code>map&lt;string, string&gt; custom = 4 [json_name = "custom"];</code>
       */
      @java.lang.Override
      public boolean containsCustom(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetCustom().getMap().containsKey(key);
      }
      /**
       * Use {@link #getCustomMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getCustom() {
        return getCustomMap();
      }
      /**
       * <pre>
       * Free-form key/value pairs for caller-defined attributes (checksums,
       * alt text, source system, …).
       * </pre>
       *
       * <code>map&lt;string, string&gt; custom = 4 [json_name = "custom"];</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, java.lang.String> getCustomMap() {
        return internalGetCustom().getMap();
      }
      /**
       * <pre>
       * Free-form key/value pairs for caller-defined attributes (checksums,
       * alt text, source system, …).
       * </pre>
       *
       * <code>map&lt;string, string&gt; custom = 4 [json_name = "custom"];</code>
       */
      @java.lang.Override
      public /* nullable */
java.lang.String getCustomOrDefault(
          java.lang.String key,
          /* nullable */
java.lang.String defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetCustom().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * Free-form key/value pairs for caller-defined attributes (checksums,
       * alt text, source system, …).
       * </pre>
       *
       * <code>map&lt;string, string&gt; custom = 4 [json_name = "custom"];</code>
       */
      @java.lang.Override
      public java.lang.String getCustomOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetCustom().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearCustom() {
        bitField0_ = (bitField0_ & ~0x00000008);
        internalGetMutableCustom().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * Free-form key/value pairs for caller-defined attributes (checksums,
       * alt text, source system, …).
       * </pre>
       *
       * <code>map&lt;string, string&gt; custom = 4 [json_name = "custom"];</code>
       */
      public Builder removeCustom(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableCustom().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
          getMutableCustom() {
        bitField0_ |= 0x00000008;
        return internalGetMutableCustom().getMutableMap();
      }
      /**
       * <pre>
       * Free-form key/value pairs for caller-defined attributes (checksums,
       * alt text, source system, …).
       * </pre>
       *
       * <code>map&lt;string, string&gt; custom = 4 [json_name = "custom"];</code>
       */
      public Builder putCustom(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableCustom().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <pre>
       * Free-form key/value pairs for caller-defined attributes (checksums,
       * alt text, source system, …).
       * </pre>
       *
       * <code>map&lt;string, string&gt; custom = 4 [json_name = "custom"];</code>
       */
      public Builder putAllCustom(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableCustom().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000008;
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.altessa.type.v1.FileRef.Metadata)
    }

    // @@protoc_insertion_point(class_scope:io.altessa.type.v1.FileRef.Metadata)
    private static final io.altessa.type.v1.FileRef.Metadata DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.altessa.type.v1.FileRef.Metadata();
    }

    public static io.altessa.type.v1.FileRef.Metadata getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Metadata>
        PARSER = new com.google.protobuf.AbstractParser<Metadata>() {
      @java.lang.Override
      public Metadata parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Metadata> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Metadata> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.altessa.type.v1.FileRef.Metadata getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int URL_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object url_ = "";
  /**
   * <pre>
   * URL for accessing the file. MAY be permanent or a time-limited signed
   * URL — readers must not cache it beyond the lifetime granted by the
   * issuer.
   * </pre>
   *
   * <code>string url = 1 [json_name = "url", (.google.api.field_behavior) = REQUIRED];</code>
   * @return The url.
   */
  @java.lang.Override
  public java.lang.String getUrl() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      url_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * URL for accessing the file. MAY be permanent or a time-limited signed
   * URL — readers must not cache it beyond the lifetime granted by the
   * issuer.
   * </pre>
   *
   * <code>string url = 1 [json_name = "url", (.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for url.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUrlBytes() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      url_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <pre>
   * Stable identifier of the file in the issuing system. Opaque to
   * consumers; suitable for re-requesting a fresh URL. Assigned at
   * upload time and never changes afterwards.
   * </pre>
   *
   * <code>string id = 2 [json_name = "id", (.google.api.field_behavior) = IDENTIFIER];</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Stable identifier of the file in the issuing system. Opaque to
   * consumers; suitable for re-requesting a fresh URL. Assigned at
   * upload time and never changes afterwards.
   * </pre>
   *
   * <code>string id = 2 [json_name = "id", (.google.api.field_behavior) = IDENTIFIER];</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METADATA_FIELD_NUMBER = 3;
  private io.altessa.type.v1.FileRef.Metadata metadata_;
  /**
   * <pre>
   * File metadata, when known.
   * </pre>
   *
   * <code>.io.altessa.type.v1.FileRef.Metadata metadata = 3 [json_name = "metadata"];</code>
   * @return Whether the metadata field is set.
   */
  @java.lang.Override
  public boolean hasMetadata() {
    return metadata_ != null;
  }
  /**
   * <pre>
   * File metadata, when known.
   * </pre>
   *
   * <code>.io.altessa.type.v1.FileRef.Metadata metadata = 3 [json_name = "metadata"];</code>
   * @return The metadata.
   */
  @java.lang.Override
  public io.altessa.type.v1.FileRef.Metadata getMetadata() {
    return metadata_ == null ? io.altessa.type.v1.FileRef.Metadata.getDefaultInstance() : metadata_;
  }
  /**
   * <pre>
   * File metadata, when known.
   * </pre>
   *
   * <code>.io.altessa.type.v1.FileRef.Metadata metadata = 3 [json_name = "metadata"];</code>
   */
  @java.lang.Override
  public io.altessa.type.v1.FileRef.MetadataOrBuilder getMetadataOrBuilder() {
    return metadata_ == null ? io.altessa.type.v1.FileRef.Metadata.getDefaultInstance() : metadata_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(url_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, url_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, id_);
    }
    if (metadata_ != null) {
      output.writeMessage(3, getMetadata());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(url_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, url_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, id_);
    }
    if (metadata_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getMetadata());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.altessa.type.v1.FileRef)) {
      return super.equals(obj);
    }
    io.altessa.type.v1.FileRef other = (io.altessa.type.v1.FileRef) obj;

    if (!getUrl()
        .equals(other.getUrl())) return false;
    if (!getId()
        .equals(other.getId())) return false;
    if (hasMetadata() != other.hasMetadata()) return false;
    if (hasMetadata()) {
      if (!getMetadata()
          .equals(other.getMetadata())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + URL_FIELD_NUMBER;
    hash = (53 * hash) + getUrl().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (hasMetadata()) {
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetadata().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.altessa.type.v1.FileRef parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.altessa.type.v1.FileRef parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.altessa.type.v1.FileRef parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.altessa.type.v1.FileRef parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.altessa.type.v1.FileRef parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.altessa.type.v1.FileRef parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.altessa.type.v1.FileRef parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.altessa.type.v1.FileRef parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.altessa.type.v1.FileRef parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.altessa.type.v1.FileRef parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.altessa.type.v1.FileRef parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.altessa.type.v1.FileRef parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.altessa.type.v1.FileRef prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Reference to a file held in an external system (object storage, CDN, …).
   * Carries enough information to retrieve the file and describe it for
   * display. The schema is intentionally storage-agnostic — neither bucket
   * nor backend is encoded here.
   * </pre>
   *
   * Protobuf type {@code io.altessa.type.v1.FileRef}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.altessa.type.v1.FileRef)
      io.altessa.type.v1.FileRefOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.altessa.type.v1.FileRefProto.internal_static_io_altessa_type_v1_FileRef_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.altessa.type.v1.FileRefProto.internal_static_io_altessa_type_v1_FileRef_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.altessa.type.v1.FileRef.class, io.altessa.type.v1.FileRef.Builder.class);
    }

    // Construct using io.altessa.type.v1.FileRef.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      url_ = "";
      id_ = "";
      metadata_ = null;
      if (metadataBuilder_ != null) {
        metadataBuilder_.dispose();
        metadataBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.altessa.type.v1.FileRefProto.internal_static_io_altessa_type_v1_FileRef_descriptor;
    }

    @java.lang.Override
    public io.altessa.type.v1.FileRef getDefaultInstanceForType() {
      return io.altessa.type.v1.FileRef.getDefaultInstance();
    }

    @java.lang.Override
    public io.altessa.type.v1.FileRef build() {
      io.altessa.type.v1.FileRef result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.altessa.type.v1.FileRef buildPartial() {
      io.altessa.type.v1.FileRef result = new io.altessa.type.v1.FileRef(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.altessa.type.v1.FileRef result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.url_ = url_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.metadata_ = metadataBuilder_ == null
            ? metadata_
            : metadataBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.altessa.type.v1.FileRef) {
        return mergeFrom((io.altessa.type.v1.FileRef)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.altessa.type.v1.FileRef other) {
      if (other == io.altessa.type.v1.FileRef.getDefaultInstance()) return this;
      if (!other.getUrl().isEmpty()) {
        url_ = other.url_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasMetadata()) {
        mergeMetadata(other.getMetadata());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              url_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getMetadataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object url_ = "";
    /**
     * <pre>
     * URL for accessing the file. MAY be permanent or a time-limited signed
     * URL — readers must not cache it beyond the lifetime granted by the
     * issuer.
     * </pre>
     *
     * <code>string url = 1 [json_name = "url", (.google.api.field_behavior) = REQUIRED];</code>
     * @return The url.
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * URL for accessing the file. MAY be permanent or a time-limited signed
     * URL — readers must not cache it beyond the lifetime granted by the
     * issuer.
     * </pre>
     *
     * <code>string url = 1 [json_name = "url", (.google.api.field_behavior) = REQUIRED];</code>
     * @return The bytes for url.
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * URL for accessing the file. MAY be permanent or a time-limited signed
     * URL — readers must not cache it beyond the lifetime granted by the
     * issuer.
     * </pre>
     *
     * <code>string url = 1 [json_name = "url", (.google.api.field_behavior) = REQUIRED];</code>
     * @param value The url to set.
     * @return This builder for chaining.
     */
    public Builder setUrl(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      url_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * URL for accessing the file. MAY be permanent or a time-limited signed
     * URL — readers must not cache it beyond the lifetime granted by the
     * issuer.
     * </pre>
     *
     * <code>string url = 1 [json_name = "url", (.google.api.field_behavior) = REQUIRED];</code>
     * @return This builder for chaining.
     */
    public Builder clearUrl() {
      url_ = getDefaultInstance().getUrl();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * URL for accessing the file. MAY be permanent or a time-limited signed
     * URL — readers must not cache it beyond the lifetime granted by the
     * issuer.
     * </pre>
     *
     * <code>string url = 1 [json_name = "url", (.google.api.field_behavior) = REQUIRED];</code>
     * @param value The bytes for url to set.
     * @return This builder for chaining.
     */
    public Builder setUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      url_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <pre>
     * Stable identifier of the file in the issuing system. Opaque to
     * consumers; suitable for re-requesting a fresh URL. Assigned at
     * upload time and never changes afterwards.
     * </pre>
     *
     * <code>string id = 2 [json_name = "id", (.google.api.field_behavior) = IDENTIFIER];</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Stable identifier of the file in the issuing system. Opaque to
     * consumers; suitable for re-requesting a fresh URL. Assigned at
     * upload time and never changes afterwards.
     * </pre>
     *
     * <code>string id = 2 [json_name = "id", (.google.api.field_behavior) = IDENTIFIER];</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Stable identifier of the file in the issuing system. Opaque to
     * consumers; suitable for re-requesting a fresh URL. Assigned at
     * upload time and never changes afterwards.
     * </pre>
     *
     * <code>string id = 2 [json_name = "id", (.google.api.field_behavior) = IDENTIFIER];</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Stable identifier of the file in the issuing system. Opaque to
     * consumers; suitable for re-requesting a fresh URL. Assigned at
     * upload time and never changes afterwards.
     * </pre>
     *
     * <code>string id = 2 [json_name = "id", (.google.api.field_behavior) = IDENTIFIER];</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Stable identifier of the file in the issuing system. Opaque to
     * consumers; suitable for re-requesting a fresh URL. Assigned at
     * upload time and never changes afterwards.
     * </pre>
     *
     * <code>string id = 2 [json_name = "id", (.google.api.field_behavior) = IDENTIFIER];</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private io.altessa.type.v1.FileRef.Metadata metadata_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.altessa.type.v1.FileRef.Metadata, io.altessa.type.v1.FileRef.Metadata.Builder, io.altessa.type.v1.FileRef.MetadataOrBuilder> metadataBuilder_;
    /**
     * <pre>
     * File metadata, when known.
     * </pre>
     *
     * <code>.io.altessa.type.v1.FileRef.Metadata metadata = 3 [json_name = "metadata"];</code>
     * @return Whether the metadata field is set.
     */
    public boolean hasMetadata() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * File metadata, when known.
     * </pre>
     *
     * <code>.io.altessa.type.v1.FileRef.Metadata metadata = 3 [json_name = "metadata"];</code>
     * @return The metadata.
     */
    public io.altessa.type.v1.FileRef.Metadata getMetadata() {
      if (metadataBuilder_ == null) {
        return metadata_ == null ? io.altessa.type.v1.FileRef.Metadata.getDefaultInstance() : metadata_;
      } else {
        return metadataBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * File metadata, when known.
     * </pre>
     *
     * <code>.io.altessa.type.v1.FileRef.Metadata metadata = 3 [json_name = "metadata"];</code>
     */
    public Builder setMetadata(io.altessa.type.v1.FileRef.Metadata value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metadata_ = value;
      } else {
        metadataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * File metadata, when known.
     * </pre>
     *
     * <code>.io.altessa.type.v1.FileRef.Metadata metadata = 3 [json_name = "metadata"];</code>
     */
    public Builder setMetadata(
        io.altessa.type.v1.FileRef.Metadata.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        metadata_ = builderForValue.build();
      } else {
        metadataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * File metadata, when known.
     * </pre>
     *
     * <code>.io.altessa.type.v1.FileRef.Metadata metadata = 3 [json_name = "metadata"];</code>
     */
    public Builder mergeMetadata(io.altessa.type.v1.FileRef.Metadata value) {
      if (metadataBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          metadata_ != null &&
          metadata_ != io.altessa.type.v1.FileRef.Metadata.getDefaultInstance()) {
          getMetadataBuilder().mergeFrom(value);
        } else {
          metadata_ = value;
        }
      } else {
        metadataBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * File metadata, when known.
     * </pre>
     *
     * <code>.io.altessa.type.v1.FileRef.Metadata metadata = 3 [json_name = "metadata"];</code>
     */
    public Builder clearMetadata() {
      bitField0_ = (bitField0_ & ~0x00000004);
      metadata_ = null;
      if (metadataBuilder_ != null) {
        metadataBuilder_.dispose();
        metadataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * File metadata, when known.
     * </pre>
     *
     * <code>.io.altessa.type.v1.FileRef.Metadata metadata = 3 [json_name = "metadata"];</code>
     */
    public io.altessa.type.v1.FileRef.Metadata.Builder getMetadataBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getMetadataFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * File metadata, when known.
     * </pre>
     *
     * <code>.io.altessa.type.v1.FileRef.Metadata metadata = 3 [json_name = "metadata"];</code>
     */
    public io.altessa.type.v1.FileRef.MetadataOrBuilder getMetadataOrBuilder() {
      if (metadataBuilder_ != null) {
        return metadataBuilder_.getMessageOrBuilder();
      } else {
        return metadata_ == null ?
            io.altessa.type.v1.FileRef.Metadata.getDefaultInstance() : metadata_;
      }
    }
    /**
     * <pre>
     * File metadata, when known.
     * </pre>
     *
     * <code>.io.altessa.type.v1.FileRef.Metadata metadata = 3 [json_name = "metadata"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.altessa.type.v1.FileRef.Metadata, io.altessa.type.v1.FileRef.Metadata.Builder, io.altessa.type.v1.FileRef.MetadataOrBuilder> 
        getMetadataFieldBuilder() {
      if (metadataBuilder_ == null) {
        metadataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.altessa.type.v1.FileRef.Metadata, io.altessa.type.v1.FileRef.Metadata.Builder, io.altessa.type.v1.FileRef.MetadataOrBuilder>(
                getMetadata(),
                getParentForChildren(),
                isClean());
        metadata_ = null;
      }
      return metadataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.altessa.type.v1.FileRef)
  }

  // @@protoc_insertion_point(class_scope:io.altessa.type.v1.FileRef)
  private static final io.altessa.type.v1.FileRef DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.altessa.type.v1.FileRef();
  }

  public static io.altessa.type.v1.FileRef getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FileRef>
      PARSER = new com.google.protobuf.AbstractParser<FileRef>() {
    @java.lang.Override
    public FileRef parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FileRef> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FileRef> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.altessa.type.v1.FileRef getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

