// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: type/v1/gender.proto

package io.altessa.type.v1;

public final class GenderOuterClass {
  private GenderOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024type/v1/gender.proto\022\022io.altessa.type." +
      "v1*D\n\006Gender\022\026\n\022GENDER_UNSPECIFIED\020\000\022\017\n\013" +
      "GENDER_MALE\020\001\022\021\n\rGENDER_FEMALE\020\002BH\n\022io.a" +
      "ltessa.type.v1P\001Z0github.com/altessa-s/p" +
      "roto-gen-go/type/v1;typev1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
