// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/altessa/type/v1/gender.proto

package io.altessa.type.v1;

public final class GenderProto {
  private GenderProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037io/altessa/type/v1/gender.proto\022\022io.al" +
      "tessa.type.v1*D\n\006Gender\022\026\n\022GENDER_UNSPEC" +
      "IFIED\020\000\022\017\n\013GENDER_MALE\020\001\022\021\n\rGENDER_FEMAL" +
      "E\020\002B`\n\022io.altessa.type.v1B\013GenderProtoP\001" +
      "Z;github.com/altessa-s/proto-gen-go/io/a" +
      "ltessa/type/v1;typev1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
