// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: type/v1/label.proto

package io.altessa.type.v1;

public final class LabelOuterClass {
  private LabelOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_altessa_type_v1_Label_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_altessa_type_v1_Label_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023type/v1/label.proto\022\022io.altessa.type.v" +
      "1\032\037google/api/field_behavior.proto\032\027goog" +
      "le/type/color.proto\"d\n\005Label\022\026\n\002id\030\001 \001(\t" +
      "B\006\340A\002\340A\005R\002id\022\031\n\005value\030\002 \001(\tB\003\340A\002R\005value\022" +
      "(\n\005color\030\003 \001(\0132\022.google.type.ColorR\005colo" +
      "rBH\n\022io.altessa.type.v1P\001Z0github.com/al" +
      "tessa-s/proto-gen-go/type/v1;typev1b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.type.ColorProto.getDescriptor(),
        });
    internal_static_io_altessa_type_v1_Label_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_altessa_type_v1_Label_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_altessa_type_v1_Label_descriptor,
        new java.lang.String[] { "Id", "Value", "Color", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.type.ColorProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
