// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: type/v1/location_privacy.proto

package io.altessa.type.v1;

public final class LocationPrivacyOuterClass {
  private LocationPrivacyOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036type/v1/location_privacy.proto\022\022io.alt" +
      "essa.type.v1*\331\001\n\017LocationPrivacy\022 \n\034LOCA" +
      "TION_PRIVACY_UNSPECIFIED\020\000\022\030\n\024LOCATION_P" +
      "RIVACY_OFF\020\001\022\034\n\030LOCATION_PRIVACY_PRIVATE" +
      "\020\002\022 \n\034LOCATION_PRIVACY_PUBLIC_CITY\020\003\022\'\n#" +
      "LOCATION_PRIVACY_PUBLIC_APPROXIMATE\020\004\022!\n" +
      "\035LOCATION_PRIVACY_PUBLIC_EXACT\020\005BH\n\022io.a" +
      "ltessa.type.v1P\001Z0github.com/altessa-s/p" +
      "roto-gen-go/type/v1;typev1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
