// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: type/v1/money_range.proto

package io.altessa.type.v1;

public interface MoneyRangeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.altessa.type.v1.MoneyRange)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Lower bound, inclusive.
   * </pre>
   *
   * <code>.google.type.Money min = 1 [json_name = "min", (.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the min field is set.
   */
  boolean hasMin();
  /**
   * <pre>
   * Lower bound, inclusive.
   * </pre>
   *
   * <code>.google.type.Money min = 1 [json_name = "min", (.google.api.field_behavior) = REQUIRED];</code>
   * @return The min.
   */
  com.google.type.Money getMin();
  /**
   * <pre>
   * Lower bound, inclusive.
   * </pre>
   *
   * <code>.google.type.Money min = 1 [json_name = "min", (.google.api.field_behavior) = REQUIRED];</code>
   */
  com.google.type.MoneyOrBuilder getMinOrBuilder();

  /**
   * <pre>
   * Upper bound, inclusive. MUST be in the same currency as `min` and
   * greater than or equal to `min`.
   * </pre>
   *
   * <code>.google.type.Money max = 2 [json_name = "max", (.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the max field is set.
   */
  boolean hasMax();
  /**
   * <pre>
   * Upper bound, inclusive. MUST be in the same currency as `min` and
   * greater than or equal to `min`.
   * </pre>
   *
   * <code>.google.type.Money max = 2 [json_name = "max", (.google.api.field_behavior) = REQUIRED];</code>
   * @return The max.
   */
  com.google.type.Money getMax();
  /**
   * <pre>
   * Upper bound, inclusive. MUST be in the same currency as `min` and
   * greater than or equal to `min`.
   * </pre>
   *
   * <code>.google.type.Money max = 2 [json_name = "max", (.google.api.field_behavior) = REQUIRED];</code>
   */
  com.google.type.MoneyOrBuilder getMaxOrBuilder();
}
