// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/altessa/type/v1/money_range.proto

package io.altessa.type.v1;

public final class MoneyRangeProto {
  private MoneyRangeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_altessa_type_v1_MoneyRange_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_altessa_type_v1_MoneyRange_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$io/altessa/type/v1/money_range.proto\022\022" +
      "io.altessa.type.v1\032\037google/api/field_beh" +
      "avior.proto\032\027google/type/money.proto\"b\n\n" +
      "MoneyRange\022)\n\003min\030\001 \001(\0132\022.google.type.Mo" +
      "neyB\003\340A\002R\003min\022)\n\003max\030\002 \001(\0132\022.google.type" +
      ".MoneyB\003\340A\002R\003maxBd\n\022io.altessa.type.v1B\017" +
      "MoneyRangeProtoP\001Z;github.com/altessa-s/" +
      "proto-gen-go/io/altessa/type/v1;typev1b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.type.MoneyProto.getDescriptor(),
        });
    internal_static_io_altessa_type_v1_MoneyRange_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_altessa_type_v1_MoneyRange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_altessa_type_v1_MoneyRange_descriptor,
        new java.lang.String[] { "Min", "Max", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.type.MoneyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
