// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: type/v1/organization_type.proto

package io.altessa.type.v1;

/**
 * <pre>
 * Legal form of an organization at a coarse level. Use this when the
 * distinction "natural person doing business" vs "registered legal entity"
 * is enough; jurisdiction-specific subtypes (ИП vs самозанятый, LLC vs
 * C-corp, …) belong in a domain-specific schema.
 * Stability (AIP-180): closed and frozen at v1. New values are NOT
 * expected; jurisdiction-specific subtypes are added in domain
 * schemas, not here.
 * </pre>
 *
 * Protobuf enum {@code io.altessa.type.v1.OrganizationType}
 */
public enum OrganizationType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Sentinel default. Treat as "not provided" rather than as a value.
   * </pre>
   *
   * <code>ORGANIZATION_TYPE_UNSPECIFIED = 0;</code>
   */
  ORGANIZATION_TYPE_UNSPECIFIED(0),
  /**
   * <pre>
   * Natural person operating as a sole proprietor / individual entrepreneur
   * (e.g. ИП in RU, sole trader in UK, sole proprietorship in US).
   * </pre>
   *
   * <code>ORGANIZATION_TYPE_INDIVIDUAL = 1;</code>
   */
  ORGANIZATION_TYPE_INDIVIDUAL(1),
  /**
   * <pre>
   * Registered legal entity distinct from its owners (e.g. ООО / АО in RU,
   * LLC / Inc. in US, GmbH / AG in DE).
   * </pre>
   *
   * <code>ORGANIZATION_TYPE_ORGANIZATION = 2;</code>
   */
  ORGANIZATION_TYPE_ORGANIZATION(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * Sentinel default. Treat as "not provided" rather than as a value.
   * </pre>
   *
   * <code>ORGANIZATION_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int ORGANIZATION_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * Natural person operating as a sole proprietor / individual entrepreneur
   * (e.g. ИП in RU, sole trader in UK, sole proprietorship in US).
   * </pre>
   *
   * <code>ORGANIZATION_TYPE_INDIVIDUAL = 1;</code>
   */
  public static final int ORGANIZATION_TYPE_INDIVIDUAL_VALUE = 1;
  /**
   * <pre>
   * Registered legal entity distinct from its owners (e.g. ООО / АО in RU,
   * LLC / Inc. in US, GmbH / AG in DE).
   * </pre>
   *
   * <code>ORGANIZATION_TYPE_ORGANIZATION = 2;</code>
   */
  public static final int ORGANIZATION_TYPE_ORGANIZATION_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static OrganizationType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static OrganizationType forNumber(int value) {
    switch (value) {
      case 0: return ORGANIZATION_TYPE_UNSPECIFIED;
      case 1: return ORGANIZATION_TYPE_INDIVIDUAL;
      case 2: return ORGANIZATION_TYPE_ORGANIZATION;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<OrganizationType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      OrganizationType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<OrganizationType>() {
          public OrganizationType findValueByNumber(int number) {
            return OrganizationType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return io.altessa.type.v1.OrganizationTypeOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final OrganizationType[] VALUES = values();

  public static OrganizationType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private OrganizationType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:io.altessa.type.v1.OrganizationType)
}

