// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/altessa/type/v1/organization_type.proto

package io.altessa.type.v1;

public final class OrganizationTypeProto {
  private OrganizationTypeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*io/altessa/type/v1/organization_type.p" +
      "roto\022\022io.altessa.type.v1*{\n\020Organization" +
      "Type\022!\n\035ORGANIZATION_TYPE_UNSPECIFIED\020\000\022" +
      " \n\034ORGANIZATION_TYPE_INDIVIDUAL\020\001\022\"\n\036ORG" +
      "ANIZATION_TYPE_ORGANIZATION\020\002Bj\n\022io.alte" +
      "ssa.type.v1B\025OrganizationTypeProtoP\001Z;gi" +
      "thub.com/altessa-s/proto-gen-go/io/altes" +
      "sa/type/v1;typev1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
