// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: type/v1/pagination.proto

package io.altessa.type.v1;

public final class PaginationOuterClass {
  private PaginationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_altessa_type_v1_Pagination_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_altessa_type_v1_Pagination_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030type/v1/pagination.proto\022\022io.altessa.t" +
      "ype.v1\032\037google/api/field_behavior.proto\"" +
      "e\n\nPagination\022 \n\tpage_size\030\001 \001(\005B\003\340A\007R\010p" +
      "ageSize\022\035\n\npage_token\030\002 \001(\tR\tpageToken\022\026" +
      "\n\006offset\030\003 \001(\005R\006offsetBH\n\022io.altessa.typ" +
      "e.v1P\001Z0github.com/altessa-s/proto-gen-g" +
      "o/type/v1;typev1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.FieldBehaviorProto.getDescriptor(),
        });
    internal_static_io_altessa_type_v1_Pagination_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_altessa_type_v1_Pagination_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_altessa_type_v1_Pagination_descriptor,
        new java.lang.String[] { "PageSize", "PageToken", "Offset", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.FieldBehaviorProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
