// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: type/v1/pagination.proto

package io.altessa.type.v1;

public interface PaginationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.altessa.type.v1.Pagination)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Maximum number of items the server should return. Zero requests
   * the service-defined default (1000); negative values yield
   * INVALID_ARGUMENT.
   * </pre>
   *
   * <code>int32 page_size = 1 [json_name = "pageSize", (.google.api.field_behavior) = NON_EMPTY_DEFAULT];</code>
   * @return The pageSize.
   */
  int getPageSize();

  /**
   * <pre>
   * Opaque continuation token returned in a previous list response.
   * Empty (the default) requests the first page. Mutually exclusive
   * with `offset`.
   * </pre>
   *
   * <code>string page_token = 2 [json_name = "pageToken"];</code>
   * @return The pageToken.
   */
  java.lang.String getPageToken();
  /**
   * <pre>
   * Opaque continuation token returned in a previous list response.
   * Empty (the default) requests the first page. Mutually exclusive
   * with `offset`.
   * </pre>
   *
   * <code>string page_token = 2 [json_name = "pageToken"];</code>
   * @return The bytes for pageToken.
   */
  com.google.protobuf.ByteString
      getPageTokenBytes();

  /**
   * <pre>
   * Number of items to skip from the start of the unpaginated result
   * set. Zero (the proto3 default) requests the first page. Mutually
   * exclusive with `page_token`.
   * </pre>
   *
   * <code>int32 offset = 3 [json_name = "offset"];</code>
   * @return The offset.
   */
  int getOffset();
}
