// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: type/v1/sort_direction.proto

package io.altessa.type.v1;

/**
 * <pre>
 * Ordering direction for list / search responses. Typically appears in
 * a list request next to a service-specific sort-field selector, e.g.
 *   message ListUsersRequest {
 *     string sort_by = 1;             // service-defined field name
 *     SortDirection direction = 2;
 *     Pagination pagination = 3;
 *   }
 * For multi-key ordering or per-field direction, services define their
 * own richer sort message — this enum stays a single-direction
 * primitive on purpose.
 * Zero value: unlike most enums in this package, `SortDirection` does
 * not have an `_UNSPECIFIED` zero value. `SORT_DIRECTION_ASC = 0` is
 * the natural default (matches SQL `ORDER BY` without `DESC`), so a
 * distinct sentinel would add noise without information. This is the
 * only exception in `type/v1` (see `buf.yaml` for the lint waiver).
 * Stability (AIP-180): closed and frozen at v1. There are only two
 * meaningful directions for a single sort key; consumers MAY assume
 * the value set will not grow.
 * </pre>
 *
 * Protobuf enum {@code io.altessa.type.v1.SortDirection}
 */
public enum SortDirection
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Ascending: A→Z, 0→9, oldest first. This is the default.
   * </pre>
   *
   * <code>SORT_DIRECTION_ASC = 0;</code>
   */
  SORT_DIRECTION_ASC(0),
  /**
   * <pre>
   * Descending: Z→A, 9→0, newest first.
   * </pre>
   *
   * <code>SORT_DIRECTION_DESC = 1;</code>
   */
  SORT_DIRECTION_DESC(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * Ascending: A→Z, 0→9, oldest first. This is the default.
   * </pre>
   *
   * <code>SORT_DIRECTION_ASC = 0;</code>
   */
  public static final int SORT_DIRECTION_ASC_VALUE = 0;
  /**
   * <pre>
   * Descending: Z→A, 9→0, newest first.
   * </pre>
   *
   * <code>SORT_DIRECTION_DESC = 1;</code>
   */
  public static final int SORT_DIRECTION_DESC_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static SortDirection valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static SortDirection forNumber(int value) {
    switch (value) {
      case 0: return SORT_DIRECTION_ASC;
      case 1: return SORT_DIRECTION_DESC;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SortDirection>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SortDirection> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SortDirection>() {
          public SortDirection findValueByNumber(int number) {
            return SortDirection.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return io.altessa.type.v1.SortDirectionOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final SortDirection[] VALUES = values();

  public static SortDirection valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private SortDirection(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:io.altessa.type.v1.SortDirection)
}

