// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/altessa/serviceinfo/v1/serviceinfo_service.proto

package io.altessa.serviceinfo.v1;

public interface GetServiceInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.altessa.serviceinfo.v1.GetServiceInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Runtime information for the instance handling the call.
   * </pre>
   *
   * <code>.io.altessa.serviceinfo.v1.ServiceInfo service_info = 1 [json_name = "serviceInfo"];</code>
   * @return Whether the serviceInfo field is set.
   */
  boolean hasServiceInfo();
  /**
   * <pre>
   * Runtime information for the instance handling the call.
   * </pre>
   *
   * <code>.io.altessa.serviceinfo.v1.ServiceInfo service_info = 1 [json_name = "serviceInfo"];</code>
   * @return The serviceInfo.
   */
  io.altessa.serviceinfo.v1.ServiceInfo getServiceInfo();
  /**
   * <pre>
   * Runtime information for the instance handling the call.
   * </pre>
   *
   * <code>.io.altessa.serviceinfo.v1.ServiceInfo service_info = 1 [json_name = "serviceInfo"];</code>
   */
  io.altessa.serviceinfo.v1.ServiceInfoOrBuilder getServiceInfoOrBuilder();
}
