// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/altessa/serviceinfo/v1/serviceinfo_service.proto

package io.altessa.serviceinfo.v1;

public interface GetServiceInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.altessa.serviceinfo.v1.GetServiceInfoRequest)
    com.google.protobuf.MessageOrBuilder {
}
