// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services/serviceinfo/v1/serviceinfo_service.proto

package io.altessa.serviceinfo.v1;

public final class ServiceinfoService {
  private ServiceinfoService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1services/serviceinfo/v1/serviceinfo_se" +
      "rvice.proto\022\031io.altessa.serviceinfo.v1\032\033" +
      "google/protobuf/empty.proto\032)services/se" +
      "rviceinfo/v1/serviceinfo.proto2[\n\022Servic" +
      "eInfoService\022E\n\003Get\022\026.google.protobuf.Em" +
      "pty\032&.io.altessa.serviceinfo.v1.ServiceI" +
      "nfoBf\n\031io.altessa.serviceinfo.v1P\001ZGgith" +
      "ub.com/altessa-s/proto-gen-go/services/s" +
      "erviceinfo/v1;serviceinfov1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          io.altessa.serviceinfo.v1.Serviceinfo.getDescriptor(),
        });
    com.google.protobuf.EmptyProto.getDescriptor();
    io.altessa.serviceinfo.v1.Serviceinfo.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
