// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: serviceinfo/v1/serviceinfo_service.proto
// Protobuf Java Version: 4.34.1

package io.altessa.serviceinfo.v1;

@com.google.protobuf.Generated
public final class ServiceinfoService extends com.google.protobuf.GeneratedFile {
  private ServiceinfoService() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "ServiceinfoService");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(serviceinfo/v1/serviceinfo_service.pro" +
      "to\022\031io.altessa.serviceinfo.v1\032\033google/pr" +
      "otobuf/empty.proto\032 serviceinfo/v1/servi" +
      "ceinfo.proto2[\n\022ServiceInfoService\022E\n\003Ge" +
      "t\022\026.google.protobuf.Empty\032&.io.altessa.s" +
      "erviceinfo.v1.ServiceInfoB]\n\031io.altessa." +
      "serviceinfo.v1P\001Z>github.com/altessa-s/p" +
      "roto-gen-go/serviceinfo/v1;serviceinfov1" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          io.altessa.serviceinfo.v1.Serviceinfo.getDescriptor(),
        });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.EmptyProto.getDescriptor();
    io.altessa.serviceinfo.v1.Serviceinfo.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
