// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/altessa/serviceinfo/v1/serviceinfo_service.proto

package io.altessa.serviceinfo.v1;

public final class ServiceInfoServiceProto {
  private ServiceInfoServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_altessa_serviceinfo_v1_GetServiceInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_altessa_serviceinfo_v1_GetServiceInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_altessa_serviceinfo_v1_GetServiceInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_altessa_serviceinfo_v1_GetServiceInfoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n3io/altessa/serviceinfo/v1/serviceinfo_" +
      "service.proto\022\031io.altessa.serviceinfo.v1" +
      "\032+io/altessa/serviceinfo/v1/serviceinfo." +
      "proto\"\027\n\025GetServiceInfoRequest\"c\n\026GetSer" +
      "viceInfoResponse\022I\n\014service_info\030\001 \001(\0132&" +
      ".io.altessa.serviceinfo.v1.ServiceInfoR\013" +
      "serviceInfo2\213\001\n\022ServiceInfoService\022u\n\016Ge" +
      "tServiceInfo\0220.io.altessa.serviceinfo.v1" +
      ".GetServiceInfoRequest\0321.io.altessa.serv" +
      "iceinfo.v1.GetServiceInfoResponseB\201\001\n\031io" +
      ".altessa.serviceinfo.v1B\027ServiceInfoServ" +
      "iceProtoP\001ZIgithub.com/altessa-s/proto-g" +
      "en-go/io/altessa/serviceinfo/v1;servicei" +
      "nfov1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.altessa.serviceinfo.v1.ServiceInfoProto.getDescriptor(),
        });
    internal_static_io_altessa_serviceinfo_v1_GetServiceInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_altessa_serviceinfo_v1_GetServiceInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_altessa_serviceinfo_v1_GetServiceInfoRequest_descriptor,
        new java.lang.String[] { });
    internal_static_io_altessa_serviceinfo_v1_GetServiceInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_altessa_serviceinfo_v1_GetServiceInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_altessa_serviceinfo_v1_GetServiceInfoResponse_descriptor,
        new java.lang.String[] { "ServiceInfo", });
    io.altessa.serviceinfo.v1.ServiceInfoProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
