// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/altessa/serviceinfo/v1/serviceinfo.proto

package io.altessa.serviceinfo.v1;

public final class ServiceInfoProto {
  private ServiceInfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_altessa_serviceinfo_v1_ServiceInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_altessa_serviceinfo_v1_ServiceInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_altessa_serviceinfo_v1_ServiceInfo_SemanticVersion_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_altessa_serviceinfo_v1_ServiceInfo_SemanticVersion_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_altessa_serviceinfo_v1_ServiceInfo_MetadataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_altessa_serviceinfo_v1_ServiceInfo_MetadataEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+io/altessa/serviceinfo/v1/serviceinfo." +
      "proto\022\031io.altessa.serviceinfo.v1\032\037google" +
      "/api/field_behavior.proto\032\036google/protob" +
      "uf/duration.proto\032\037google/protobuf/times" +
      "tamp.proto\"\312\010\n\013ServiceInfo\022&\n\014service_na" +
      "me\030\001 \001(\tB\003\340A\003R\013serviceName\0229\n\023service_de" +
      "scription\030\002 \001(\tB\003\340A\003H\000R\022serviceDescripti" +
      "on\210\001\001\022\'\n\nservice_id\030\003 \001(\tB\003\340A\003H\001R\tservic" +
      "eId\210\001\001\022\033\n\006leader\030\004 \001(\010B\003\340A\003R\006leader\022&\n\014f" +
      "ull_version\030\005 \001(\tB\003\340A\003R\013fullVersion\022f\n\020s" +
      "emantic_version\030\006 \001(\01326.io.altessa.servi" +
      "ceinfo.v1.ServiceInfo.SemanticVersionB\003\340" +
      "A\003R\017semanticVersion\022>\n\nbuild_time\030\007 \001(\0132" +
      "\032.google.protobuf.TimestampB\003\340A\003R\tbuildT" +
      "ime\022 \n\006branch\030\010 \001(\tB\003\340A\003H\002R\006branch\210\001\001\022 \n" +
      "\006commit\030\t \001(\tB\003\340A\003H\003R\006commit\210\001\001\022\'\n\nbuild" +
      "_tags\030\n \001(\tB\003\340A\003H\004R\tbuildTags\210\001\001\022U\n\010meta" +
      "data\030\013 \003(\01324.io.altessa.serviceinfo.v1.S" +
      "erviceInfo.MetadataEntryB\003\340A\003R\010metadata\022" +
      "%\n\tleader_id\030\r \001(\tB\003\340A\003H\005R\010leaderId\210\001\001\022C" +
      "\n\nstart_time\030\016 \001(\0132\032.google.protobuf.Tim" +
      "estampB\003\340A\003H\006R\tstartTime\210\001\001\022;\n\006uptime\030\017 " +
      "\001(\0132\031.google.protobuf.DurationB\003\340A\003H\007R\006u" +
      "ptime\210\001\001\032\235\001\n\017SemanticVersion\022\031\n\005major\030\001 " +
      "\001(\rB\003\340A\003R\005major\022\031\n\005minor\030\002 \001(\rB\003\340A\003R\005min" +
      "or\022\031\n\005patch\030\003 \001(\rB\003\340A\003R\005patch\022)\n\013pre_rel" +
      "ease\030\004 \001(\tB\003\340A\003H\000R\npreRelease\210\001\001B\016\n\014_pre" +
      "_release\032;\n\rMetadataEntry\022\020\n\003key\030\001 \001(\tR\003" +
      "key\022\024\n\005value\030\002 \001(\tR\005value:\0028\001B\026\n\024_servic" +
      "e_descriptionB\r\n\013_service_idB\t\n\007_branchB" +
      "\t\n\007_commitB\r\n\013_build_tagsB\014\n\n_leader_idB" +
      "\r\n\013_start_timeB\t\n\007_uptimeJ\004\010\014\020\rBz\n\031io.al" +
      "tessa.serviceinfo.v1B\020ServiceInfoProtoP\001" +
      "ZIgithub.com/altessa-s/proto-gen-go/io/a" +
      "ltessa/serviceinfo/v1;serviceinfov1b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_io_altessa_serviceinfo_v1_ServiceInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_altessa_serviceinfo_v1_ServiceInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_altessa_serviceinfo_v1_ServiceInfo_descriptor,
        new java.lang.String[] { "ServiceName", "ServiceDescription", "ServiceId", "Leader", "FullVersion", "SemanticVersion", "BuildTime", "Branch", "Commit", "BuildTags", "Metadata", "LeaderId", "StartTime", "Uptime", "ServiceDescription", "ServiceId", "Branch", "Commit", "BuildTags", "LeaderId", "StartTime", "Uptime", });
    internal_static_io_altessa_serviceinfo_v1_ServiceInfo_SemanticVersion_descriptor =
      internal_static_io_altessa_serviceinfo_v1_ServiceInfo_descriptor.getNestedTypes().get(0);
    internal_static_io_altessa_serviceinfo_v1_ServiceInfo_SemanticVersion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_altessa_serviceinfo_v1_ServiceInfo_SemanticVersion_descriptor,
        new java.lang.String[] { "Major", "Minor", "Patch", "PreRelease", "PreRelease", });
    internal_static_io_altessa_serviceinfo_v1_ServiceInfo_MetadataEntry_descriptor =
      internal_static_io_altessa_serviceinfo_v1_ServiceInfo_descriptor.getNestedTypes().get(1);
    internal_static_io_altessa_serviceinfo_v1_ServiceInfo_MetadataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_altessa_serviceinfo_v1_ServiceInfo_MetadataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
