// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serviceinfo/v1/serviceinfo.proto

package io.altessa.serviceinfo.v1;

public interface ServiceInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.altessa.serviceinfo.v1.ServiceInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The canonical name of the service (e.g., "user-service", "billing-api").
   * </pre>
   *
   * <code>string service_name = 1 [json_name = "serviceName"];</code>
   * @return The serviceName.
   */
  java.lang.String getServiceName();
  /**
   * <pre>
   * The canonical name of the service (e.g., "user-service", "billing-api").
   * </pre>
   *
   * <code>string service_name = 1 [json_name = "serviceName"];</code>
   * @return The bytes for serviceName.
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <pre>
   * Human-readable description of the service and its purpose.
   * </pre>
   *
   * <code>optional string service_description = 2 [json_name = "serviceDescription"];</code>
   * @return Whether the serviceDescription field is set.
   */
  boolean hasServiceDescription();
  /**
   * <pre>
   * Human-readable description of the service and its purpose.
   * </pre>
   *
   * <code>optional string service_description = 2 [json_name = "serviceDescription"];</code>
   * @return The serviceDescription.
   */
  java.lang.String getServiceDescription();
  /**
   * <pre>
   * Human-readable description of the service and its purpose.
   * </pre>
   *
   * <code>optional string service_description = 2 [json_name = "serviceDescription"];</code>
   * @return The bytes for serviceDescription.
   */
  com.google.protobuf.ByteString
      getServiceDescriptionBytes();

  /**
   * <pre>
   * Unique identifier for this specific instance of the service (e.g., a UUID or hostname-pid).
   * </pre>
   *
   * <code>optional string service_id = 3 [json_name = "serviceId"];</code>
   * @return Whether the serviceId field is set.
   */
  boolean hasServiceId();
  /**
   * <pre>
   * Unique identifier for this specific instance of the service (e.g., a UUID or hostname-pid).
   * </pre>
   *
   * <code>optional string service_id = 3 [json_name = "serviceId"];</code>
   * @return The serviceId.
   */
  java.lang.String getServiceId();
  /**
   * <pre>
   * Unique identifier for this specific instance of the service (e.g., a UUID or hostname-pid).
   * </pre>
   *
   * <code>optional string service_id = 3 [json_name = "serviceId"];</code>
   * @return The bytes for serviceId.
   */
  com.google.protobuf.ByteString
      getServiceIdBytes();

  /**
   * <pre>
   * Indicates whether this service instance is currently the leader in a distributed system.
   * True if this instance is the leader, false otherwise.
   * </pre>
   *
   * <code>bool is_leader = 4 [json_name = "isLeader"];</code>
   * @return The isLeader.
   */
  boolean getIsLeader();

  /**
   * <pre>
   * The full version string of the service (e.g., "1.2.3-alpha+build.123").
   * This may include semantic version, pre-release, and build metadata.
   * </pre>
   *
   * <code>string full_version = 5 [json_name = "fullVersion"];</code>
   * @return The fullVersion.
   */
  java.lang.String getFullVersion();
  /**
   * <pre>
   * The full version string of the service (e.g., "1.2.3-alpha+build.123").
   * This may include semantic version, pre-release, and build metadata.
   * </pre>
   *
   * <code>string full_version = 5 [json_name = "fullVersion"];</code>
   * @return The bytes for fullVersion.
   */
  com.google.protobuf.ByteString
      getFullVersionBytes();

  /**
   * <pre>
   * The structured semantic version of the service.
   * </pre>
   *
   * <code>.io.altessa.serviceinfo.v1.ServiceInfo.SemanticVersion semantic_version = 6 [json_name = "semanticVersion"];</code>
   * @return Whether the semanticVersion field is set.
   */
  boolean hasSemanticVersion();
  /**
   * <pre>
   * The structured semantic version of the service.
   * </pre>
   *
   * <code>.io.altessa.serviceinfo.v1.ServiceInfo.SemanticVersion semantic_version = 6 [json_name = "semanticVersion"];</code>
   * @return The semanticVersion.
   */
  io.altessa.serviceinfo.v1.ServiceInfo.SemanticVersion getSemanticVersion();
  /**
   * <pre>
   * The structured semantic version of the service.
   * </pre>
   *
   * <code>.io.altessa.serviceinfo.v1.ServiceInfo.SemanticVersion semantic_version = 6 [json_name = "semanticVersion"];</code>
   */
  io.altessa.serviceinfo.v1.ServiceInfo.SemanticVersionOrBuilder getSemanticVersionOrBuilder();

  /**
   * <pre>
   * The timestamp indicating when the service binary was built.
   * Human-readable timestamp representation (e.g., "2025-01-19T15:30:45Z").
   * </pre>
   *
   * <code>string build_time = 7 [json_name = "buildTime"];</code>
   * @return The buildTime.
   */
  java.lang.String getBuildTime();
  /**
   * <pre>
   * The timestamp indicating when the service binary was built.
   * Human-readable timestamp representation (e.g., "2025-01-19T15:30:45Z").
   * </pre>
   *
   * <code>string build_time = 7 [json_name = "buildTime"];</code>
   * @return The bytes for buildTime.
   */
  com.google.protobuf.ByteString
      getBuildTimeBytes();

  /**
   * <pre>
   * Name of the source code branch from which this service instance was built (e.g., "main", "develop").
   * </pre>
   *
   * <code>optional string branch = 8 [json_name = "branch"];</code>
   * @return Whether the branch field is set.
   */
  boolean hasBranch();
  /**
   * <pre>
   * Name of the source code branch from which this service instance was built (e.g., "main", "develop").
   * </pre>
   *
   * <code>optional string branch = 8 [json_name = "branch"];</code>
   * @return The branch.
   */
  java.lang.String getBranch();
  /**
   * <pre>
   * Name of the source code branch from which this service instance was built (e.g., "main", "develop").
   * </pre>
   *
   * <code>optional string branch = 8 [json_name = "branch"];</code>
   * @return The bytes for branch.
   */
  com.google.protobuf.ByteString
      getBranchBytes();

  /**
   * <pre>
   * Full Git commit hash (SHA) of the source code revision from which this service instance was built.
   * </pre>
   *
   * <code>optional string commit = 9 [json_name = "commit"];</code>
   * @return Whether the commit field is set.
   */
  boolean hasCommit();
  /**
   * <pre>
   * Full Git commit hash (SHA) of the source code revision from which this service instance was built.
   * </pre>
   *
   * <code>optional string commit = 9 [json_name = "commit"];</code>
   * @return The commit.
   */
  java.lang.String getCommit();
  /**
   * <pre>
   * Full Git commit hash (SHA) of the source code revision from which this service instance was built.
   * </pre>
   *
   * <code>optional string commit = 9 [json_name = "commit"];</code>
   * @return The bytes for commit.
   */
  com.google.protobuf.ByteString
      getCommitBytes();

  /**
   * <pre>
   * Build tags or flags used during the compilation of the service.
   * </pre>
   *
   * <code>optional string build_tags = 10 [json_name = "buildTags"];</code>
   * @return Whether the buildTags field is set.
   */
  boolean hasBuildTags();
  /**
   * <pre>
   * Build tags or flags used during the compilation of the service.
   * </pre>
   *
   * <code>optional string build_tags = 10 [json_name = "buildTags"];</code>
   * @return The buildTags.
   */
  java.lang.String getBuildTags();
  /**
   * <pre>
   * Build tags or flags used during the compilation of the service.
   * </pre>
   *
   * <code>optional string build_tags = 10 [json_name = "buildTags"];</code>
   * @return The bytes for buildTags.
   */
  com.google.protobuf.ByteString
      getBuildTagsBytes();

  /**
   * <pre>
   * A collection of key-value pairs for additional, arbitrary metadata about the service instance.
   * Keys and values are strings. Maximum 100 entries allowed.
   * </pre>
   *
   * <code>map&lt;string, string&gt; metadata = 11 [json_name = "metadata"];</code>
   */
  int getMetadataCount();
  /**
   * <pre>
   * A collection of key-value pairs for additional, arbitrary metadata about the service instance.
   * Keys and values are strings. Maximum 100 entries allowed.
   * </pre>
   *
   * <code>map&lt;string, string&gt; metadata = 11 [json_name = "metadata"];</code>
   */
  boolean containsMetadata(
      java.lang.String key);
  /**
   * Use {@link #getMetadataMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getMetadata();
  /**
   * <pre>
   * A collection of key-value pairs for additional, arbitrary metadata about the service instance.
   * Keys and values are strings. Maximum 100 entries allowed.
   * </pre>
   *
   * <code>map&lt;string, string&gt; metadata = 11 [json_name = "metadata"];</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getMetadataMap();
  /**
   * <pre>
   * A collection of key-value pairs for additional, arbitrary metadata about the service instance.
   * Keys and values are strings. Maximum 100 entries allowed.
   * </pre>
   *
   * <code>map&lt;string, string&gt; metadata = 11 [json_name = "metadata"];</code>
   */
  /* nullable */
java.lang.String getMetadataOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <pre>
   * A collection of key-value pairs for additional, arbitrary metadata about the service instance.
   * Keys and values are strings. Maximum 100 entries allowed.
   * </pre>
   *
   * <code>map&lt;string, string&gt; metadata = 11 [json_name = "metadata"];</code>
   */
  java.lang.String getMetadataOrThrow(
      java.lang.String key);

  /**
   * <pre>
   * Version of the Protobuf package or definitions that this service was compiled against.
   * </pre>
   *
   * <code>optional string proto_version = 12 [json_name = "protoVersion"];</code>
   * @return Whether the protoVersion field is set.
   */
  boolean hasProtoVersion();
  /**
   * <pre>
   * Version of the Protobuf package or definitions that this service was compiled against.
   * </pre>
   *
   * <code>optional string proto_version = 12 [json_name = "protoVersion"];</code>
   * @return The protoVersion.
   */
  java.lang.String getProtoVersion();
  /**
   * <pre>
   * Version of the Protobuf package or definitions that this service was compiled against.
   * </pre>
   *
   * <code>optional string proto_version = 12 [json_name = "protoVersion"];</code>
   * @return The bytes for protoVersion.
   */
  com.google.protobuf.ByteString
      getProtoVersionBytes();

  /**
   * <pre>
   * Identifier of the current leader instance if this node is not the leader.
   * This is useful for clients to discover the active leader.
   * </pre>
   *
   * <code>optional string leader_id = 13 [json_name = "leaderId"];</code>
   * @return Whether the leaderId field is set.
   */
  boolean hasLeaderId();
  /**
   * <pre>
   * Identifier of the current leader instance if this node is not the leader.
   * This is useful for clients to discover the active leader.
   * </pre>
   *
   * <code>optional string leader_id = 13 [json_name = "leaderId"];</code>
   * @return The leaderId.
   */
  java.lang.String getLeaderId();
  /**
   * <pre>
   * Identifier of the current leader instance if this node is not the leader.
   * This is useful for clients to discover the active leader.
   * </pre>
   *
   * <code>optional string leader_id = 13 [json_name = "leaderId"];</code>
   * @return The bytes for leaderId.
   */
  com.google.protobuf.ByteString
      getLeaderIdBytes();

  /**
   * <pre>
   * The timestamp when the service instance was started.
   * Human-readable timestamp representation in RFC 3339 format (e.g., "2025-12-18T10:15:30Z").
   * </pre>
   *
   * <code>optional string start_time = 14 [json_name = "startTime"];</code>
   * @return Whether the startTime field is set.
   */
  boolean hasStartTime();
  /**
   * <pre>
   * The timestamp when the service instance was started.
   * Human-readable timestamp representation in RFC 3339 format (e.g., "2025-12-18T10:15:30Z").
   * </pre>
   *
   * <code>optional string start_time = 14 [json_name = "startTime"];</code>
   * @return The startTime.
   */
  java.lang.String getStartTime();
  /**
   * <pre>
   * The timestamp when the service instance was started.
   * Human-readable timestamp representation in RFC 3339 format (e.g., "2025-12-18T10:15:30Z").
   * </pre>
   *
   * <code>optional string start_time = 14 [json_name = "startTime"];</code>
   * @return The bytes for startTime.
   */
  com.google.protobuf.ByteString
      getStartTimeBytes();

  /**
   * <pre>
   * The number of seconds the service has been running since startup.
   * Calculated dynamically on each request as the difference between current time and start_time.
   * </pre>
   *
   * <code>optional uint64 uptime = 15 [json_name = "uptime"];</code>
   * @return Whether the uptime field is set.
   */
  boolean hasUptime();
  /**
   * <pre>
   * The number of seconds the service has been running since startup.
   * Calculated dynamically on each request as the difference between current time and start_time.
   * </pre>
   *
   * <code>optional uint64 uptime = 15 [json_name = "uptime"];</code>
   * @return The uptime.
   */
  long getUptime();
}
